### ISSUE TITLE
Can you add NetType parsing 

### ISSUE THREAD

**Issue by itliuxing** [nielsbasjes/yauaa#100]
NetType/WIFI or NetType/4G
DATA：Mozilla/5.0 (Linux; Android 8.0; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/044109 Mobile Safari/537.36 MicroMessenger/6.6.7.1321(0x26060739) NetType/4G Language/zh_CN

**Comment by nielsbasjes** [comment]
I just had a look an this looks like a Tencent only browser feature. 
Also there are quite a few more values than just the WIFI and 4G you mentioned.
I added this.
