### ISSUE TITLE
Weird useragent strings: ";__CT_JOB_ID__:<uuid>;"

### ISSUE THREAD

**Issue by tckb** [nielsbasjes/yauaa#101]
```
;__CT_JOB_ID__:96edd000-2fa3-4d85-a9b8-052093934fbd;
;__CT_JOB_ID__:c78579f7-3fa4-4982-9497-2be8f3cf4c83;

```

@nielsbasjes  we have been seeing the above user agents for a while now. I can't seem to figure out it and categorize it. YAUAA flags it as `hacker` but, I am not so sure about it. 

Anyone seen this type?

**Comment by nielsbasjes** [comment]
I just checked some production logs and I also see this type.
The traffic level is very low, looks like a unique id per visit. 
Looking at the value itself I agree with the "not so sure" part.
Doing a quick google did not yield any info about what this really is.

For now they stay reported as "Hacker" until we understand more about what this really is.

**Comment by nielsbasjes** [comment]
I'm closing this one.
Currently I have nothing better then what I have right now.
