### ISSUE TITLE
Incorrect Device Class in some Fire OS related devices

### ISSUE THREAD

**Issue by pcct** [nielsbasjes/yauaa#1016]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 5.1.1; AFTT Build/LVY48F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.160 Mobile Safari/537.36'

**Incorrect fields**
device class: 'Fire OS 5'
device brand: ''

**Expected fields**
device class: 'Set-top box'
device brand: 'Amazon'

**Additional information**
I think the incorrect result is due to some entries in `AmazonDeviceTags` map (located in `AmazonDevices.yaml`) that are missing some values, namely the `AFTGAZL`, `AFTJULI1`, `AFTLBT962E2` and `AFTT`.

From what I can understand the `AmazonDevices.yaml` is generated based on the `AmazonDevices.csv` where the entries I mention have some empty _cells_  that are maybe causing the problem.

**Comment by nielsbasjes** [comment]
Yes, You are absolutely right.
I do not know what happened there.
So I fixed the table and updated it with the missing 2022 and 2023 devices.

**Comment by nielsbasjes** [comment]
I have released 7.18.0 with this fix in it.

**Comment by pcct** [comment]
Thank you for the quick fix.
Really nice work. 😍

**Comment by nielsbasjes** [comment]
https://try.yauaa.basjes.nl/?ua=Mozilla%2F5.0+%28Linux%3B+Android+5.1.1%3B+AFTT+Build%2FLVY48F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F108.0.5359.160+Mobile+Safari%2F537.36
