### ISSUE TITLE
Samsung device version not being extracted

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#103]
Hi,

I wanted to extract device parameters using `DEVICE_BRAND` and `DEVICE_VERSION` so I can group data by brand and then by version.

However it works very strange for samsung:
```
Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G930F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.2 Chrome/51.0.2704.106 Mobile VR Safari/537.36
DEVICE_BRAND = "Samsung"
DEVICE_VERSION = "Unknown"
```

Why `DEVICE_VERSION` is not just `SM-G930F` ? It's working fine for iPhone

```
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
DEVICE_BRAND = "Apple"
DEVICE_VERSION = "iPhone"
```

**Comment by nielsbasjes** [comment]
For the Samsung you get 

      DeviceClass                          : 'Virtual Reality'
      DeviceName                           : 'Samsung SM-G930F'
      DeviceBrand                          : 'Samsung'

for the iPhone you get

      DeviceClass                          : 'Phone'
      DeviceName                           : 'Apple iPhone'
      DeviceBrand                          : 'Apple'
      DeviceFirmwareVersion                : '15E148'
      DeviceVersion                        : 'iPhone'

Now in general I have found that I usually only look at the DeviceClass, Name and Brand.
For the DeviceName I have implemented in such a way that in general it starts with the brand (if not unknown). Only in a few exceptional cases the DeviceVersion is of any real use.

Looking at your question I think you expect the DeviceVersion to have what I actually put in DeviceName.

Is this a good enough answer for what your are looking for?

**Comment by DaimonPl** [comment]
Thx for response! Basically we are extracting fields from various user agents to be able to summarize entire data, so sometimes it's essential to have "Samsung" and "SM-G930F" parameters separately. For example to filter data by device brand and split results by model/version.

If we use Device Name we gonna have entire string concatenated already so it's not exactly the same approach.

It's similar scenario for which I reported ticket about operating system name/version

**Comment by nielsbasjes** [comment]
The DeviceVersion was originally intended as a 'version' of the device, not the type of the device.
Seems like it drifted a bit in some cases ...
The DeviceName is the combination of Brand + Type because that made a lot of things a lot easier when I wrote that. This part of the analysis is the hardest part.
Your example usage is actually already possible: Filter by DeviceBrand and then refine by DeviceName.

**Comment by nielsbasjes** [comment]
I'm closing this one as "Explained"
