### ISSUE TITLE
Incorrect detection in android 10 with chrome

### ISSUE THREAD

**Issue by paulovinisb** [nielsbasjes/yauaa#1045]
useragent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36

Incorrect: 
operatingSystemNameVersion: Android ??

Expected: 
operatingSystemNameVersionMajor: Android 10

...

This user agent is not getting the correct value for android 10.

Unlike the user agent: Mozilla/5.0 (Linux; Android 10; VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36

This user agent gets the correct value of the fields, i think its because the "K".

**Comment by nielsbasjes** [comment]
This is actually the correct result.
This is an example of the reduction of data in the user agent.
See also https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**Comment by rvcoutinho** [comment]
Hi, Niels. How are you?

It does not seem correct to me. I understand not being able to collect brand/device names. But the Android version is there. Why not to parse it?

In the case presented by Paulo, we do not have control of User-Agent capture (most of it happens in partners), so moving to client hint is not a possibility anyway. Besides, client hints can be manipulated in the same way as the user agent, right? 

Thanks in advance,

Rômulo Coutinho.

**Comment by nielsbasjes** [comment]
Please check the documentation on this https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-final-reduced-state

This is an example of a user agent where the "10" in "Android 10" is a meaningless number that is simply there to not break simple user agent analysis systems.

Because the "10" is a fake value this analyzer correctly reports the version being unknown.

**Comment by nielsbasjes** [comment]
Note that the mentioned site states
```
April 25th, 2023: the Phase 6 rollout is enabled for 50% of Android clients on M110 and above via Finch.
```
So that is why you are suddenly losing version information. I predict it will be 100% very soon.

**Comment by nielsbasjes** [comment]
Here they specify https://www.chromium.org/updates/ua-reduction/#mobile-and-tablet

    Post UA-Reduction, the new format will be:
    
    Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/<majorVersion>.0.0.0 <deviceCompat> Safari/537.36

As described here https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-6 

    In Phase 6, we change the <deviceModel> token to “K” and 
    change the <androidVersion> token to a static “10” string.

So the `<androidVersion>` is always `10` regardless of the real version of Android.

With Phases 4 and 5 the version of Android that is in the useragent is still the actual version of Android. 
With Phase 6 (which is now ~50% of the traffic) the `Android 10` token only means `It runs some version of Android` and the actual version of Android in use is no longer part of the useragent.
