### ISSUE TITLE
memory leak possibility?  

### ISSUE THREAD

**Issue by email2liyang** [nielsbasjes/yauaa#105]
we have a single UserAgentAnalyzer in our whole application
```
UserAgentAnalyzer
            .newBuilder()
            .hideMatcherLoadStats()

            // limit to only OS and Browser info - decrease RAM size to ~60Mb (full one ~220Mb)
            .withField("OperatingSystemNameVersion")
            .withField("AgentNameVersionMajor")
            .withCache(25000)
            .build()
```

at run time we only invoke 
```
UserAgent agent = userAgentAnalyzer.parse(userAgent);
```

when we deploy the code into production env, we meet very large memory usage of the application, when I dump live memory  and analyse it, we found it may be caused by yauaa, because it end out lots of duplicated agent information in the memory and it's also hashmap related.

is there any thing we need to do to clean up cache or do any clean up steps needed to do at run time to reduce the memory?

![screen shot 2018-08-07 at 3 28 07 pm](https://user-images.githubusercontent.com/443527/43761823-c3e73f38-9a58-11e8-82d7-0ea976cd7301.png)
![screen shot 2018-08-07 at 3 28 34 pm](https://user-images.githubusercontent.com/443527/43761824-c42518a8-9a58-11e8-9809-208a3b4f8074.png)
![screen shot 2018-08-07 at 3 48 34 pm](https://user-images.githubusercontent.com/443527/43762049-6d4666b2-9a59-11e8-91ea-821a6280e851.png)

**Comment by email2liyang** [comment]
from the memory analyse below, we could confirm we only have one instance of UserAgentAnalyzer in our application, but it generate lots of things in memory
![screen shot 2018-08-07 at 4 35 55 pm](https://user-images.githubusercontent.com/443527/43764493-24feb524-9a60-11e8-8c60-2172823f6324.png)

**Comment by nielsbasjes** [comment]
This is not a memory leak.

The normal memory usage of the bare library is ~250MiB-300MiB per instance.
Most of this is in a set of very large HashMaps needed to get the analysis speed so fast.

This memory usage is reduced automatically (where possible) if you request less fields.
See here for more details : https://github.com/nielsbasjes/yauaa#memory-usage

As you can see from this table
OperatingSystemNameVersion => 56MB
AgentNameVersionMajor => 17MB

Your memory dumps shows a hashmap of about 72MB which makes perfect sense.
