### ISSUE TITLE
Making commandline optional

### ISSUE THREAD

**Issue by hc-codersatlas** [nielsbasjes/yauaa#108]
Hi, is it possible to make the commandline version optional? i.e. excluding args4j and not having the startup logging? We use this in a webapp. Thanks.

**Comment by hc-codersatlas** [comment]
I'm using https://mvnrepository.com/artifact/nl.basjes.parse.useragent/yauaa/5.2 and it shows args4j still as a dependency. When I launch the app via Spring Boot lots of lines are still printed to the logs etc. Is this the wrong version to use?

**Comment by nielsbasjes** [comment]
Ah, now I see. 
I fixed the args4j dependency.
There are always some lines logged during startup of the engine, but I consider this not to be "lots".
Which lines are you referring to?

**Comment by hc-codersatlas** [comment]
If the logging is normal then all good. Thanks for fixing the dependency.

**Comment by nielsbasjes** [comment]
Just now I released version 5.3 which includes this.
