### ISSUE TITLE
Incorrect results for Amazon Echo (AEOCN)

### ISSUE THREAD

**Issue by nhmarujo** [nielsbasjes/yauaa#1110]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 7.1.2; AEOCN) AppleWebKit/537.36 (KHTML, like Gecko) Silk/112.6.3 like Chrome/112.0.5615.213 Safari/537.36'

**Expected/Incorrect fields**
Device.Class: 'Voice' (best guess, but unsure)
Device.Name: 'Echo Show 5 (2nd Gen)' (not 100% sure is that specific generation, tried to find on amazon docs but no luck)

**Additional information**
https://www.amazon.com/Echo-Show-5-2nd-Gen-2021-release/dp/B08KJN3333#tech

**Comment by nhmarujo** [comment]
Did try to find it on the links you parse to produce these files https://github.com/nielsbasjes/yauaa/blob/7a9896058fc1c62d0e9b9ea044c3563e9072f39f/analyzer/src/main/code-gen/UserAgents/Amazon/AmazonDevices.csv, but doesn't seem to figure there. But again, I couldn't find a specific section for this type of devices.

**Comment by nielsbasjes** [comment]
Thanks. 
I use the Amazon website to find all the specs. Currently it does not show the device you have, only this one https://developer.amazon.com/docs/fire-tv/device-specifications-echo-show.html

And indeed the code you have is not documented and I have found others essentially asking the same question.

The Echo Show seems like a tabletop (bed side?) TV/Speaker/Radio/Tablet/Conference call kind of device.
To me calling it a (albeit desktop, non handheld) Tablet makes the most sense right now.

**Comment by nhmarujo** [comment]
I think it is like an alarm clock. Probably "Smart Clock" would be the best categorisation for it.

**Comment by nhmarujo** [comment]
Xiaomi, for instance, calls it "Smart Clock", hence the suggestion 😄 
https://www.mi.com/global/product/mi-smart-clock/

**Comment by nhmarujo** [comment]
I was looking further and looks like Amazon also categorizes those as Smart Displays: https://www.amazon.com/gp/browse.html?node=9818047011

**Comment by nhmarujo** [comment]
They also have a category for "Smart Speakers" which I guess [in here](https://yauaa.basjes.nl/expect/fieldvalues/) would translate to Device Class "Voice"

**Comment by nielsbasjes** [comment]
Fixed: 
https://github.com/nielsbasjes/yauaa/blob/c57771ae5618af58e6149f07fbf5487bf71c9c4a/analyzer/src/main/resources/UserAgents/Amazon.yaml#L928-L952
