### ISSUE TITLE
Abstract logging with SLF4j

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#1140]
I am using your great library in a Java project. The dependency is defined with Gradle as follows:

implementation 'nl.basjes.parse.useragent:yauaa:7.22.0'

Your library makes explicit use of Log4j while my projects uses Logback through SLF4j.

The first problem is that Log4j is not defined as a dependency in the released packages. Thus, I have to manually add Log4j dependency. Once added, the second issue is that it forces my project to use Log4j. That's why I suggest you decouple the real logging implementation used from your implementation so that anybody can use its preferred logging library.

To this aim, I suggest to make use of SLF4j that was designed for this purpose.

**Comment by lpellegr** [comment]
Here is a class example where you explicitly reference Log4j classes:

https://github.com/nielsbasjes/yauaa/blob/cb015479acc1b6b1003da8203b18adf743e32c6b/analyzer/src/main/java/nl/basjes/parse/useragent/AnalyzerPreHeater.java#L21

**Comment by nielsbasjes** [comment]
Long ago I chose to not include any logging framework and only include an API that allows switching to any well known logging framework.
Back then I started with Slf4J and at some point I decided to switch to the Log4j2-API instead. The primary reason for me to look for a replacement was that at that point in time Slf4J was effectively a dead project.

The Log4j2-API offers very similar capabilities and you can still use Slf4j if that is what you prefer.

If you want to use Slf4j (with for example logback) then simply add this dependency (sorry, Maven syntax). While verifying your question I noticed that my example works fine for Slf4j 1.x but for Slf4j 2.x you need to do it slightly differently:

SLF4j 1.x:

```xml
<!-- Send all Log4j2 calls to SLF4J -->
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-to-slf4j</artifactId>
  <version>${log4j2.version}</version>
</dependency>
```

SLF4j 2.x:

```xml
<!-- Send all Log4j2 calls to SLF4J 2.x -->
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-to-slf4j</artifactId>
  <version>${log4j2.version}</version>
  <exclusions>
    <exclusion>
      <!-- Make sure the Slf4j 1.x api is excluded because we want the 2.x version -->
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

See 
- https://yauaa.basjes.nl/using/#logging-dependencies
- https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/Examples/java-slf4j/pom.xml
- https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/Examples/java-slf4j2/pom.xml
