### ISSUE TITLE
Support for Xiaomi devices

### ISSUE THREAD

**Issue by MohTaheri** [nielsbasjes/yauaa#120]
Hi,

I have found the following user agent coming from Chrome installed on Xiamoi Mi5 (after updating chrome the build field has been removed from UA).

"Mozilla/5.0 (Linux; Android 8.0.0; MI 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36"

This device instance name has been reported as Xiaomi Android Mobile.

Is it possible to include these devices in next release?

**Comment by nielsbasjes** [comment]
Yes, I fixed this example and many similar situations.
This will be part of the 5.5 release.

**Comment by MohTaheri** [comment]
Thank u so much, Niels.
