### ISSUE TITLE
Release a new version with updated dependencies

### ISSUE THREAD

**Issue by sergeykad** [nielsbasjes/yauaa#1213]
The latest release of the library includes many outdated and insecure dependencies, which is causing us a variety of problems.

As many dependencies have been updated since the last release, could we please get a new release that includes them?

**Comment by nielsbasjes** [comment]
Yes, good idea. I'll get it out soon.

**Comment by nielsbasjes** [comment]
Released 7.23.0
Should be available on maven central soon.
