### ISSUE TITLE
Support for devices

### ISSUE THREAD

**Issue by Ahmadreza-SY** [nielsbasjes/yauaa#122]
Hi,

I have found the following user agent coming from Chrome installed on Blackberry STV100-1.

`Mozilla/5.0 (Linux; Android 6.0.1; STV100-1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36`

This DeviceName has been reported as "Android Mobile" and DeviceBrand as Unknown.

Is it possible to include these devices in next release?

[This link](http://www.webapps-online.com/online-tools/user-agent-strings) provides some user-agents related to Blackberry devices. It may be useful.

**Comment by Ahmadreza-SY** [comment]
`Mozilla/5.0 (Linux; Android 8.0.0; LLD-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36`

The user-agent above is also reported as "Unknown". It's device model is "Huawei Honor 9 Lite Dual LLD-L21".

Please consider it as well.

**Comment by nielsbasjes** [comment]
For many brands I am missing the codes the detect.
I'll add these and try to find a complete list of all Huawei codes.
If you happen to know where I can find such a list that would really help.

**Comment by nielsbasjes** [comment]
I added a really large list of codes. So the two useragents you provided are fixed.

However as a consequence the memory usage doubled and the performance dropped. I'm working on this because this I cannot release. See #123
