### ISSUE TITLE
Bug report - Edge Browser Version

### ISSUE THREAD

**Issue by tb-mtg** [nielsbasjes/yauaa#130]
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]

```

- test:
#    options:
#    - 'verbose'
#    - 'init'
#    - 'only'
    input:
      user_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Desktop'
      DeviceBrand  : 'Unknown'
      DeviceCpu  : 'Intel x86_64'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Windows NT'
      OperatingSystemVersion  : '10.0'
      OperatingSystemNameVersion  : 'Windows 10.0'
      OperatingSystemVersionBuild  : '17763'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'EdgeHTML'
      LayoutEngineVersion  : '18'
      LayoutEngineVersionMajor  : '18'
      LayoutEngineNameVersion  : 'EdgeHTML 18'
      LayoutEngineNameVersionMajor  : 'EdgeHTML 18'
      AgentClass  : 'Browser'
      AgentName  : 'Edge'
      AgentVersion  : '44.17763.1.0'
      AgentVersionMajor  : '44'
      AgentNameVersion  : 'Edge 44.17763.1.0'
      AgentNameVersionMajor  : 'Edge 44'



```

**Comment by nielsbasjes** [comment]
Thanks for reporting this.

The main problem here is that this system analyses the UserAgent of Edge on Windows does NOT contain the version of Edge at all. The version 44 is not a part of the input and as such cannot be extracted.
Edge on Android and iOS do have their actual version in the UA and those are correctly extracted.
I'll have a look if I can find a mapping/lookup table somewhere that I can include to fix this.

**Comment by nielsbasjes** [comment]
I have found a usable table in Wikipedia.
As defined by Microsoft the Edge tag is
`Edge/<EdgeHTML Rev>.<Windows Build>`

Since the <Windows Build> is already in the OperatingSystemVersionBuild I'm not including it in the version of the browser.

**Comment by nielsbasjes** [comment]
I think I fixed it. 
Can you please check?
I've updated the demo site https://try.yauaa.basjes.nl/

**Comment by tb-mtg** [comment]
Yes, it now displays major version correctly.  

It would nice to also get the full version, but at least what you did is working.  

Thank you

**Comment by nielsbasjes** [comment]
I'm leaving this open for now. 
Going to see if I can do better and include the minor version (which is actually the build of the OS).

**Comment by nielsbasjes** [comment]
Hi, Can you check https://try.yauaa.basjes.nl to see if I got it right? Thanks.

**Comment by tb-mtg** [comment]
Yep, it looks to be working now. Good job
