### ISSUE TITLE
Is there a way to detect linux systems with the UserAgent?

### ISSUE THREAD

**Issue by pDiller** [nielsbasjes/yauaa#131]
Is there a method in the framework with which one can easily recognize whether the UserAgent comes from a Linux system?

For example: 

`boolean linux = UserAgent.isLinux();`

We're doing it this way right now:

```
UserAgent userAgent = UserAgentAnalyzer.newBuilder().withField("OperatingSystemNameVersion").withField("DeviceCpuBits").build().parse(userAgentString);
String nameAndVersion = userAgent.getValue("OperatingSystemNameVersion");
if (containsAny(nameAndVersion.toLowerCase(), "linux", "ubuntu"....)) {
    return OperatingSystemType.LINUX;
}
```

But here we have to enter all Linux derivatives to find out if it is a Linux system.

**Comment by nielsbasjes** [comment]
I think what you are looking for is 

`      DeviceName                           : 'Linux Desktop'
`

**Comment by pDiller** [comment]
I think this is exactly what we were looking for! Thank you!
