### ISSUE TITLE
系统版本号解析异常

### ISSUE THREAD

**Issue by Cloud-Lego** [nielsbasjes/yauaa#1316]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

解析异常

input:
      User-Agent                           : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
    expected:
      DeviceClass                          : 'Desktop'
      DeviceName                           : 'Desktop'
      DeviceBrand                          : 'Unknown'
      DeviceCpu                            : 'Intel x86_64'
      DeviceCpuBits                        : '64'
      OperatingSystemClass                 : 'Desktop'
      OperatingSystemName                  : 'Windows NT'
      OperatingSystemVersion               : '??'
      OperatingSystemVersionMajor          : '??'
      OperatingSystemNameVersion           : 'Windows NT ??'
      OperatingSystemNameVersionMajor      : 'Windows NT ??'
      OperatingSystemVersionBuild          : '??'
      LayoutEngineClass                    : 'Browser'
      LayoutEngineName                     : 'Blink'
      LayoutEngineVersion                  : '114'
      LayoutEngineVersionMajor             : '114'
      LayoutEngineNameVersion              : 'Blink 114'
      LayoutEngineNameVersionMajor         : 'Blink 114'
      AgentClass                           : 'Browser'
      AgentName                            : 'Chrome'
      AgentVersion                         : '114'
      AgentVersionMajor                    : '114'
      AgentNameVersion                     : 'Chrome 114'
      AgentNameVersionMajor                : 'Chrome 114'
      AgentInformationEmail                : 'Unknown'
      AgentInformationUrl                  : 'Unknown'
      WebviewAppName                       : 'Unknown'
      WebviewAppVersion                    : '??'
      WebviewAppVersionMajor               : '??'
      WebviewAppNameVersion                : 'Unknown ??'
      WebviewAppNameVersionMajor           : 'Unknown ??'
      NetworkType                          : 'Unknown'
      __SyntaxError__                      : 'false'

OperatingSystemNameVersionMajor      : 'Windows NT ??'  版本号未知

**Comment by nielsbasjes** [comment]
This analysis result is correct.
The version of the operating system is not present in this example.
The "10" is invalid.

This is an example of phase 5 in this
 https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-5
