### ISSUE TITLE
Wrong typification for ZTE T1002

### ISSUE THREAD

**Issue by nhmarujo** [nielsbasjes/yauaa#1330]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 12; ZTE T1002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Mobile Safari/537.36'
sec-ch-ua: '" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"'
sec-ch-ua-arch: ''
sec-ch-ua-bitness: ''
sec-ch-ua-full-version-list: '" Not A;Brand";v="99.0.0.0", "Chromium";v="99.0.4844.88", "Google Chrome";v="99.0.4844.88"'
sec-ch-ua-mobile: '?1'
sec-ch-ua-model: '"ZTE T1002"'
sec-ch-ua-platform: '"Android"'
sec-ch-ua-platform-version: '"12.0.0"'

**Expected/Incorrect fields**
DeviceClass: 'Tablet'
...

**Expected behavior**
I believe that `ZTE T1002` is considered a tablet, even if a very small one. That is what I would expect for Device Class.

**Additional information**
Additional info from GSM Arena: https://www.gsmarena.com/zte_light_tab_2_v9a-4467.php

**Comment by nhmarujo** [comment]
Note: I don't actually have one of these devices. This is the `user-agent` and `user-agent client hints` we got on a request.

**Comment by nielsbasjes** [comment]
Yes, I would call this a Tablet too.

However have a look at this specification https://www.chromium.org/updates/ua-reduction/#mobile-and-tablet

```
Mozilla/5.0 (Linux; Android <androidVersion>; <deviceModel>)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/<majorVersion>.<minorVersion> <deviceCompat>
Safari/537.36
```

Where the <deviceCompat> is defined as

```
Represents device form-factor.
The possible values are:

"Mobile"
"" (empty string, used by Tablets and Desktop)
```

So a Tablet should say "Safari".
And "Mobile Safari" means it is a Phone.

**Comment by nhmarujo** [comment]
Thank you for the insight @nielsbasjes . I understand your rationale, you need to rely on those rules even if our perception of the specific device might be different.

Thank you for the clarification and I am happy to close this as I guess there is no real room for improvement here 🙂

**Comment by nielsbasjes** [comment]
> Thank you for the insight @nielsbasjes . I understand your rationale, you need to rely on those rules even if our perception of the specific device might be different.
> 

With your additional information the `sec-ch-ua-mobile: '?1'` also means it is a phone.

So the problem here lies with the way this device was configured.

**Comment by nhmarujo** [comment]
Thank you for the additional clarification and your prompt answers. Closing

**Comment by nielsbasjes** [comment]
I have added this one as a test case
https://github.com/nielsbasjes/yauaa/blob/2df72c13909f355913604e04e69a485b50e15a1e/analyzer/src/main/resources/UserAgents/ClientHints-Tests.yaml#L2963

**Comment by nhmarujo** [comment]
Thank you @nielsbasjes . That makes sense!
