### ISSUE TITLE
commons-logging dependency

### ISSUE THREAD

**Issue by hc-codersatlas** [nielsbasjes/yauaa#137]
Hi, this project depends on slf4j and commons-logging. Is there a reason for it? It'd be good to route the logging and configuration under 1 banner and not have to run logging bridges. Can it all made to work just with slf4j? Thanks.

**Comment by nielsbasjes** [comment]
The commons-logging comes from the fact that without it Spring causes problems.
I welcome suggestions on how to get rid of it.

**Comment by nielsbasjes** [comment]
Fixed
