### ISSUE TITLE
Add support for Kryo serialization

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#138]
As stated by @hc-codersatlas in #135 :

> I tried to run this against Kryo but as classes, such as Matcher are missing no-args constructor it won't compile.

**Comment by nielsbasjes** [comment]
Implemented

**Comment by nielsbasjes** [comment]
Just now I released version 5.8 that includes this.

**Comment by hc-codersatlas** [comment]
Thanks. I gave this a test. The file generated by Kryo was close to 1MB (quite acceptable). The startup times for my test environment went from ~2000ms to ~700ms. A big improvement.
