### ISSUE TITLE
Frozen SamsungBrowser

### ISSUE THREAD

**Issue by hejiac2023** [nielsbasjes/yauaa#1386]
I found a problem with this useragent.

I known this is a frozen useragent, but the OperatingSystemNameVersion  : 'Android 10' let me confused, why isn't 'Android ??'.
Is there any method or api to known it's a frozen useragent? Currently i use the OperatingSystemNameVersion  contain or not '??' to judge the frozen useragent.

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/117.0.0.0 Mobile Safari/537.36'
    expected:
      DeviceClass  : 'Phone'
      DeviceName  : 'Samsung Android Mobile'
      DeviceBrand  : 'Samsung'
      OperatingSystemClass  : 'Mobile'
      OperatingSystemName  : 'Android'
      OperatingSystemVersion  : '10'
      OperatingSystemVersionMajor  : '10'
      OperatingSystemNameVersion  : 'Android 10'
      OperatingSystemNameVersionMajor  : 'Android 10'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '117.0'
      LayoutEngineVersionMajor  : '117'
      LayoutEngineNameVersion  : 'Blink 117.0'
      LayoutEngineNameVersionMajor  : 'Blink 117'
      AgentClass  : 'Browser'
      AgentName  : 'SamsungBrowser'
      AgentVersion  : '24.0'
      AgentVersionMajor  : '24'
      AgentNameVersion  : 'SamsungBrowser 24.0'
      AgentNameVersionMajor  : 'SamsungBrowser 24'

```

**Comment by nielsbasjes** [comment]
Fixed.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Samsung.yaml#L2301-L2410

**Comment by hejiac2023** [comment]
hey @nielsbasjes ，this issue is not only a bug report, but also a feature requirement :)

>>Is there any method or api to known it's a frozen useragent?

**Comment by nielsbasjes** [comment]
I'll have a look.
Do realize that I already in know of at least 3 different ways of reducing the ua info.

**Comment by nielsbasjes** [comment]
Q: What is the usecase you would like to know this for? Im thinking perhaps simply looking at the '??' is the best way?

**Comment by hejiac2023** [comment]
My usecase is to stat the real mobile os version, so i need to exclude the frozen ua, looking at '??' can do that, but just this way make me uncomfortable

**Comment by nielsbasjes** [comment]
I double checked.

Simply reporting if the UA was frozen is not an accurate answer to your question. Looking at the version and filtering it out if it is '??' is actually the correct way of doing what you are looking for.

An example is that when ClientHints are available then the UA was frozen and still the actual OS version is available.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Samsung.yaml#L2364-L2384

**Comment by nielsbasjes** [comment]
I have released a new version with the Samsung fix in it.
