### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by cgivre** [nielsbasjes/yauaa#14]
Hi Niels, 
I'm interested in making a UDF for Drill that uses your UA parser.  Would you be willing to release it using the Apache license?
Thanks,

**Comment by nielsbasjes** [comment]
Hi,

I'm already looking into making a Drill and a Hive plugin myself.
So at this time I'm gonna leave the licence as-is.

Niels

**Comment by cgivre** [comment]
Hi Niels, 
I took a first cut at a Drill UDF using your UA parser.  Here is the repo:  

https://github.com/cgivre/drill-useragent-function <https://github.com/cgivre/drill-useragent-function>

If you have some time, please take a look.  I’d definitely appreciate the feedback.  

Usage is as follows: 
SELECT parse_user_agent( columns[0] ) as ua FROM dfs.`/Users/cgivre/drill-httpd/ua.csv`;

This returns a map for each result as shown below:

{"DeviceClass":"Desktop","DeviceName":"Macintosh","DeviceBrand":"Apple","OperatingSystemClass":"Desktop","OperatingSystemName":"Mac OS X","OperatingSystemVersion":"10.10.1","OperatingSystemNameVersion":"Mac OS X 10.10.1","LayoutEngineClass":"Browser","LayoutEngineName":"Blink","LayoutEngineVersion":"39.0","LayoutEngineVersionMajor":"39","LayoutEngineNameVersion":"Blink 39.0","LayoutEngineNameVersionMajor":"Blink 39","AgentClass":"Browser","AgentName":"Chrome","AgentVersion":"39.0.2171.99","AgentVersionMajor":"39","AgentNameVersion":"Chrome 39.0.2171.99","AgentNameVersionMajor":"Chrome 39","DeviceCpu":"Intel"} 

Thanks,

**Comment by nielsbasjes** [comment]
Cool!
Note that if you build it the file analyzer/target/yauaa-0.9-SNAPSHOT-udf.jar contains all the dependencies in the jar file. This should make installing it a bit easier.

**Comment by cgivre** [comment]
Hi Niels, 
Thanks!  I’m going to write up some unit tests, and include some sample data for the function.  I have two questions for you:
1.  I think I did this correctly with respect to creating the “parser” object in the setup() function, however the performance still seems a little slow. Would you mind taking a look to see if you see any ways to improve the performance?  It took my machine 4 seconds to parse about 5 or 6 UA strings.  I read your documentation and it seemed as if it should be much faster, so I’m wondering if something on Drill’s end is slowing things down. 

2.  I’ve been working on the DRILL-3423 and will submit a PR shortly (https://github.com/cgivre/drill/tree/merge_branch <https://github.com/cgivre/drill/tree/merge_branch>) which completes Jim Scotts’ work on integrating your HTTPD parser into Drill.  I’d love to include the UA parser in that PR as well.   Any chance you’d reconsider changing the license to something compatible with Apache?

Thanks!  
— Charles

**Comment by nielsbasjes** [comment]
The instantiation of the parser takes about 1 second. I don't know the life cycle of Drill but this speed sound like it creates a new one for every call.

**Comment by nielsbasjes** [comment]
I updated the license to Apache.

**Comment by cgivre** [comment]
Thank you for updating the license!  Per your suggestion, I updated the docs for the Drill UDF. I did some more experimenting with it and I think I must have had some processes running in the background which was slowing down my machine, but the performance is quite good as written with Drill.

**Comment by nielsbasjes** [comment]
I see you write this:

> git clone https://github.com/nielsbasjes/yauaa.git
> cd yauaa
> mvn clean package -DskipTests
> cp <path-to-yauaa>/analyzer/target/yauaa-0.9-SNAPSHOT.jar <drill-path>/jars/3rdparty
> cp <path-to-yauaa>/analyzer/target/yauaa-0.9-SNAPSHOT-udf.jar <drill-path>/jars/3rdparty
> cp <path-to-yauaa>/devtools/target/devtools-0.9-SNAPSHOT.jar <drill-path>/jars/3rdparty

If you actually need the 'jar', the 'udf.jar' AND the 'devtools' then I need to fix something.
It was intended that you only need the 'udf.jar'. Please verify if I created a bug there.

To make thing easier for people I would recommend something like this instead:
> ( cd <drill-path>/jars/3rdparty && wget http://repo1.maven.org/maven2/nl/basjes/parse/useragent/yauaa/0.10.1/yauaa-0.10.1-udf.jar )

**Comment by nielsbasjes** [comment]
I just released 0.11

**Comment by nielsbasjes** [comment]
I think this can be closed now.
