### ISSUE TITLE
Detecting email clients from user-agent

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#1485]
I have a use case where given a user agent, I need to know if it corresponds to an email client.

It seems yauaa is not supporting this use case, even for the most popular user-agent values like Gmail:

> Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)

Is there a specific reason why yauaa does not detect such user agents, other than a need that was not a priority in its development?

**Comment by nielsbasjes** [comment]
The fact is that there are some email clients in the analysis. So it is possible.

The simple answer is I don't have good the test cases. 
I have seen a lot of useragents, knowing what kind of device it really was and how I can determine which it was is the big problem.

In many cases I have based the rules on the official specifications and personal test by really installing a browser.

So if you have testcases you know for a fact what kind of device it was, I would welcome those and try to include them.
And if you can point to specifications or ways for me to reproduce it, that really helps.

**Comment by nielsbasjes** [comment]
I just noticed that I had this exact useragent on my todo list (but I forgot about it): https://github.com/nielsbasjes/yauaa/blob/9329dfde146d1042c17b758b6ada85f4e1fcdc8d/analyzer/src/main/resources/UserAgents/EMailClients.yaml#L1209-L1214

Key question here is that I got this doing "Google Docs Sheet: Insert --> Image --> By Url ."

How do you propose I determine if it is Google Docs or GMail?

**Comment by lpellegr** [comment]
Thank you for your response.

In my situation, all the user-agent values I encounter are from email clients. This is "guaranteed" because these values come from requests made to load a pixel image included in an email, indicating that it was opened by an email client or its engine.

To assist further, I've compiled a sorted list of such user-agents, which you can find here:
https://gist.github.com/lpellegr/1e7d2186b36de8e9b3fc04a4f0656f28

I noticed there is an _AgentInformationEmail_ field. Could you explain its purpose? Would it be possible to populate this field with the email client name detected when we are in an "email context"?

If the library user knows they are parsing email user-agents, they could first check the _AgentInformationEmail_ field. Alternatively, we could introduce a new field specifically for this purpose?

**Comment by lpellegr** [comment]
A quick classification using an LLM model gives the following results:
https://gist.github.com/lpellegr/142c153b21ec9fb22f9861d6d247ee27

It could be a good starting point to identify the most popular email clients and then continue with a manual review before adding rules. If you agree to add detection for such cases and can share an example about how to create a rule for detection, I would be happy to help add new rules.

**Comment by nielsbasjes** [comment]
Thanks.
I had a quick look at this list.

Some are already classified as email client. Like this one https://try.yauaa.basjes.nl/?ua=Outlook-Express%2F7.0+%28MSIE+7.0%3B+Windows+NT+6.1%3B+WOW64%3B+Trident%2F7.0%3B+SLCC2%3B+.NET+CLR+2.0.50727%3B+.NET+CLR+3.5.30729%3B+.NET+CLR+3.0.30729%3B+Media+Center+PC+6.0%3B+MATPJS%3B+InfoPath.1%3B+.NET4.0E%3B+.NET4.0C%3B+TmstmpExt%29

AgentClass: 	Email Client
AgentName: 	Microsoft Outlook-Express
AgentVersion: 	7.0

Some cannot be seen as email clients, simply because there is nothing in the UserAgent to base such a conclusion on.

And I hope to find some that I can add to the list of email clients that can be detected.

Thanks for making this list!

**Comment by nielsbasjes** [comment]
I have released a new version with everything I could make a rule for to detect it.
https://github.com/nielsbasjes/yauaa/releases/tag/v7.27.0

**Comment by lpellegr** [comment]
Great. Thank you!
