### ISSUE TITLE
Mozilla Fenix

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#151]
Seems to be the next Firefox.
TODO Get examples of Fenix useragent.

https://github.com/mozilla-mobile/fenix/issues/1848

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Mobile_and_Tablet_indicators

**Comment by nielsbasjes** [comment]
At this point in time the useragent is

    Mozilla/5.0 (Android 7.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

So we cannot detect Fenix yet.

**Comment by kbrosnan** [comment]
The user agent will not be distinguishable from Firefox for Android. It is intended to replace Firefox for Andorid at some point in the future. The behavior to websites should be identical between Gecko versions.

**Comment by nielsbasjes** [comment]
Thanks for your explanation!
