### ISSUE TITLE
Golang port

### ISSUE THREAD

**Issue by Valve** [nielsbasjes/yauaa#152]
I apologize for using issues to ask a question.

Is there a known implementation of this project in Golang? Your project looks like a solid piece of work and having something like that for go users would be very helpful.
If there is no known go implementation, what would be the basic steps to reimplement it in go?
I guess I'd need a parser generator library and also integrate all the rule CSV files into the build process?

Thank you

**Comment by nielsbasjes** [comment]
Using the issues system for this is fine.
At this moment I am not aware of any go port. 
There is a port to .NET and to my knowledge this is the only other language port inexistence.

The parser for the useragent and for the matching language have been written using Antlr4 and for Antlr4 a go parser generator already exists.
All rule files are yaml and the actual format is pretty simple.

So the parsing everything into datastructures should be pretty easy.
It is the matching the trees that I have found to be the hardest part in making it as performant as possible.

**Comment by Valve** [comment]
@nielsbasjes  thank you for the answer.
Can you please point me to a place in the source where most of hard/manual work went?

I think that a large part of the work can be automated by leveraging antlr4 tools, but I'm curious how much of the manual programming will be left in order to implement it fully.

**Comment by nielsbasjes** [comment]
Actually the base rule engine is "simple". The hard part lies in all of the performance optimizations I implemented.
Just have a look at the "analyzer" module in the project.
