### ISSUE TITLE
java.lang.NoClassDefFoundError: nl/basjes/collections/PrefixMap

### ISSUE THREAD

**Issue by Chandira-2557** [nielsbasjes/yauaa#157]
Getting the above exception while setting up in eclipse?
Jars in classpath:
1. commons-collections4-4.1.jar
2. commons-logging-1.1.1.jar
3. slf4j-api-1.6.6.jar
4. yauaa-5.10.jar

**Comment by nielsbasjes** [comment]
Hi.

This is strange. 
The class you are missing is a class in this dependency that should simply be loaded from maven central along with all the other dependencies. 
Perhaps this is a problem specific for Eclipse? 

    <dependency>
      <groupId>nl.basjes.collections</groupId>
      <artifactId>prefixmap</artifactId>
      <version>1.1</version>
    </dependency>
