### ISSUE TITLE
Incorrect hacker indentification

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1586]
There are different deviceclass and other attributes values for very similar user agent strings (supposedly from the same user / device):

**The exact useragent**
useragent1: 'Mozilla/5.0 (Linux; Android 10; ELE-L29 Build/HUAWEIELE-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 hap/1110/huawei com.huawei.fastapp/13.5.1.300 fruitcrush.HUAWEI/1.0.4 ({"type":"shortcut","packageName":"com.huawei.android.launcher","extra":{"isNative":false,"scene":"dialog","original":{"type":"other","packageName":"fastappList"}}})'
useragent2: 'Mozilla/5.0 (Linux; Android 10; ELE-L29 Build/HUAWEIELE-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 hap/1110/huawei com.huawei.fastapp/13.5.1.300 fruitcrush.HUAWEI/1.0.4 ({"packageName":"fastappList","type":"other","extra":"{}"})'

**Expected/Incorrect fields**
deviceclass1: 'Hacker'
deviceclass2: 'Phone'

**Expected behavior**
Not sure why the first user-agent is identified as a robot, doesn't look much different from the second one.

**Comment by nielsbasjes** [comment]
The reason the first one is seen as a Hacker is because it contains '}}'
Fixed and also now reported as the "HUAWEI Quick App Center"
