### ISSUE TITLE
Mobile device with Intel Mac OS X?

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1587]
There are different deviceclass values for very similar user agent strings (supposedly from the same user / device):

**The exact useragent**
useragent1: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1'
useragent2: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15'

**Expected/Incorrect fields**
deviceclass1: 'Mobile'
deviceclass2: 'Desktop'

**Expected behavior**
The first case looks like a mobile view or something, still it's clearly a desktop device, so not sure if setting the deviceclass to 'Mobile' is the most appropriate option here.

**Comment by nielsbasjes** [comment]
This is tricky without actually knowing the real device at hand.

The first one explicitly says "Mobile/15E148" ... which makes Yauaa tag this as a Mobile device.
Same as what others have concluded here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#safari_ua_string

**Comment by nielsbasjes** [comment]
I have improved part of the handling of this case. 
The resulting tags are still mixed and probably wrong: A "Mobile" device running a Desktop OS.

Important reminder: anyone can manipulate the UserAgent to show any combination of nonsense. I suspect this is one such case you found in your accesslogs.
