### ISSUE TITLE
SHIELD Android TV recognized as Tablet

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1589]
**The exact useragent**
useragent: 'TV Bro/1.0 Mozilla/5.0 (Linux; Android 11; SHIELD Android TV Build/RQ1A.210105.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Safari/537.36'

**Expected/Incorrect fields**
deviceclass: 'Tablet' (expected: 'Set-top box')
operatingsystemclass: 'Mobile' (expected: 'Embedded')

**Expected behavior**
I'd expect similar results to 'Mozilla/5.0 (Linux; Android 11; SHIELD Android TV Build/RQ1A.210105.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Mobile Safari/537.36' parsing.

**Comment by nielsbasjes** [comment]
Do you have info on what kind/brand/model of device this is ?

**Comment by Ivan-N-Kravchenko** [comment]
Unfortunately no, all I've got is the user-agent string.

**Comment by nielsbasjes** [comment]
I predict it is this one https://play.google.com/store/apps/details?id=com.phlox.tvwebbrowser

**Comment by nielsbasjes** [comment]
Fixed
