### ISSUE TITLE
Compilation Warning (kryo)

### ISSUE THREAD

**Issue by erethir** [nielsbasjes/yauaa#159]
Hi,
I am trying to include yauaa to my project and I am getting a compilation warning when building with maven after having added a dependency to yauaa 5.10. Since I have set the compiler options `-Xlint:all -Werror`, the build fails.

This is the output:
```
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] Cannot find annotation method 'value()' in type 'com.esotericsoftware.kryo.DefaultSerializer': class file for com.esotericsoftware.kryo.DefaultSerializer not found
[WARNING] Cannot find annotation method 'value()' in type 'com.esotericsoftware.kryo.DefaultSerializer'
[INFO] 2 warnings
```

Adding a dependency to kryo as well solves the issue, but this shouldn't be necessary...

**Comment by nielsbasjes** [comment]
I have a hard time reproducing the problem you ran into.
Can you provide a (as small as possible) project that shows the problem?
Thanks

**Comment by erethir** [comment]
Sure, here's a minimal maven project that triggers the error when built with e.g. mvn clean install.
[testproject.zip](https://github.com/nielsbasjes/yauaa/files/3253520/testproject.zip)

**Comment by nielsbasjes** [comment]
Apparently if you have jdk 1.8 installed this problem does not occur.
Only when jdk 11 is installed does this occur.

**Comment by erethir** [comment]
In your [pom.xml](https://github.com/nielsbasjes/yauaa/blob/master/analyzer/pom.xml) kryo is included in the "provided" scope, so I suppose that is why it does not get included as a transitive dependency. It doesn't seem like you are repackaging it either. Here the output of `mvn dependency:tree`

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ testproject ---
[INFO] testproject:testproject:jar:1.0-SNAPSHOT
[INFO] \- nl.basjes.parse.useragent:yauaa:jar:5.10:compile
[INFO]    +- org.apache.commons:commons-text:jar:1.6:compile
[INFO]    |  \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO]    +- org.apache.commons:commons-collections4:jar:4.3:compile
[INFO]    +- nl.basjes.collections:prefixmap:jar:1.1:compile
[INFO]    \- org.slf4j:slf4j-api:jar:1.7.26:compile
```

My interpretation of it all is that building works fine (without `-xlint:all`) since I am just including your already compiled classes. The `-xlint:all` option might be analyzing your annotations for some reason, which causes it to try to load DefaultSerializer from kryo, and kryo is missing.

Running the analyzer works too because you don't need to instantiate anything dependent on kryo classes.

I don't know anything about kryo, but I suppose a possible fix would be not to annotate anything with DefaultSerializer and just document that there is a serializer available. Of course that might break backwards-compatibility though.

**Comment by nielsbasjes** [comment]
I have come to the conclusion that one of the Xlint options (namely classfile) is doing something that is a bit too strict for this situation.
So I have chosen to simply document this situation with two possible workarounds:
https://yauaa.basjes.nl/README-Usage.html#building-your-project-with--xlintall

> If your project does not use Kryo and you have this warning then there are several ways to work around this:
> 
> Disable the Xlint check that triggers this warning. Apparently this is the "classfile" so try to use -Xlint:all,-classfile instead.
> Add the otherwise needless Kryo library as a dependency to your project.
```

<dependency>
  <groupId>com.esotericsoftware</groupId>
  <artifactId>kryo</artifactId>
  <version>4.0.2</version>
</dependency>




```

**Comment by erethir** [comment]
Thanks for looking into it. You could add to the documentation that it works just adding the kryo dependency with `<scope>provided</scope>` so it's not all that bad.

**Comment by nielsbasjes** [comment]
Thanks for the tip. I updated the docs.
