### ISSUE TITLE
Linux x86_64 recognized as Android

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1590]
Two quite similar user agent strings (supposedly from the same user / device) are parsed very differently:

**The exact useragent**
useragent1: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/22.0 Chrome/111.0.5563.116 Safari/537.36'
useragent2: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Safari/537.36'

**Expected/Incorrect fields**
deviceclass1: 'Tablet'
deviceclass2: 'Desktop'
operatingsystemclass1: 'Mobile'
operatingsystemclass2: 'Mobile'
operatingsystemname1: 'Desktop'
operatingsystemname2: 'Linux'
...

**Expected behavior**
Not sure if there is a good reason for such a difference, it seems reasonable to expect identical attribute values (except versions).

**Comment by nielsbasjes** [comment]
Cause: The second one has a 'reduced' Chrome version 122 **.0.0.0** which triggers some extra rules.

**Comment by nielsbasjes** [comment]
Rootcause: The SamsungBrowser has a broken useragent. 
It ALWAYS say it is Linux even if this browser only exists on Android.
So I need custom overrides for this one

**Comment by nielsbasjes** [comment]
Fixed
