### ISSUE TITLE
google adwords bots misclassified

### ISSUE THREAD

**Issue by bkersbergen** [nielsbasjes/yauaa#16]
The google adwords bots seems to be misclassified. They should be Robot instead of Browser.
These are the user agents google is currently using:  (confirmed on https://support.google.com/adwords/answer/2404197 )

Mozilla/5.0 (Linux; Android 5.0; SM-G920A) AppleWebKit (KHTML, like Gecko) Chrome Mobile Safari (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)

I've attached code+data to reproduce the effect.

[adwordbots.pig.txt](https://github.com/nielsbasjes/yauaa/files/529688/adwordbots.pig.txt)
[bots.txt](https://github.com/nielsbasjes/yauaa/files/529689/bots.txt)

**Comment by nielsbasjes** [comment]
Fixed.
See https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/Robots.yaml#L728
