### ISSUE TITLE
UserAgent#getAvailableFieldNamesSorted returns partially sorted field names

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#160]
Let's say you have an instance of _UserAgentAnalyzer_ initialized as below:

```java
UserAgentAnalyzer userAgentAnalyzer = 
    UserAgentAnalyzer.newBuilder().withAllFields().build();
```

Then, calling `userAgentAnalyzer.getAvailableFieldNamesSorted()`, returns fields in a non lexicographically sorted order:

> DeviceClass, DeviceName, DeviceBrand, DeviceCpu, DeviceCpuBits, OperatingSystemClass, OperatingSystemName, OperatingSystemVersion, OperatingSystemNameVersion, LayoutEngineClass, LayoutEngineName, LayoutEngineVersion, LayoutEngineVersionMajor, LayoutEngineNameVersion, LayoutEngineNameVersionMajor, AgentClass, AgentName, AgentVersion, AgentVersionMajor, AgentNameVersion, AgentNameVersionMajor

**Comment by nielsbasjes** [comment]
The ordering is intended to be a logical ordering and not a lexicographical ordering.
I double checked and the current ordering is how I intended it to be.
