### ISSUE TITLE
Inconsistent Yandex Browser identification

### ISSUE THREAD

**Issue by Ivan-N-Kravchenko** [nielsbasjes/yauaa#1604]
There are different webviewappname values for very similar user agent strings (apparently from the same user / device):

**The exact useragent**
useragent1: 'Mozilla/5.0 (Linux; Android 10; M2006C3MNG Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/126.0.6478.186 YaBrowser/24.1.1.23 (lite) Mobile Safari/537.36'
useragent2: 'Mozilla/5.0 (Linux; Android 10; M2006C3MNG Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 YaBrowser/22.8.0.203 (lite) Mobile Safari/537.36'

**Expected/Incorrect fields**
webviewappname1: 'Yabrowser'
webviewappname2: 'Yandex Browser'

**Expected behavior**
Both look like Yandex Browser.

**Comment by nielsbasjes** [comment]
Fixed
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/MobileBrowser-Tests.yaml#L440-L498
