### ISSUE TITLE
Mention UserAgent class in documentation

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#161]
The library is really awesome. Congratulations! 

While trying out the library, I struggled to find constants associated with field names.

It seems constants are available in the class `nl.basjes.parse.useragent.UserAgent`. It would be really helpful to mention at least this class in the documentation.

**Comment by nielsbasjes** [comment]
I have extended the list of constants and mentioned it in the documentation.
See https://yauaa.basjes.nl/README-Usage.html#limiting-to-only-certain-fields
