### ISSUE TITLE
Field OperatingSystemVersionMajor seems to always return Unknown

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#162]
As an example, let's say you parse the following UA with the analyzer:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

then, you get `10.0` for the field _OperatingSystemVersion_ and `Unknown` for the field _OperatingSystemVersionMajor_. I was expecting `10` for the last field.

Here is another example:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10

**Comment by lpellegr** [comment]
I forgot to mention the analyzer is initialized as follows:

```
UserAgentAnalyzer userAgentAnalyzer = 
    UserAgentAnalyzer.newBuilder().withAllFields().build();
```

**Comment by lpellegr** [comment]
Oops, it seems I am expecting value for a field that is not supported. Please consider this issue as a feature request. It would make the OS version field align with others (e.g. Agent, Device, Layout Engine).

**Comment by nielsbasjes** [comment]
Feature request was implemented :)

**Comment by lpellegr** [comment]
Thanks. Is there a release planned soon?
