### ISSUE TITLE
Missing constants in nl.basjes.parse.useragent.UserAgent

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#163]
Following the [documentation](https://yauaa.basjes.nl/README-Output.html) and expected output, the class _nl.basjes.parse.useragent.UserAgent_ contains constants for all field names with the exception of the following:

- AgentNameVersion
- AgentNameVersionMajor
- LayoutEngineNameVersion
- LayoutEngineNameVersionMajor
- OperatingSystemNameVersion
- OperatingSystemVersionBuild

It would be convenient to add associated constants.

**Comment by nielsbasjes** [comment]
I'm working on a cleanup of this part of the code to make it more consistent (also looking at the other tickets you posted).

**Comment by nielsbasjes** [comment]
I've added a lot of them now.
Please check.

**Comment by lpellegr** [comment]
Thanks for the changes. It looks good to me. Is there an official release planned soon?

**Comment by nielsbasjes** [comment]
Sorry that took a while.
I found a nasty bug that caused some headache in solving it.
Just now I released version 5.11.
