### ISSUE TITLE
Semantic versioning for releases

### ISSUE THREAD

**Issue by lpellegr** [nielsbasjes/yauaa#166]
I really like your project so if I can suggest something: it would be great to follow semantic versioning to number releases:

https://semver.org/

**Comment by nielsbasjes** [comment]
I had a good look at the semver system a long time ago.
What I chose is to only use the first two as I'm almost never doing any patch releases.
So when the API changes I update to a new major version, when simply adding/improving rules it is a minor version.
The last time I used the 'patch' digit was about 3 years ago when I did something wrong while creating the release.

**Comment by lpellegr** [comment]
Many tools understand semantic versioning, that's a real benefit (also it seems you are using `v` as a prefix, which I am not sure about what it brings). Anyway, it's your choice but it's too bad!
