### ISSUE TITLE
Provide a option to not add the useless fields in init()

### ISSUE THREAD

**Issue by JamesChenX** [nielsbasjes/yauaa#173]
Because we use yauua to serve a lot of users, I very care about the performance and memory usage.
When I know yauua put 21 fields "new AgentField(UNKNOWN_VALUE)" into allFields(with 32 capacity. By the way, I think 21 is enough) in init() even I don't need it(I have used withField to tell which fields I need).

Could you please provide a option like "getOnlyRequiredFields(boolean)"?
e.g. If I call withField(UserAgent.OPERATING_SYSTEM_CLASS), it should only init and give me the allFields with only one field that is "OPERATING_SYSTEM_CLASS".

yauua is great but I want it better.

**Comment by nielsbasjes** [comment]
Yes, although the gain is probably tiny, I do see this as a memory usage improvement.

**Comment by nielsbasjes** [comment]
I've implemented it in such a way that is always goes for 'minimal memory usage' if fields are specified.
I've published a snapshot release ( 5.13-SNAPSHOT ) with this feature at https://oss.sonatype.org/content/repositories/snapshots/ .

Please verify if this works correctly.
Thanks.

**Comment by JamesChenX** [comment]
It's really kind of you and I will check it.
Really thank for your commits.

**Comment by JamesChenX** [comment]
I am afraid that the 5.13-SNAPSHOT hasn't been published because my maven cannot find it while it can find the "5.12-SNAPSHOT" version (I have configured "https://oss.sonatype.org/content/repositories/snapshots/")
But I have checked the commits https://github.com/nielsbasjes/yauaa/commit/4af29b7cce5e7cc4a75e72d895d66417b2fec2f0
As the code shows, it should work.

F.Y.I. the wantedFieldNames is a little inconsistent because it declared as Set in the member field
180: `private Set<String> wantedFieldNames = null;`
but as List in Constructor
377: `public UserAgent(String userAgentString, List<String> wantedFieldNames)`
As a result, it do a conversion in
357: `wantedFieldNames = new HashSet<>(newWantedFieldNames);`
Maybe just pass Set<String> wantedFieldNames in constructor will be more consistent.

Thank for your commits.

**Comment by nielsbasjes** [comment]
Good catch, that is inconsistent.
I'm changing this to persist in a Set and to accept any Collection (i.e. also a List) as input.

**Comment by nielsbasjes** [comment]
Apparently the snapshot release went bad because of a timeout either in my network link (unlikely) or at the Sonatype side (likely, seen it before). Retrying ...

**Comment by JamesChenX** [comment]
I have tried to download it more 10 times at different times, but the jar of 5.13-SNAPSHOT can never be downloaded (while 5.12-SNAPSHOT always OK)

**Comment by nielsbasjes** [comment]
Apparently something went wrong when releasing the snapshot.
So I did the same thing again. 
This one seems to work at my end.
Please verify.

**Comment by JamesChenX** [comment]
It still cannot not work.
What maven downloaded are these files: 
![image](https://user-images.githubusercontent.com/44962329/68062553-054d4980-fd46-11e9-9236-331abbd1989c.png)

**Comment by nielsbasjes** [comment]
Yes, I see the same.
My current assessment is that there is a problem in the maven deploy plugin.
Can you please build it locally and test it from there? 
I'm making a separate issue of this SNAPSHOT deployment thing.

**Comment by nielsbasjes** [comment]
I've just been able to deploy a SNAPSHOT that seems to work.

**Comment by JamesChenX** [comment]
OK. I have downloaded it.
It performs better than former version but I also find many codes that will affect performance.
I have listed some of them and I think maybe you can check them or I will optimize them in future as a fork.

1. Is synchronized necessary in `public synchronized UserAgent parse(UserAgent userAgent)`? And maybe we can narrow it down or remove it?
2. Is setAsHacker necessary?
3. There seem a lot of redundant codes. For example, some constants(special operators) like SET_ALL_FIELDS seem useless because I have checked the codes and it's redundant.

**By the way, I have used a cache to cache all parsed result to greatly improve performance. Hope this way can help others**
Thank you.

**Comment by nielsbasjes** [comment]
1. Yes, I think this is needed. There is only 1 place where calling it is synchronized because the code of an instance is not reentrant. I've had a look if I can change it but I think that would be too much work.
2. Yes, the setAsHacker is needed. It is only called in exceptional flows.
3. The SET_ALL_FIELDS is not useless. Really, it isn't.

The UserAgentAnalyzer class already adds a caching layer on top of UserAgentAnalyzerDirect.

**Comment by nielsbasjes** [comment]
FYI: I released version 5.13 yesterday.
