### ISSUE TITLE
Provide a method getValue without returning defaultValue in AgentField

### ISSUE THREAD

**Issue by JamesChenX** [nielsbasjes/yauaa#174]
In my case, I need to return null instead of returning defaultValue when value is null.
Otherwise, I have to check whether the returning string whether is the defaultValue in my code.

**Comment by nielsbasjes** [comment]
How about checking that the confidence < 0 ?
That is a very cheap integer compare.

**Comment by nielsbasjes** [comment]
Ok, since I see this is as a "good enough" solution and you seem to agree I'm closing this ticket.
