### ISSUE TITLE
IllegalArgumentException when parsing AgentClass

### ISSUE THREAD

**Issue by bkersbergen** [nielsbasjes/yauaa#18]
When  parsing the attached (malformed) useragent, yauaa does not catch the runtime exception and the pig-job crashes.
This effect is not wanted :) 
The error can also be reproduced by pasting it into http://analyze-useragent.appspot.com/ 

[error.txt](https://github.com/nielsbasjes/yauaa/files/608761/error.txt)
[input.txt](https://github.com/nielsbasjes/yauaa/files/608762/input.txt)

pig latin code
```
    DEFINE ParseUserAgent  nl.basjes.parse.useragent.pig.ParseUserAgent;
    REGISTER lib/yauaa-pig-0.11-udf.jar;

    raw = load 'input.txt' as (agent:chararray);
    b = foreach raw generate ParseUserAgent(agent).AgentClass;
    dump b;
```

**Comment by nielsbasjes** [comment]
Thanks!
I fixed it: 
https://github.com/nielsbasjes/yauaa/commit/f7d41ae7d0a90689134de145aa96d0e4208d0044
