### ISSUE TITLE
Except Agent class no other properties fetch by the library

### ISSUE THREAD

**Issue by moreatulr** [nielsbasjes/yauaa#181]
Yauaa library wont be able to get the Agent information except agent class, all other properties are blank.

E.g: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

It contains the browser name as Chrome but it wont pick it up.
Yauaa version: 5.8

**Comment by nielsbasjes** [comment]
I'm  not able to reproduce what you describe. Please provide the code you used to create the analyzer.

**Comment by moreatulr** [comment]
Thanks for input, it was my mistake, not added the property at the time of initialisation of analyzer. The issue is resolved.

Thanks,
Atul
