### ISSUE TITLE
the result is not have NetType

### ISSUE THREAD

**Issue by luffyace** [nielsbasjes/yauaa#182]
can you add this field?

**Comment by nielsbasjes** [comment]
Can you provide an example what you mean? A UserAgent and the expected value you want.

**Comment by nielsbasjes** [comment]
I just checked and for many situations the NetType flag as used by Tencent is already extracted.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/Tencent.yaml#L117

So please provide an example of when it does not work as you expect it to work.
