### ISSUE TITLE
i have some quesion

### ISSUE THREAD

**Issue by luffyace** [nielsbasjes/yauaa#183]
![image](https://user-images.githubusercontent.com/13696180/69702688-b9b27380-112a-11ea-936a-2bd3d9c1040e.png)
i want know  how to define the number 1100，how to get this number? i tried to defined by my self but is not ok ,so ?

**Comment by nielsbasjes** [comment]
This page documents how this works. https://yauaa.basjes.nl/Internals-MakingNewRules.html
