### ISSUE TITLE
remove `B` from UserAgentAnalyzerBuilder

### ISSUE THREAD

**Issue by robstoll** [nielsbasjes/yauaa#185]
**Is your feature request related to a problem? Please describe.**
The type parameter `B` does not make sense IMO and causes problems in language which have a stronger type inference than Java (e.g. Scala).

**Describe the solution you'd like**
Remove the type parameter `B` it does not bring any value as far as I can see. E.g. `withCache` returns `(B) this` which means ~~it would fail anyway~~ (that was a wrong thought, the cast is perfectly fine) if one would create a subtype of UserAgentAnalyzerBuilder

**Describe alternatives you've considered**
casting all the time, following an example in scala:
```
UserAgentAnalyzer.newBuilder
    .withCache(10000)
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .hideMatcherLoadStats
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .withField(UserAgent.OPERATING_SYSTEM_NAME)
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .withField(UserAgent.AGENT_NAME)
    .asInstanceOf[UserAgentAnalyzerDirectBuilder[_, _]]
    .build
    .asInstanceOf[UserAgentAnalyzer]
```

**Additional context**
I am willing to create a PR if you agree on removing `B`

**Comment by nielsbasjes** [comment]
The reason for having this parameter in there is that without it you either:
1. All the subclasses need to reimplement all the setters again from the parents just because the return type has changed. So it simplifies the maintenance and creation of additional subclasses.
2. The user of the code must know the exact inheritance of the setters and simply using them in any order is not possible.

https://stackoverflow.com/a/46036268/114196

I do understand your problems in the usage in Scala, but at this point for me the tradeoff still tips towards the way it is now. 
If you have an idea on how to solve this the also addresses these issues then please let me know.

**Comment by robstoll** [comment]
I can take a look. With subclasses you mean the UserAgentAnalyzerTesterBuilder?

**Comment by robstoll** [comment]
@nielsbasjes 
A quick outline of the idea, I'll introduce an abstract class with the type parameter `B` and a concrete one which specifies it. Sub-classes have to extend the abstract class. 
A question in this regard, what naming do you prefer `AbstractUserAgentAnalyzerBuilder`or `BaseUserAgentAnalyzerBuilder` or `UserAgentAnalyzerBuilderBase` or would you prefer a sub-class named `UserAgentAnalyzerBuilderImpl`?

**Comment by nielsbasjes** [comment]
Oh nice idea. By separating the code from the usage we can hide the generic types.
I'm going to have a good look at this later this week.
Just wondering: 
- Would this also work (for Scala users) by using a Java 8 interface with default implementations?
- Which is the better/more flexible/ more reliable implementation? Abstract class or such an interface?

**Comment by nielsbasjes** [comment]
@robstoll I've just released version 5.14 that includes this improvement.
Should arrive at maven central later today.

**Comment by nielsbasjes** [comment]
@robstoll I forgot to say: Thank you very much for finding this solution. This really helps!

**Comment by robstoll** [comment]
With pleasure :slightly_smiling_face: and thanks for the release, now it does not only work nicely but the code also looks great in Scala projects :+1:
