### ISSUE TITLE
document BC break due to slf4j 2.0.0-alpha1

### ISSUE THREAD

**Issue by robstoll** [nielsbasjes/yauaa#187]
**Describe the bug**
Due to the update of slf4j to 2.0.0-alpha1 one cannot longer use a slf4j implementation which is designed for an older API than 1.8. For instance, when using logback 1.2.3 (latest stable version), then slf4j outputs the following error:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/home/robert/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

I would prefer if only stable versions are used in yauaa or at least document that one has to exclude the slf4j dependency if the implementation does not implement alpha1 yet.

**Comment by nielsbasjes** [comment]
Oops, that version is too new then.

**Comment by nielsbasjes** [comment]
I realized this was a mistake I made.
I've immediately released version 5.14.1 which only reverts back to slf4j 1.7.29 which should fix the problem you ran into.
Please verify.

**Comment by nielsbasjes** [comment]
It arrived at maven central
https://repo1.maven.org/maven2/nl/basjes/parse/useragent/yauaa/5.14.1/

**Comment by robstoll** [comment]
Sweet, works as expected :)
