### ISSUE TITLE
Network analysis error

### ISSUE THREAD

**Issue by cfengdev** [nielsbasjes/yauaa#190]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 9; MI 9 SE Build/PKQ1.181121.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36 MMWEBID/9817 MicroMessenger/7.0.9.1560(0x27000935) Process/tools NetType/WIFI Language/zh_CN ABI/arm64'

**Expected/Incorrect fields**
fielda: '"NetworkType" -> {UserAgent$AgentField@14924} "{ value:'Wifi Language', confidence:'4', default:null }"'

**Expected behavior**
NetworkType: Wifi

**Comment by nielsbasjes** [comment]
Thanks for reporting this case.
I have fixed it.
