### ISSUE TITLE
Frozen/Reduced Chrome UA

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#193]
From Discover on Google https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome/

**Comment by nielsbasjes** [comment]
https://www.chromestatus.com/feature/5704553745874944
> We want to freeze (but not remove) the User Agent string ...

At this point I have not been able to find an indication what the "frozen" User Agent will look like.

Similar:
https://github.com/mozilla/standards-positions/issues/202#issuecomment-558294095
https://twitter.com/_scottlow/status/1206831008261132289

**Comment by nielsbasjes** [comment]
Looking at these changes we find several strings
https://chromium.googlesource.com/chromium/src.git/+/ac24e578a3694c8f4c6c35ee3b7a8d046d686e67%5E%21/

Added them as testcases.

**Comment by nielsbasjes** [comment]
Waiting for a Chrome version that actually changes this.

**Comment by nielsbasjes** [comment]
Chrome 83 now has it built in.
The code clearly makes that ALL desktop devices will show the same OS.
So Chrome on Linux or Mac will show Windows 10 !

```
const char kDesktop[] =
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, "
    "like Gecko) Chrome/%s.0.0.0 Safari/537.36";
const char kAndroid[] =
    "Mozilla/5.0 (Linux; Android 9; Unspecified Device) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/%s.0.0.0 "
    "Safari/537.36";
const char kAndroidMobile[] =
    "Mozilla/5.0 (Linux; Android 9; Unspecified Device) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/%s.0.0.0 Mobile "
    "Safari/537.36";
```

**Comment by nielsbasjes** [comment]
Keeping this issue open to track what the next Chromium/Chrome/Edge versions do.

**Comment by nielsbasjes** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=955620

**Comment by nielsbasjes** [comment]
https://www.chromium.org/updates/ua-reduction

**Comment by nielsbasjes** [comment]
https://twitter.com/nielsbasjes/status/1454743997675720707

**Comment by nielsbasjes** [comment]
Quote:
Also note that the macOS platform version was already capped to 10_15_7 in Chrome 90 for site compatibility reasons.
https://bugs.chromium.org/p/chromium/issues/detail?id=1175225

**Comment by nielsbasjes** [comment]
All known/documented reductions have been implemented.

**Comment by Chaho12** [comment]
> All known/documented reductions have been implemented.

From what version did you implement all reduced chrome ua? Is it starting from v7?
- https://github.com/nielsbasjes/yauaa/releases/tag/v7.0.0
