### ISSUE TITLE
Feature request & help generating antlr source files

### ISSUE THREAD

**Issue by trevorgithub** [nielsbasjes/yauaa#20]
I like what I’ve seen of YAUAA; thank you for your effort!  

One feature request I have would be to recognize when Internet Explorer 11 is in compatibility mode.  The user agent looks like this, for example:

`Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E)`

And YAUAA will currently output this information:

- DeviceClass = Desktop
- DeviceName = Desktop
- DeviceBrand = Unknown
- DeviceCpu = x64
- OperatingSystemClass = Desktop
- OperatingSystemName = Windows NT
- OperatingSystemVersion = Windows 7
- OperatingSystemNameVersion = Windows 7
- LayoutEngineClass = Browser
- LayoutEngineName = Trident
- LayoutEngineVersion = 7.0
- LayoutEngineVersionMajor = 7
- LayoutEngineNameVersion = Trident 7.0
- LayoutEngineNameVersionMajor = Trident 7
- AgentClass = Browser
- AgentName = Internet Explorer
- AgentVersion = 11.0
- AgentVersionMajor = 11
- AgentNameVersion = Internet Explorer 11.0`

It would be very helpful to me if there was a way to indicate that it is in IE 7 compatibility mode. 

To that end, I downloaded the source and tried to get it working. I had some problems, starting with generating the Antlr java classes. Admittedly, I am Antlr beginner, so it’s likely my process is wrong.  But for reference, what I tried was:

1. Copying UserAgent.g4 to a temporary directory.
2. From the command line, I ran antlr4 against the grammar file:

`$antlr4 UserAgent.g4`

The output was a number of errors:

- error(156): UserAgent.g4:70:6: invalid escape sequence
- error(156): UserAgent.g4:121:24: invalid escape sequence
- error(156): UserAgent.g4:130:8: invalid escape sequence
- error(156): UserAgent.g4:130:51: invalid escape sequence
- error(156): UserAgent.g4:134:8: invalid escape sequence
- error(156): UserAgent.g4:148:30: invalid escape sequence
- error(156): UserAgent.g4:149:30: invalid escape sequence

Compiling the resulting java source and using the TestRig tool failed to test the parsing failed:

`grun UserAgent userAgent -gui`

`Can't load UserAgent as lexer or parser`

When I tried the same thing with UserAgentTreeWalker.g4, antlr was able to generate the java source without any errors, and I was able to use the TestRig tool successfully.

**Comment by nielsbasjes** [comment]
Hi,

Thanks for your input.

Can you please provide me the useragent string of IE 11 in 'normal' mode aswell? I can only detect a pattern if I know what the difference is to look for. Perhaps you know of a page at Microsoft where they describe the pattern? I have not been able to find that yet.

Assume there is an IE in compatibility mode.
How do you propose I put that fact in the output?
Perhaps: LayoutEngineName = Trident Compatibility 

I found that with the latest Antlr version (released mid december) a bunch of checks got a lot better (a good thing) and now catch some problems I created in this code.

**Comment by nielsbasjes** [comment]
I fixed the antlr problems. Please check.

**Comment by trevorgithub** [comment]
Antlr problems are fixed now. Thank you.

**Comment by trevorgithub** [comment]
Thank you for considering adding support for compatibility mode.

This is the user agent string for IE 11 in compatibility view mode (64 bit processor):

`Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E)`

And this is the user agent for IE 11 not in compatibility mode (64 bit mode):

`Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko`

Notice the Trident token is still present in both modes, and has version 7 for IE 11.  This trident token is the definitive way to tell what version of IE you're using, regardless of any compatibility or [enterprise mode settings](https://blogs.msdn.microsoft.com/cjacks/2014/08/11/ie11-enterprise-mode-and-compatibility-view-are-additive-not-exclusive/).

I’m not sure why it adds in all the stuff about .NET CLR, Media Centre etc, when I’m in compatibility mode.  The above two strings were captured from a Window 7/IE 11 machine, where I turned on compatibility view mode.  This can be turn on by choosing Tools/Compatibility View settings from the Internet Explorer 11 menu.  Then add the website that you want to operate in compatibility mode.  

Note that compatibility mode is not unique to IE 11; previous versions of IE also had this dating back to IE 8.  I don’t know if non-Internet Explorer browsers have a similar concept.

The best document I could find about compatibility mode was when it was introduced in IE 8:

https://blogs.msdn.microsoft.com/ie/2008/08/27/introducing-compatibility-view/

From that doc, it talks about a new tag being added in detecting compatibility view:

> A new tag in the User Agent string allows for detection of clients viewing your site in Compatibility View. This tag is also present in the “normal” Internet Explorer 8 User Agent string.
> 
> Compatibility View: 
> User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/4.0; SLCC1; Media Center PC 5.0; .NET CLR 3.5.21022) 
> 
> Updated IE8 UA String: 
> User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; SLCC1; Media Center PC 5.0; .NET CLR 3.5.21022)

From my own experience, it seems like 'MSIE' has been dropped in IE 11 when not in compatibility mode, although I don’t have documentation to back that up.

As to this question:

> Assume there is an IE in compatibility mode.
> How do you propose I put that fact in the output?
> Perhaps: LayoutEngineName = Trident Compatibility

I would suggest we include a version number to indicate what version it is emulating. Like MSIE 7.0.  Putting the information in a layout engine section seems like a good idea to me, and a popular suggestion in this other user agent analyzer library (which never implemented it):

https://github.com/before/uadetector/issues/64

If there's anything else I can provide, please let me know.

**Comment by nielsbasjes** [comment]
I found the specification here https://msdn.microsoft.com/library/ms537503.aspx

**Comment by nielsbasjes** [comment]
As a work in progress idea I am playing with creating the output like you see below.
This would duplicate the Agent name/version fields for most browsers.
Yet for the IE in compatibility mode situations it would show a different version.

I'm still in doubt if this is the right approach.

```
# IE 11 in normal mode
- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko'
    expected:
      DeviceClass                          : 'Desktop'
      DeviceName                           : 'Desktop'
      DeviceBrand                          : 'Unknown'
      DeviceCpu                            : 'x64'
      OperatingSystemClass                 : 'Desktop'
      OperatingSystemName                  : 'Windows NT'
      OperatingSystemVersion               : 'Windows 7'
      OperatingSystemNameVersion           : 'Windows 7'
      LayoutEngineClass                    : 'Browser'
      LayoutEngineName                     : 'Trident'
      LayoutEngineVersion                  : '7.0'
      LayoutEngineVersionMajor             : '7'
      LayoutEngineNameVersion              : 'Trident 7.0'
      LayoutEngineNameVersionMajor         : 'Trident 7'
      AgentClass                           : 'Browser'
      AgentName                            : 'Internet Explorer'
      AgentVersion                         : '11.0'
      AgentVersionMajor                    : '11'
      AgentNameVersion                     : 'Internet Explorer 11.0'
      AgentNameVersionMajor                : 'Internet Explorer 11'
      AgentReportedVersion                 : '11.0'
      AgentReportedVersionMajor            : '11'
      AgentReportedNameVersion             : 'Internet Explorer 11.0'
      AgentReportedNameVersionMajor        : 'Internet Explorer 11'

# IE 11 in Compatibility mode
- test:
    input:
      user_agent_string: 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; .NET4.0E)'
    expected:
      DeviceClass                          : 'Desktop'
      DeviceName                           : 'Desktop'
      DeviceBrand                          : 'Unknown'
      DeviceCpu                            : 'x64'
      OperatingSystemClass                 : 'Desktop'
      OperatingSystemName                  : 'Windows NT'
      OperatingSystemVersion               : 'Windows 7'
      OperatingSystemNameVersion           : 'Windows 7'
      LayoutEngineClass                    : 'Browser'
      LayoutEngineName                     : 'Trident'
      LayoutEngineVersion                  : '7.0'
      LayoutEngineVersionMajor             : '7'
      LayoutEngineNameVersion              : 'Trident 7.0'
      LayoutEngineNameVersionMajor         : 'Trident 7'
      AgentClass                           : 'Browser'
      AgentName                            : 'Internet Explorer'
      AgentVersion                         : '11.0'
      AgentVersionMajor                    : '11'
      AgentNameVersion                     : 'Internet Explorer 11.0'
      AgentNameVersionMajor                : 'Internet Explorer 11'
      AgentReportedVersion                 : '7.0'
      AgentReportedVersionMajor            : '7'
      AgentReportedNameVersion             : 'Internet Explorer 7.0'
      AgentReportedNameVersionMajor        : 'Internet Explorer 7'
```

**Comment by trevorgithub** [comment]
Nice find on the specifications.  

If you didn't want to repeat the agent name/version fields for most browsers, maybe you could add (or set) an emulation set of fields only when the browser's reported name/version is different from the real agent name/number? I understand that fields aren't always set.  I don't know how they would be accessed.  Could I still ask for them by name with this syntax?

```
UserAgentAnalyzer uaa;
public ThreadState() {
    uaa = UserAgentAnalyzer
            .newBuilder()
            .withoutCache()
            .withField("DeviceClass")
            .withField("AgentNameVersionMajor")
            .withField("AgentReportedNameVersionMajor") //assume this is one of the extra fields, is often null
            .build();
```

But, I share your uncertainty whether it's better to just always include both sets of fields, even though most of the time they would be duplicated. I guess if you repeated them both, the caller would need to check that the AgentNameVersion matches the AgentReportedNameVerision; if they don't, then the they know the browser is in emulation mode.

**Comment by nielsbasjes** [comment]
I added 4 extra fields that are only filled when IE in compatibility mode is detected.
See https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/InternetExplorer.yaml#L841

**Comment by trevorgithub** [comment]
Cool, thanks.  Will you be updating the maven repository at some point?

**Comment by nielsbasjes** [comment]
I released it last week.
