### ISSUE TITLE
hive udf upgrade 

### ISSUE THREAD

**Issue by Jiwei0** [nielsbasjes/yauaa#200]
Error while compiling statement: FAILED: InvalidParserConfigurationException Two different Yauaa versions have been loaded: Runtime Library: Yauaa 5.9 (v5.9-dirty @ 2019-06-26T07:55:52Z) Rule sets : Yauaa 5.15 (v5.15 @ 2020-02-08T20:41:35Z)

**Comment by nielsbasjes** [comment]
This means you have included two different versions in the same project at the same time.
