### ISSUE TITLE
yauaa used by webapplication with tomcat causes memory leak on servlet context destroy

### ISSUE THREAD

**Issue by uhausbrand** [nielsbasjes/yauaa#203]
**Describe the bug**
We use yauaa with a tomcat webapp. We instantiate yauaa only once. We observed that after an undeployment of our webapp there is still memory used by yauaa because of references held by the class loader. On a new deployment of our webapp we have multiple instances of the resources used by yauaa which results in a memory problem.

**Component where the bug happens**
[x] Core analyzer
[ ] UDF : Flink/Beam/Nifi/...
[ ] Other

**To Reproduce**
Steps or code fragment to reproduce the behavior:
1. Create webapp with tomcat and yauaa
1.1 Generate a heap dump and verify that the informMatcherActions hash map uses a large amount of memory
2. Undeploy the webapp. Tomcat instance is still running.
3. Generate heap dump and observe that the informMatcherActions hash map is still loaded in memory.

**Expected behavior**
On servlet context destroy all used resources of the webapp should be cleaned up. For this yauaa should provide a method at UserAgenAnalyzer (or where it best fits) to remove all internally used resources.

**Screenshots**
![image](https://user-images.githubusercontent.com/3223429/76075863-07e2d880-5f9e-11ea-95db-8549b36cc9e1.png)

**Additional context**
Related to issue #105

**Comment by uhausbrand** [comment]
Currently we remove our instance to the UserAgentAnalyzer, which removes the hash map reference, but there is still stuff left (for example the Lexer is still loaded)

**Comment by nielsbasjes** [comment]
I've added a destroy() method to the analyzer to clean and wipe as much as possible.
Once you called that the analyzer becomes unusable.
I've deployed 5.16-SNAPSHOT just now that includes this. 
See also https://yauaa.basjes.nl/README-Usage.html#snapshots

Please let me know if this solves the problem you found.

**Comment by uhausbrand** [comment]
Thank you for the quick response.
I'm making some quick tests right now and can do a full check on monday.
Looks like it solves the problem.

**Comment by nielsbasjes** [comment]
I did some testing and I'm very curious about why my library leaks memory in your application.

If I run the analyzer in a clean setting (i.e. no Tomcat) and do a periodic "GC + check memory usage" I see this:

```
1: Startup + GC           --> Used memory is    3523816 bytes (    3 MiB).
2: Init Analyzer + GC     --> Used memory is   98427192 bytes (   93 MiB).
3: Run Analyzer + GC      --> Used memory is  116363408 bytes (  110 MiB).
4: Destroy Analyzer + GC  --> Used memory is   18429384 bytes (   17 MiB).
5: Null Analyzer + GC     --> Used memory is   10188592 bytes (    9 MiB).
```

if I leave out the destroy completely the en result is the same:
  
```  
1: Startup + GC           --> Used memory is    3523432 bytes (    3 MiB).
2: Init Analyzer + GC     --> Used memory is   98421608 bytes (   93 MiB).
3: Run Analyzer + GC      --> Used memory is  116360616 bytes (  110 MiB).
5: Null Analyzer + GC     --> Used memory is   10178000 bytes (    9 MiB).
```

The end result is the same in both cases: A memory usage that is much lower than the ~50MiB you reported.

**Comment by uhausbrand** [comment]
First of all, the destroy method works.
Second:
The issue lies in the combination of using tomcat and doing a application deployment without shutting tomcat down. If you do this, you need to tell tomcat which resources and classes can be destroyed, otherwise they are still referenced by some tomcat classes and won't get garbage collected.
We already do this for some of our used resources, but didn't do it for the UserAgentAnalyzer. After setting our UserAgentAnalyzer instance to null, there were still some maps and classes from your library loaded. Just for this we would need a destroy method otherwise we would need to rely on reflection to do this somehow.
