### ISSUE TITLE
Module cannot be derived 5.16.0, problem when using modules

### ISSUE THREAD

**Issue by pethers** [nielsbasjes/yauaa#205]
**Describe the bug**
Cannot use the automatic module name using 5.16.0 release

**Component where the bug happens**

**To Reproduce**
Steps or code fragment to reproduce the behavior:
$jar -d -f yauaa-5.16.jar
Unable to derive module descriptor for: yauaa-5.16.jar
Provider class org.springframework.core.ReactiveAdapterRegistry$SpringCoreBlockHoundIntegration not in module

**Expected behavior**
$jar -d -f yauaa-5.15.jar
No module descriptor found. Derived automatic module.

yauaa@5.15 automatic
requires java.base mandated
.
.
.
**Screenshots**

**Additional context**
Causing problem with Java 9+ using module-info.java and using
        requires yauaa;

**Comment by nielsbasjes** [comment]
Hi, 
So far I have not yet done anything with Java 9 modules.
Can you point me to what needs to be changed?
Niels

**Comment by pethers** [comment]
Think it is caused by the file META-INF/services/reactor.blockhound.integration.BlockHoundIntegration

**Comment by nielsbasjes** [comment]
Just now I released a new version which includes this fix.
