### ISSUE TITLE
Parse error for iOS 13 family

### ISSUE THREAD

**Issue by majidazimi** [nielsbasjes/yauaa#207]
I'm having difficulty parsing operating systems fields from `Apple iPhone iOS 13.3.1 AppleWebKit/1 Safari/1` (while activating all fields) which is parsed by majority of online parsers. 

```
- test:
    input:
      user_agent_string: 'Apple iPhone iOS 13.3.1 AppleWebKit/1 Safari/1'
    expected:
      OperatingSystemName  : 'iOS'
      OperatingSystemVersion  : '13.3.1'
      OperatingSystemVersionMajor  : '13'
      OperatingSystemNameVersion  : 'iOS 13.3.1'
      OperatingSystemNameVersionMajor  : 'iOS 13'
```

**Comment by nielsbasjes** [comment]
Hi,
What kind of situation does this appear?
I have a pretty big database with real useragents and in the whole month of February 2020 this pattern does not occur.

Normal Apple iPhone iOS 13.3.1 useragents look something like this

```Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1```

**Comment by nielsbasjes** [comment]
Fixed: https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/Apple.yaml#L1583
