### ISSUE TITLE
The version of os and browser

### ISSUE THREAD

**Issue by SheldonNeal** [nielsbasjes/yauaa#212]
Hi Niels,
is it convenient for you to add the minor version of os or browser？
And the major version keeps two number ,the minor version keeps three number, like :
major：7.3 
minor:7.3.41

`Mozilla/5.0 (Linux; Android 10; JSN-AL00 Build/HONORJSN-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.96 Mobile Safari/537.36
`
Another question,can i customize the field for parsing the ua？

I would appreciate your immediate attention to this matter.

**Comment by nielsbasjes** [comment]
Although I can add those I see too little use of those to add them generically.
This has also to do with the fact that you can simply get the version and extract the desired substring based on a regular expression. 
Any tool you use (Java, SQL, etc.) has a function to effectively do a regex extract using an expression something like this (untested) ```^([^.]+(?:\.(?:[^\.]+))?)```

**Comment by SheldonNeal** [comment]
OK,thanks for your advice,it is useful for my demand,and i have extract the information i need.
