### ISSUE TITLE
OneDrive is not recognise properly instead it recognised as Oneplus

### ISSUE THREAD

**Issue by moreatulr** [nielsbasjes/yauaa#213]
Hi,

I am trying to parse below user agent string "**OneDriveMpc-Transform_Thumbnail/1.0**" which is related to microsoft one drive. The output is:
**_DeviceClass = Unknown
DeviceName = Oneplus OnedriveMpc-Transform Thumbnail
DeviceBrand = Oneplus
OperatingSystemClass = Unknown
OperatingSystemName = Unknown
OperatingSystemVersion = ??
OperatingSystemVersionMajor = ??
OperatingSystemNameVersion = Unknown ??
OperatingSystemNameVersionMajor = Unknown ??
LayoutEngineClass = Unknown
LayoutEngineName = Unknown
LayoutEngineVersion = ??
LayoutEngineVersionMajor = ??
LayoutEngineNameVersion = Unknown ??
LayoutEngineNameVersionMajor = Unknown ??
AgentClass = Special
AgentName = OneDriveMpc-Transform_Thumbnail
AgentVersion = 1.0
AgentVersionMajor = 1_**

Can you please check.
Also if it is not supporting this then is there any chance in near future that it will support it as well.

Thanks,
Atul

**Comment by nielsbasjes** [comment]
I know OneDrive from my Windows 10 laptop.
But what is this useragent so I can classify it correctly?

**Comment by moreatulr** [comment]
Hello,

The user agent string is: **

> OneDriveMpc-Transform_Thumbnail/1.0

**

**Comment by nielsbasjes** [comment]
I understand that this is the useragent to be parsed.
What I meant to ask is what type of thing is this? 
What application does this belong to?

**Comment by moreatulr** [comment]
It is related to Microsoft OneDrive and this is found when we are working with OneDrive application.

**Comment by nielsbasjes** [comment]
Hi @moreatulr 
I did a quick simple change and now this is classified as
```
- test:
    input:
      user_agent_string: 'OneDriveMpc-Transform_Thumbnail/1.0'
    expected:
      DeviceName                            : 'OnedriveMpc-Transform_Thumbnail'
      AgentClass                            : 'Special'
      AgentName                             : 'OneDriveMpc-Transform_Thumbnail'
      AgentVersion                          : '1.0'
      AgentVersionMajor                     : '1'
      AgentNameVersion                      : 'OneDriveMpc-Transform_Thumbnail 1.0'
      AgentNameVersionMajor                 : 'OneDriveMpc-Transform_Thumbnail 1'
```

So no more OneDrive but the rest I consider still to be a bit strange.
What do you think of this result?

**Comment by moreatulr** [comment]
Hi Niels,

First of all sorry for late response.
Thanks for the options. It would be better if we have "DeviceName = OneDrive" only.
Even I am in touch with my team, they found this and I am looking more details from them that how and where they got this. Only thing they conveyed to me the it is related to "Micorsoft OneDrive"
I gone through some sites related to this useragent string and found one this. This is the [site](https://answers.microsoft.com/en-us/msoffice/forum/all/recent-activity-on-onedrive-not-by-me/ce04a10a-9348-4328-896b-0208583ec5a7). 
This will might help you.

**Comment by nielsbasjes** [comment]
OneDrive is not a device, it is a piece of software.
So i have some cleanup to do.
Thanks

**Comment by nielsbasjes** [comment]
I made the DeviceClass "Unknown" as there is no enough information available to make a different assesment.
