### ISSUE TITLE
Operating system parse error with opera + windows phone

### ISSUE THREAD

**Issue by paoloruiz** [nielsbasjes/yauaa#222]
**The exact useragent**
useragent: 'Opera/9.80 (Windows Phone; Opera Mini/8.1.0/37.6116; U; en) Presto/2.12.423 Version/12.16'

**Expected/Incorrect fields**
```
DeviceClass: 'Phone'
OperatingSystemClass: 'Mobile'
OperatingSystemName: 'Windows Phone'
```

**Expected behavior**
The windows phone on opera should be parsed without an operating system version, but as a windows phone instead of generic 'Mobile' Device class.

**Comment by nielsbasjes** [comment]
Thanks for the report.
Fixed.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/WindowsPhone.yaml#L742
