### ISSUE TITLE
HTC Sensation 4G is a phone, not a tablet

### ISSUE THREAD

**Issue by paoloruiz** [nielsbasjes/yauaa#223]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; U; Android 2.3.3; en-us; Sensation_4G Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/5.0 Safari/533.16'

**Expected/Incorrect fields**
`DeviceClass: 'Phone'`

**Expected behavior**
The HTC Sensation should be a smartphone instead of a tablet.

**Comment by nielsbasjes** [comment]
Thanks!
Fixed: https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/Android.yaml#L1869
