### ISSUE TITLE
Outlook on IOS

### ISSUE THREAD

**Issue by paoloruiz** [nielsbasjes/yauaa#224]
**The exact useragent**
useragent: 'Outlook-iOS/709.2226530.prod.iphone (3.24.1)'

**Expected/Incorrect fields**
```
DeviceClass: 'Phone'
DeviceName: 'Apple iPhone'
DeviceBrand: 'Apple'
DeviceVersion: 'iPhone'
OperatingSystemClass: 'Mobile'
OperatingSystemName: 'iOS'
AgentClass: 'Email Client'
AgentName: 'Microsoft Outlook'
AgentVersion: '3.24.1'
AgentVersionMajor: '3'
AgentNameVersion: 'Microsoft Outlook 3.24.1'
AgentNameVersionMajor: 'Microsoft Outlook 3'
```

**Expected behavior**
It looks like the outlook app on iOS is a "new browser". I'm a little unsure of the correct naming conventions for `AgentName` and such, but I've given it my best guess.

**Comment by nielsbasjes** [comment]
Thanks.
Using this example I was able to find some more variants of Outlook (olther than iOS) in my own logfiles.
Going to fix those too.

**Comment by nielsbasjes** [comment]
In this example it says "iphone".
Just to make the set complete: Do you perhaps have an example for me how it looks on an iPad ?

**Comment by paoloruiz** [comment]
Sorry, took a look through all the user agents I've received and I didn't find anything. Everything seemed to have a desktop user agent or look like the one posted above with "iphone" in the string.

**Comment by nielsbasjes** [comment]
Thanks for double checking.
I couldn't find any in the data I have either so I'm leaving it at this.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/EMailClients.yaml#L779

I have made all the names of the Outlook variants more consistent to cleanup the mess Microsoft makes of this.
Desktop: "Microsoft Outlook"
Mobile:   "Microsoft Outlook Mobile"

and "Microsoft Outlook-Express"
