### ISSUE TITLE
Question: confidence interpretation

### ISSUE THREAD

**Issue by ktulinger** [nielsbasjes/yauaa#226]
**Is your feature request related to a problem? Please describe.**
Hello, I have just a question regarding the confidence levels. I haven't found much in the documentation so, what is the range of the confidence level? I realized after some tests that it's not a number -1-100 (percent-like). So what is the actual interpretation of the number for the caller?

Is there a threshold which could be considered a "pretty confident" result for a given field?

**Comment by nielsbasjes** [comment]
No there isn't a range other than '< 0 ' means "I really do not know".
The values are simply : Higher number means more confident for that field.
Every time I get a new useragent example that is incorrectly classified I usually simply add some rules and set the scores to "a bit more confident than the other values". I.e. a bit higher ...
The highest I have right now is 1000000.
Expect in the future even higher numbers.
