### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sushmit-telaverge** [nielsbasjes/yauaa#228]
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]

While using version 5.21 in java code base. 
We are not getting the expected what we are seeing into the UI which runs on 5.22 version. 

  - user_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Roku/DVP-8.10 (468.10E04145A)'
    DeviceClass                      : 'Desktop'
    DeviceName                       : 'Desktop'
    DeviceBrand                      : 'Unknown'
    DeviceCpu                        : 'Intel x86_64'
    DeviceCpuBits                    : '64'
    OperatingSystemClass             : 'Desktop'
    OperatingSystemName              : 'Windows NT'
    OperatingSystemVersion           : '10.0'
    OperatingSystemVersionMajor      : '10'
    OperatingSystemNameVersion       : 'Windows 10.0'
    OperatingSystemNameVersionMajor  : 'Windows 10'
    LayoutEngineClass                : 'Browser'
    LayoutEngineName                 : 'Blink'
    LayoutEngineVersion              : '70.0'
    LayoutEngineVersionMajor         : '70'
    LayoutEngineNameVersion          : 'Blink 70.0'
    LayoutEngineNameVersionMajor     : 'Blink 70'
    AgentClass                       : 'Browser'
    AgentName                        : 'Chrome'
    AgentVersion                     : '70.0.3538.77'
    AgentVersionMajor                : '70'
    AgentNameVersion                 : 'Chrome 70.0.3538.77'
    AgentNameVersionMajor            : 'Chrome 70'

```

- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Roku/DVP-8.10 (468.10E04145A)'
    expected:
      DeviceClass  : 'Set-top box'
      DeviceName  : 'Roku Digital Video'
      DeviceBrand  : 'Roku'
      DeviceCpu  : 'Intel x86_64'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Embedded'
      OperatingSystemName  : 'Roku OS'
      OperatingSystemVersion  : 'DVP-8.10'
      OperatingSystemVersionMajor  : 'DVP'
      OperatingSystemNameVersion  : 'Roku OS DVP-8.10'
      OperatingSystemNameVersionMajor  : 'Roku OS DVP'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '70.0'
      LayoutEngineVersionMajor  : '70'
      LayoutEngineNameVersion  : 'Blink 70.0'
      LayoutEngineNameVersionMajor  : 'Blink 70'
      AgentClass  : 'Browser'
      AgentName  : 'Chrome'
      AgentVersion  : '70.0.3538.77'
      AgentVersionMajor  : '70'
      AgentNameVersion  : 'Chrome 70.0.3538.77'
      AgentNameVersionMajor  : 'Chrome 70'



```

**Comment by nielsbasjes** [comment]
I do not understand your bug report.
What I read is that you found that in this example version 5.21 returns a different result than 5.22.
This is not a bug; This is correct because I fixed a problem regarding Roku devices
https://github.com/nielsbasjes/yauaa/commit/886bb7305464716c57879940b0e1ebe843aa8bab

**Comment by sushmit-telaverge** [comment]
this is the latest build available : 
https://mvnrepository.com/artifact/nl.basjes.parse.useragent/yauaa/5.21 

I require latest build with ROKU fixes. Is it possible ?

**Comment by nielsbasjes** [comment]
I plan on releasing 5.22 later this week.

**Comment by nielsbasjes** [comment]
Version 5.22 which includes this fix has been released and is now available on Maven central.
