### ISSUE TITLE
How you determine device type?

### ISSUE THREAD

**Issue by shahzad31** [nielsbasjes/yauaa#229]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Tizen 2.3) AppleWebKit/538.1 (KHTML, like Gecko)'

**Expected/Incorrect fields**
os: Tizen
browser: AppleWebKit
...

**Expected behavior**
 Your analyser categorise above UA as desktop, i am curious to understand, what data point you use to determine device type into desktop/phone etc.

**Comment by nielsbasjes** [comment]
You can try this latest version here: https://try.yauaa.basjes.nl/?ua=Mozilla/5.0%20(Linux;%20Tizen%202.3)%20AppleWebKit/538.1%20(KHTML,%20like%20Gecko)

I have two questions:
- What kind of device and browser is this really?
- Given the lack of information in this useragent; Do you agree this is the best possible result? Or do you have a better suggestion?

**Comment by shahzad31** [comment]
i agree, this is the best possible scenario , i also don't have much info about it.

**Comment by nielsbasjes** [comment]
Thanks. This is then part of 5.22 (which I intend to release later this week).

**Comment by nielsbasjes** [comment]
Version 5.22 which includes this fix has been released and is now available on Maven central.
