### ISSUE TITLE
UserAgent Resolution returns different values on the website then the lib

### ISSUE THREAD

**Issue by bpb** [nielsbasjes/yauaa#236]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Google-Safety; +http://www.google.com/bot.html)'

**Incorrect fields**
DeviceClass: Phone
isHuman: true

**Expected behavior**
Running on https://try.yauaa.basjes.nl/ 
DeviceClass: 'Robot'
isHuman: 'false'

**Additional information**
Using yauaa 5.3/5.4
UAA setup and function call
```
 val  uaa = UserAgentAnalyzer.newBuilder.withCache(10000)
    .hideMatcherLoadStats
    .withField("AgentName")
    .withField("AgentVersion")
    .withField("LayoutEngineName")
    .withField("LayoutEngineVersion")
    .withField("OperatingSystemName")
    .build
    UserAgentClassifier.getDeviceClass(uaa.parse(useragent))
    UserAgentClassifier.isHuman(uaa.parse(useragent))
```

**Comment by nielsbasjes** [comment]
I added a quick test and this passes on my machine (which meets my expectations and what you describe you expect):
```
    @Test
    void testLimitedFields() {
        UserAgentAnalyzer uaa = UserAgentAnalyzer.newBuilder().withCache(10000)
            .hideMatcherLoadStats()
            .withField("AgentName")
            .withField("AgentVersion")
            .withField("LayoutEngineName")
            .withField("LayoutEngineVersion")
            .withField("OperatingSystemName")
            .build();

        String useragent = "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Google-Safety; +http://www.google.com/bot.html)";
        assertEquals(ROBOT, UserAgentClassifier.getDeviceClass(uaa.parse(useragent)));
        assertFalse(isHuman(uaa.parse(useragent)));
    }
```

**Comment by nielsbasjes** [comment]
Note that the `isHuman` is _not_ part of what the `https://try.yauaa.basjes.nl/` demo website provides.

**Comment by bpb** [comment]
I consider that this might be some environmental factors (i'm locally developing on OSX) however the behavior is the same if this is running in a AWS EC2 instance.

**Comment by nielsbasjes** [comment]
Can you please try this with a recent version. The 5.5 version is from 2018.

**Comment by nielsbasjes** [comment]
Right now I think the problem lis in the fact that you are testing with a very very old version. 
In the last few years your specific example is apparently analyzed differently in comparison with a more recent version. 

The classification simply looks at the DeviceClass and then gives an assessment; and by looking at your output the old version returns "Phone" instead of "Robot" which will yield something completely different.
 
Also since a few years a lot has improved for using it with Scala (https://yauaa.basjes.nl/README-Usage.html#scala-usage).

**Comment by bpb** [comment]
Thank you for helping with the trouble shooting. It turned out I had some issues with conflicting versions in my project.

**Comment by nielsbasjes** [comment]
NOTE: I have changed this test to output "Robot Mobile" instead of "Robot" (will be in the next release).
