### ISSUE TITLE
HUAWEI HarmonyOS UA compatibility

### ISSUE THREAD

**Issue by chenxi21039** [nielsbasjes/yauaa#268]
**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 10; HarmonyOS; ANA-AN00; HMSCore 5.3.0.312) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.1.302 Mobile Safari/537.36'

**Expected/Incorrect fields**
DeviceName: 'ANA-AN00'
DeviceBrand: 'Huawei'

**Expected behavior**

**Additional information**
If you know of specifications provided by the builder of the agent or system at hand then please provide these specifications.

**Comment by nielsbasjes** [comment]
Thanks for this new useragent.
I found another element in this one that is new to me: HarmonyOS
Working on it.

**Comment by nielsbasjes** [comment]
So in addition to the mentioned DeviceName and DeviceBrand i have now also updated the operating system information.
The output for your example is now:
```
      DeviceClass                          : 'Phone'
      DeviceName                           : 'Huawei ANA-AN00'
      DeviceBrand                          : 'Huawei'
      OperatingSystemClass                 : 'Mobile'
      OperatingSystemName                  : 'HarmonyOS'
      OperatingSystemVersion               : '??'
      OperatingSystemVersionMajor          : '??'
      OperatingSystemNameVersion           : 'HarmonyOS ??'
      OperatingSystemNameVersionMajor      : 'HarmonyOS ??'
      LayoutEngineClass                    : 'Browser'
      LayoutEngineName                     : 'Blink'
      LayoutEngineVersion                  : '88.0'
      LayoutEngineVersionMajor             : '88'
      LayoutEngineNameVersion              : 'Blink 88.0'
      LayoutEngineNameVersionMajor         : 'Blink 88'
      AgentClass                           : 'Browser'
      AgentName                            : 'HuaweiBrowser'
      AgentVersion                         : '11.1.1.302'
      AgentVersionMajor                    : '11'
      AgentNameVersion                     : 'HuaweiBrowser 11.1.1.302'
      AgentNameVersionMajor                : 'HuaweiBrowser 11'
```

The only thing I do not know is what the correct value is for the LayoutEngineName. For now I leave it unchanged which here shows `Blink`
