### ISSUE TITLE
Wechat useragent shoud parse to WeChat(Browser) 

### ISSUE THREAD

**Issue by pkptzx** [nielsbasjes/yauaa#28]
eg. wechat app useragent:

Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; PE-TL20 Build/HuaweiPE-TL20) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025440 Mobile Safari/533.1 MicroMessenger/6.2.5.53_r2565f18.621 NetType/WIFI Language/zh_CN

but if u access http://devicedetector.net/ 
result:
client (mobile app)
WeChat 6.2

**Comment by nielsbasjes** [comment]
Thanks for reporting.

**Comment by nielsbasjes** [comment]
I found that the useragents for WeChat over various platforms are a mess. So right now this is what you get for this mobile application:

      DeviceClass                          : 'Phone'
      DeviceName                           : 'PE-TL20'
      DeviceBrand                          : 'Huawei'
      OperatingSystemClass                 : 'Mobile'
      OperatingSystemName                  : 'Android'
      OperatingSystemVersion               : '4.4.2'
      OperatingSystemNameVersion           : 'Android 4.4.2'
      OperatingSystemVersionBuild          : 'HuaweiPE-TL20'
      LayoutEngineClass                    : 'Browser'
      LayoutEngineName                     : 'AppleWebKit'
      LayoutEngineVersion                  : '533.1'
      LayoutEngineVersionMajor             : '533'
      LayoutEngineNameVersion              : 'AppleWebKit 533.1'
      LayoutEngineNameVersionMajor         : 'AppleWebKit 533'
      AgentClass                           : 'Mobile App'
      AgentName                            : 'WeChat'
      AgentVersion                         : '6.2.5.53_r2565f18.621'
      AgentVersionMajor                    : '6'
      AgentNameVersion                     : 'WeChat 6.2.5.53_r2565f18.621'
      AgentNameVersionMajor                : 'WeChat 6'
      AgentLanguage                        : 'Chinese (S)'
      AgentLanguageCode                    : 'zh-cn'
      AgentSecurity                        : 'Strong security'


I updated https://analyze-useragent.appspot.com/ so you can try for yourself.
Please let me know if this output is correct.

**Comment by pkptzx** [comment]
This UserAgent is WeChat Windows Client :

> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.27.400 QQBrowser/9.0.2524.400

**Comment by pkptzx** [comment]
This UserAgent u no parse to WeChatApp
> Mozilla/5.0 (Linux; Android 5.1.1; SM801 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043024 Safari/537.36 MicroMessenger/6.5.4.1000 NetType/4G Language/zh_CN

**Comment by pkptzx** [comment]
if  contain 'MicroMessenger'  then certain WeChat App

**Comment by pkptzx** [comment]
https://github.com/piwik/device-detector/blob/master/regexes/client/mobile_apps.yml

**Comment by nielsbasjes** [comment]
Thanks. 
Can you please check  https://analyze-useragent.appspot.com/ if it now works as expected?

**Comment by pkptzx** [comment]
QQ Browser is Tencent's  Browser product.
so , Tencent's else product with Browser ,all base QQ Browser.
if only have 'MQQBrowser' tag , then QQ Browser.
if   'MicroMessenger' then  WeChat App.
if contain  'MQQBrowser' and 'QQ' then QQ app/windows app

eg.
> Mozilla/5.0 (Linux; U; Android 5.0.2; zh-cn; MI 2S Build/LRX22G) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025489 Mobile Safari/533.1 V1_AND_SQ_6.2.3_336_YYB_D **QQ/6.2.3.2700** NetType/WIFI WebP/0.3.0 Pixel/720

**Comment by nielsbasjes** [comment]
Does Tencent have a specification of this somewhere? I could not find it.

**Comment by nielsbasjes** [comment]
I did some digging in the clicklogs I have and used those as test cases. 
This was really hard to do with only the 'specifications' you gave me.
Please verify if the responses are correct now https://analyze-useragent.appspot.com/

If you know of a page with specifications I would really like to know too.

**Comment by nielsbasjes** [comment]
I'm closing this because the results look good to me.
