### ISSUE TITLE
Can you standardize the DeviceName ?

### ISSUE THREAD

**Issue by pkptzx** [nielsbasjes/yauaa#29]
now eg.

> DeviceName = SM801
DeviceBrand = Unknown

> DeviceName = **_Redmi_** Note 2
DeviceBrand = Redmi

> DeviceName = **_HUAWEI_** GRA-CL10
DeviceBrand = Huawei

> DeviceName = PE-TL20
DeviceBrand = Huawei

 I can't statistics...
if DeviceName all with deviceBrand then all data have.
if DeviceName all without deviceBrand then all data remove it.
just one way,the above.

I want...
> DeviceName = GRA-CL10
DeviceBrand = Huawei

> DeviceName = PE-TL20
DeviceBrand = Huawei

> DeviceName = Note 2
DeviceBrand = Redmi

I hope you know what I mean ..........

**Comment by nielsbasjes** [comment]
I understand you want to remove the brandname from the device brand.
Did I understand correct?

**Comment by pkptzx** [comment]
yes, you are right!

**Comment by nielsbasjes** [comment]
I am working on a solution so that it always starts with the brand. This is the cleanest thing I can do.

**Comment by nielsbasjes** [comment]
Please test on http://analyze-useragent.appspot.com/
