### ISSUE TITLE
Fails to recognize MSOffice

### ISSUE THREAD

**Issue by s-pilkhwal** [nielsbasjes/yauaa#301]
I found a problem with this useragent.
Got this user agent for MS Word  2016

```

- test:
    input:
      user_agent_string: 'Mozilla/4.0 (compatible; ms-office; MSOffice rmj)'
    expected:
      DeviceClass  : 'Unknown'
      DeviceName  : 'Unknown'
      DeviceBrand  : 'Unknown'
      OperatingSystemClass  : 'Unknown'
      OperatingSystemName  : 'Unknown'
      OperatingSystemVersion  : '??'
      OperatingSystemVersionMajor  : '??'
      OperatingSystemNameVersion  : 'Unknown ??'
      OperatingSystemNameVersionMajor  : 'Unknown ??'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Mozilla'
      LayoutEngineVersion  : '4.0'
      LayoutEngineVersionMajor  : '4'
      LayoutEngineNameVersion  : 'Mozilla 4.0'
      LayoutEngineNameVersionMajor  : 'Mozilla 4'
      AgentClass  : 'Browser'
      AgentName  : 'Netscape'
      AgentVersion  : '4.0'
      AgentVersionMajor  : '4'
      AgentNameVersion  : 'Netscape 4.0'
      AgentNameVersionMajor  : 'Netscape 4'



```

**Comment by nielsbasjes** [comment]
Thanks for the report.
This is a nasty one: It contains absolutely no information other than "MSOffice rmj".

Do you have additional infromation for me?
How do you get Word to make this request?

**Comment by s-pilkhwal** [comment]
I'm using Microsoft® Word for Microsoft 365 MSO (16.0.14326.20164) 64-bit.
I have an image url embedded in the Word document which makes a GET api call to a Nginx server to fetch the image.

**Comment by nielsbasjes** [comment]
I have implemented this one.
Do note that because of the almost complete absence of information the analysis is also very limited.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/EMailClients.yaml#L363
