### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by MaksNikita2** [nielsbasjes/yauaa#304]
Good afternoon, I downloaded your project from Git and when executing I get an error that the following package does not exist
import nl.basjes.parse.useragent.parser.UserAgentBaseListener;  (file - UserAgent)
I decided to check and really did not find this path, how can I fix this problem?

**Comment by nielsbasjes** [comment]
This is generated code.
If you build the project with the provided maven configs these will all be generated during the "generate-sources" phase in maven.
