### ISSUE TITLE
Is there a list of values?

### ISSUE THREAD

**Issue by choeflake** [nielsbasjes/yauaa#31]
Hi,

are there lists of possible values for classes? For example, a list of possible values for Device Class or Operating System Name etc.

**Comment by nielsbasjes** [comment]
For the DeviceClass it is already documented in https://github.com/nielsbasjes/yauaa/blob/master/README.md .
For the other fields I'll check what is possible.

**Comment by nielsbasjes** [comment]
I had a look at the values in the testcases in the project
`cat analyzer/src/main/resources/UserAgents/*yaml  | fgrep '   :' | grep -v '[0-9] *:' | fgrep -v '#' | sort | uniq -c `
and based on that I added a bit more documentation to the README.md

Please indicate if this is what you were looking for.

**Comment by nielsbasjes** [comment]
I'm closing this because from my perspective this is these are the lists where I actually can provide a complete list of values.

**Comment by choeflake** [comment]
Thanks! The the following (extended version of @nielsbasjes command) command prints available values for other properties like Operating System Name, or what you want.
`cat src/main/resources/UserAgents/*yaml | fgrep ' :' | grep -v '[0-9] *:' | fgrep -v '#' | sort | uniq | sed 's/\s\s//g' | sed 's/\s:/:/g' | egrep 'AgentClass:|AgentName:|DeviceBrand:|DeviceClass:|LayoutEngineName:|OperatingSystemClass:OperatingSystemName:'`

**Comment by dinikolop** [comment]
Hi @nielsbasjes ! Very useful bash command.
Is there a way to get a list of possible values for a specified field directly from the library in Java?

**Comment by nielsbasjes** [comment]
No, there isn't such a command in the library itself.
The main reason is that most fields are extracted values from the useragents. So what you put in is what comes out.
Only for a few specific "high level" fields would this make sense and those seem covered by the mentioned bash command and the documentation https://yauaa.basjes.nl/README-Output.html .
