### ISSUE TITLE
Startup error 

### ISSUE THREAD

**Issue by MaksNikita2** [nielsbasjes/yauaa#311]
When running through mvn, the following error appears 
`
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (Generate Matchers and Lookups) on project yauaa: Command execution failed.: Cannot run program ".\regen-all.sh" (in directory "C:\yauaa\analyzer"): CreateProcess error=2, ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒ -> [Help 1]

`
How can you fix it?

**Comment by nielsbasjes** [comment]
The fix: Get a linux machine or use the provided docker based development environment.

**Comment by nielsbasjes** [comment]
Please; next time you have a question use the discussions feature instead of reporting a bug.
