### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by MaksNikita2** [nielsbasjes/yauaa#313]
Good afternoon, when building a project on Ubuntu, the following errors appear in the IDE intellij idea:

1. Could not find artifact org.logstash:logstash-core:pom:7.13.0 in central (https://repo.maven.apache.org/maven2)

2. Could not find artifact org.logstash:logstash-core:jar:7.13.0 in central (https://repo.maven.apache.org/maven2)

3. Could not find artifact nl.basjes.parse.useragent:yauaa-devtools:pom:6.0 in central (https://repo.maven.apache.org/maven2)

4. Cannot resolve org.logstash:logstash-core:7.13.0

5. Cannot resolve plugin com.github.spotbugs:spotbugs-maven-plugin:4.2.3

6. Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2

7. Cannot resolve plugin com.github.spotbugs:spotbugs-maven-plugin:4.2.3

8. Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2

9. Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2

10. Cannot resolve plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2

other

how to fix them?
Could you send us instructions on how to assemble your project correctly?

**Comment by nielsbasjes** [comment]
Points 1-4 : You are not running the full build scripts. Do `mvn clean install` as documented https://yauaa.basjes.nl/Building.html

Points  5-10: You are still running in a broken environment and reporting it as a bug in my code. This is a bug at your end.
All of these exist in maven central.
https://search.maven.org/artifact/com.github.spotbugs/spotbugs-maven-plugin
https://search.maven.org/artifact/org.apache.maven.plugins/maven-checkstyle-plugin

And you are reporting the exact same problem multiple times: 6,8,9,10
