### ISSUE TITLE
Build the project 

### ISSUE THREAD

**Issue by MaksNikita2** [nielsbasjes/yauaa#317]
Good afternoon, you can ask you for instructions on how to launch your project, I tried to launch this project on Ubuntu through the command maven command mvn compile and through the mvn clean patskage and through antlr, but always some errors appear during the assembly, please, if it's not difficult for you, describe how to properly launch your project

**Comment by nielsbasjes** [comment]
https://yauaa.basjes.nl/README-WebServlet.html
