### ISSUE TITLE
user agents detected as mobile/desktop but not SmartTV

### ISSUE THREAD

**Issue by lokeshhctm** [nielsbasjes/yauaa#356]
Below user-agent are smart tv user agent but these are being detected as Mobile/ Desktop but not SmartTV

Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager

Mozilla/5.0 (SMART-TV; Linux; Tizen 5.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/5.0 TV Safari/538.1

samsung-agent/1.1

Dalvik/2.1.0 (Linux; U; Android 9; PHILIPS 4K TV Build/PTM5.200218.611) CTV

**Comment by nielsbasjes** [comment]
Thanks!

> Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager

Fixed.

> Mozilla/5.0 (SMART-TV; Linux; Tizen 5.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/5.0 TV Safari/538.1

This was already classified by the latest version as a TV. No changes.

> samsung-agent/1.1

Tricky one. 
There is no usable information in the string itself and this page indicates they think it is a Mobile Phone.

https://useragents.io/explore/platforms/java/maker/samsung-f23/uas/samsung-agent-1-1_5e401d2f52c492c9aefeb88617ecaaa8

> Dalvik/2.1.0 (Linux; U; Android 9; PHILIPS 4K TV Build/PTM5.200218.611) CTV

Fixed.

Please verify the currently produced output.
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/TV.yaml#L2247

**Comment by lokeshhctm** [comment]
when are you going to have it on mvn repo ?

**Comment by nielsbasjes** [comment]
I released 6.2 a few days ago. I'm currently releasing 6.3 (should be available later today).
