### ISSUE TITLE
Mac OS X version not detected correctly: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0

### ISSUE THREAD

**Issue by botezan** [nielsbasjes/yauaa#371]
I found a problem with this useragent.

```

- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Apple Macintosh'
      DeviceBrand  : 'Apple'
      DeviceCpu  : 'Intel'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS X'
      OperatingSystemVersion  : '10.15'
      OperatingSystemVersionMajor  : '10'
      OperatingSystemNameVersion  : 'Mac OS X 10.15'
      OperatingSystemNameVersionMajor  : 'Mac OS X 10'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Gecko'
      LayoutEngineVersion  : '94.0'
      LayoutEngineVersionMajor  : '94'
      LayoutEngineNameVersion  : 'Gecko 94.0'
      LayoutEngineNameVersionMajor  : 'Gecko 94'
      LayoutEngineBuild  : '20100101'
      AgentClass  : 'Browser'
      AgentName  : 'Firefox'
      AgentVersion  : '94.0'
      AgentVersionMajor  : '94'
      AgentNameVersion  : 'Firefox 94.0'
      AgentNameVersionMajor  : 'Firefox 94'

```

**Comment by nielsbasjes** [comment]
Please indicate the problem you see.

Do note that https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#macintosh states:

    Starting in Firefox 87, Firefox caps the reported Mac OS X version number to 10.15, 
    so macOS 11.0 Big Sur and later will be reported as "10.15" in the User-Agent string.

This means that if the firefox version is 87 or above and the Mac OS X version is 10.15 then the Mac OS X version is nonsense. I have verified this with several people who have Mac OS X version >11 and they all have only version 10.15.

So the `OperatingSystemNameVersion  : 'Mac OS X 10.15'` you showed is incorrect.

**Comment by botezan** [comment]
Thank you for having a look.
I have indeed modified the expected result in my original post.
This is in fact the output for the operating system:
_Operating System_	
Class	Desktop
Name	Mac OS X
Version	??
Version Major	??
Name Version	Mac OS X ??
Name Version Major	Mac OS X ??

I didn't know about Firefox capping the Mac OS X version to 10.15.
Does this mean that we have no way to detect the Mac OS X version anymore when Firefox is used?

**Comment by nielsbasjes** [comment]
> Does this mean that we have no way to detect the Mac OS X version anymore when Firefox is used?

Yes, unfortunately that is the case since Firefox 87.
I recently changed the output of the version to '??' to indicate this.
