### ISSUE TITLE
Googlebot Smartphone doesn't parse as Mobile

### ISSUE THREAD

**Issue by lamemind-ud** [nielsbasjes/yauaa#383]
**The exact useragent**
"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Expected/Incorrect fields**
Obtained Device Class: 'Robot'
Expected Device Class: 'Robot Mobile'

**Expected behavior**
Hello Yauaa Team, 
according to [Google docs](https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers), I think the reported user agent should be matched as Mobile.

**Comment by nielsbasjes** [comment]
[This documentation also says](https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers#user_agent_version):

    Wherever you see the string Chrome/W.X.Y.Z in the user agent strings in the table,
    W.X.Y.Z is actually a placeholder that represents the version of the Chrome browser 
    used by that user agent: for example, 41.0.2272.96. 

If you do that then you'll find this testcase that does exactly what you expect:

https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/resources/UserAgents/Robots-Google.yaml#L463

```
- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
    expected:
      DeviceClass                          : 'Robot Mobile'
      DeviceName                           : 'Google'
      DeviceBrand                          : 'Google'
      OperatingSystemClass                 : 'Cloud'
      OperatingSystemName                  : 'Google'
      OperatingSystemVersion               : 'Google'
      OperatingSystemVersionMajor          : 'Google'
      OperatingSystemNameVersion           : 'Google'
      OperatingSystemNameVersionMajor      : 'Google'
      LayoutEngineClass                    : 'Robot'
      LayoutEngineName                     : 'Googlebot'
      LayoutEngineVersion                  : 'Googlebot'
      LayoutEngineVersionMajor             : 'Googlebot'
      LayoutEngineNameVersion              : 'Googlebot'
      LayoutEngineNameVersionMajor         : 'Googlebot'
      AgentClass                           : 'Robot Mobile'
      AgentName                            : 'Googlebot'
      AgentVersion                         : '2.1'
      AgentVersionMajor                    : '2'
      AgentNameVersion                     : 'Googlebot 2.1'
      AgentNameVersionMajor                : 'Googlebot 2'
      AgentInformationUrl                  : 'http://www.google.com/bot.html'
```

**Comment by lamemind** [comment]
Ok I got it! I was testing the fake useragent
Sorry for reporting wrong bug.
Cheers
