### ISSUE TITLE
Lenovo tablets recognised as phones

### ISSUE THREAD

**Issue by mkuthan** [nielsbasjes/yauaa#39]
The following Lenovo tablets are recognised incorrectly as phones:

Mozilla/5.0 (Linux; U; Android 4.2.2; pl-pl; Lenovo B8000-H/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.2.2 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.2.2;pl-pl; Lenovo B8000-F/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.2.2 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.2.2; pl-pl; Lenovo A7600-H Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.2.2;pl-pl; Lenovo B6000-F/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.2.2 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.2.2; pl-pl; Lenovo A3500-H Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.2.2; pl-pl; Lenovo A3500-FL Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

I would prepare PR for Lenovo case but it is not so easy to start. Should I create separate config file for Lenovo or add matchers to Android.yaml? Is it possible to create single rule and put all Lenovo models into CSV file like windows oem models? How to override device class only from phone to tablet?

**Comment by nielsbasjes** [comment]
I know my current rules say that "Mobile Safari" is the key indicator that it is a Phone. 
Also finding the brand/name of the device looks for the `<device name> Build/<os build>` pattern.
These rules are based on this https://developer.chrome.com/multidevice/user-agent

Apparently Lenovo does things dramatically different....
Thanks for reporting this.
I'll have a look. 

Question: Do you know of a Lenovo specific useragent definition specification?

**Comment by nielsbasjes** [comment]
I just implemented an override for specific device tags (i.e. the ones you mentioned).
Does this change solve the problem?
https://github.com/nielsbasjes/yauaa/commit/93f5ee97d39b32a14014ae9862f18675a603644a#diff-6f8c78e1a51190dcd664b61692ae3e07

**Comment by mkuthan** [comment]
Thanks for quick fix, I'll check it today and let You know.

**Comment by nielsbasjes** [comment]
Ok, closing this for now. 
If any new occurrences of this (or other issues) are found please let me know.
Thanks
