### ISSUE TITLE
Minimal Logging / Minimal Dependencies / Usage Example

### ISSUE THREAD

**Issue by jakobvogel** [nielsbasjes/yauaa#408]
Hello! First of all, many thanks for all your work on Yauaa. It is a great tool and super-helpful for us.

## Problem Description

Unfortunately, we are currently (and since several months) stuck at version 5.x, due to the additional explicit logging dependency introduced in version 6.x. In our product, we use our own logging framework, and the team did not like any of the options that seem to be available for upgrading, adding a log4j dependency or running Yauaa in a separate Docker container. Our "solution" of just staying with 5.x does not feel right either, of course.

## Solutions?

Would it be possible to provide an example for how to set up Yauaa in an absolutely minimal way, i.e. with either no logging at all, or  with an adapter for forwarding logging messages to arbitrary frameworks?

Would it be possible to make Yauaa run without a logging component at all? (It is not a great time to add a new log4j dependency into a product that does not need it else. 😉)

## Additional Context

We use Yauaa to process user agent strings before storing the respective interaction events in a ClickHouse database. The idea is to "enrich" raw events with data obtained via Yauaa in order to be able to support more generic SQL queries like "How many of our active users use versions of Windows/iPads/etc.?" that would not be possible with raw UA strings. Therefore, we do not really care about errors occurring there, particularly concerning more exotic UAs like search engine robots. We are happy if the majority of user agents used by our human customers are identified, but we would likely not check for UA analysis problems and live with partial/missing data in such records.

Many thanks!

**Comment by nielsbasjes** [comment]
Hi,
In the example directory I have tried to show the bare minimum "normal" way of using Yauaa. For me this is also a simple integration test to show it all still works in all scenarios.
The Java version (using Log4J2) is here: https://github.com/nielsbasjes/yauaa/tree/master/examples/java

To help you guys on the way I have added the same example which does not use Log4j2 and only uses SLF4J:
https://github.com/nielsbasjes/yauaa/tree/master/examples/java-slf4j

Does this solve what you need?

**Comment by nielsbasjes** [comment]
Note that if you use Log4j2 then you can still turn off all logging with a `log4j2.xml` config file with something like this ( found here https://stackoverflow.com/a/53509257/114196 )

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    <Loggers>
        <Root level="off"/>
    </Loggers>
</Configuration>
```

**Comment by jakobvogel** [comment]
Hello @nielsbasjes — Wow, thanks a lot for your super-quick response and for the new example!

Could you please clarify: Up to and including version 5, Yauaa used SLF4J directly and listed it as dependency? That is, in terms of logging, the minimal example does the same, just with the additional "detour" via the `log4j-to-slf4j` adapter? Is my understanding correct?

Many thanks again, and merry christmas!

**Comment by nielsbasjes** [comment]
@jakobvogel 
The way these logging frameworks work is that they have an API (i.e. the classes you use in your application) and the actual logging implementation.
Now both SLF4J and Log4j(2) have an API and an implementation and for both there is the option to forward the calls to their API to a different logging system.
So you can send logging using the log4j API to slf4j when you include the bridging jar file (the `log4j-to-slf4j` jar).

Because I like the Log4j2 API better than SLF4J and also because SLF4J did not have any releases for about 18 months I chose to switch APIs last summer.

By not including the logger I made it very flexible for users of the system to choose themselves which logger to use.

So yes, your understanding is correct.
