### ISSUE TITLE
Test run findings

### ISSUE THREAD

**Issue by MrNghia123** [nielsbasjes/yauaa#42]
Hi,
It is a great job you have done so far.
I am working on a project which involve in about a million clicks everyday.
After test run your parser with about 600k useragent in my database, I found some interesting findings:
-  It took my Macbook pro late 2013, 16GB RAM ~ 60 seconds to finish 600k UA strings. Welldone!
- The following UAs give "Hacker" in the fields:
MAUI WAP Browser
Mozilla/5.0 (Linux; Android 6.1; Honor Note 8 Build/MXC89L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36
Dorado WAP-Browser

I attach here the parse results in case you want to look into it. Basically the results were logged by the following code:
 
		for (String ua: uArrayList) {
			   UserAgent agent = uaa.parse(ua);  
			   AgentField deviceClass = agent.get("DeviceClass");
			   AgentField deviceName = agent.get("DeviceName");
			   AgentField operatingSystemClass =  agent.get("OperatingSystemClass");
			   AgentField operatingSystemName = agent.get("OperatingSystemName");
			   AgentField operatingSystemVersion = agent.get("OperatingSystemVersion");
			   AgentField layoutEngineClass = agent.get("LayoutEngineClass");
			   logger.info("{}|{}|{}|{}|{}|{}|{}", deviceClass.getValue(), deviceName.getValue(),
					   operatingSystemClass.getValue(), operatingSystemName.getValue(),
					   operatingSystemVersion.getValue(), layoutEngineClass.getValue(),
					   ua);

		}

[myLogFile.log.gz](https://github.com/nielsbasjes/yauaa/files/1106253/myLogFile.log.gz)

Since I am sitting on a lot of user agents, just let me know if you want to look into them.
Regards,

**Comment by nielsbasjes** [comment]
Thanks for the input. I'll have a look at it.
The three that are classified as "Hacker"
The first and last are just 'text' without anything. Because I want the number of lookups to be as limited as possible these are classified as "Hacker" because they do not follow any of the requirements in the RFCs.
The second one is a bug on my end. The "Honor Note" matches the SQL fragment "OR NOT" ... I already fixed this.

**Comment by nielsbasjes** [comment]
The "Honor Note 8" effect has been fixed in release 1.4
Thanks for the set of test useragents.
