### ISSUE TITLE
Bug when loadingDefaultResources is true for UserAgents yaml files at findAllResources method ?

### ISSUE THREAD

**Issue by Chaho12** [nielsbasjes/yauaa#458]
**Describe the bug**

Is this a bug when loadingDefaultResources is true for UserAgents yaml files at findAllResources [method](https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/java/nl/basjes/parse/useragent/config/ConfigLoader.java#L280-L309) ?

`getResources` returns empty array of resources. 
![image](https://user-images.githubusercontent.com/25147023/155671434-872e556f-cace-49a7-b6a8-6fdd7f270351.png)

```
String resourceString: "classpath*:UserAgents/**/*.yaml", 
boolean showLoadMessages: false
boolean areOptional: false
boolean loadingDefaultResources: true
```

When we call `PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();`,  [object with no parameters sent](https://github.com/spring-projects/spring-framework/blob/v5.3.15/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L214-L216), it would load with `DefaultResourceLoader`, so resolver's classLoader will be null as shown in image below (debug mode image shown below)
![image](https://user-images.githubusercontent.com/25147023/155668011-c11805e4-05f2-4b91-94fa-07d14b3128a9.png)

This is not a problem normally, but when we use Yauaa by using [different plugin SPI](https://trino.io/docs/current/develop/spi-overview.html), files are loaded into different class loader than default one.

If it is a bug, then I would suggest that it should pass current class's classLoader when creating object as below, so that it knows which class loader to use.
As you can see below, Yauaa is loaded at different plugin SPI, it is part of PluginClassLoader
![image](https://user-images.githubusercontent.com/25147023/155669540-85fb65a8-badf-41e8-80b4-daf299943859.png)

Therefore, I suggest that code should be fixed as following:
```java
PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver(this.getClass().getClassLoader());
```
![image](https://user-images.githubusercontent.com/25147023/155669461-e93c1ec8-f89f-4c87-815d-fa8752718a2e.png)

**Component where the bug happens**
[x] Core analyzer
[ ] UDF : Flink/Beam/Nifi/...
[ ] Other

**To Reproduce**
Steps or code fragment to reproduce the behavior:
1. Create a custom function that uses Yauaa with plugin SPI at Trino 

```java
package com.abc.def.trino.udfs.scalar;

import com.abc.def.trino.udfs.util.UDFUtils;
import io.airlift.slice.Slice;
import io.airlift.slice.Slices;
import io.trino.spi.block.Block;
import io.trino.spi.block.BlockBuilder;
import io.trino.spi.function.Description;
import io.trino.spi.function.ScalarFunction;
import io.trino.spi.function.SqlType;
import io.trino.spi.type.StandardTypes;
import nl.basjes.parse.useragent.UserAgent;
import nl.basjes.parse.useragent.UserAgentAnalyzer;

import java.util.List;

import static io.trino.spi.type.VarcharType.VARCHAR;

public class UDFParseAgent {

    private static volatile List<String> PREDEFINED_FIELD_NAMES;

    // error occurs here when creating `UserAgentAnalyzer` object
    private static final ThreadLocal<UserAgentAnalyzer> userAgentAnalyzerThreadLocal =
        ThreadLocal.withInitial(() -> UserAgentAnalyzer
                .newBuilder()
                .hideMatcherLoadStats()
                .withCache(10000)
                .build());

    private static List<String> getPredefinedFileNames() {
        List<String> predefined = PREDEFINED_FIELD_NAMES;
        if (predefined == null) {
            predefined = userAgentAnalyzerThreadLocal.get().getAllPossibleFieldNamesSorted();
            PREDEFINED_FIELD_NAMES = predefined;
        }
        return predefined;
    }

    @ScalarFunction(value="parse_agent")
    @SqlType("array(varchar)")
    public static Block parseAgent(@SqlType(StandardTypes.VARCHAR) Slice userAgentString) throws IllegalArgumentException {
        if (userAgentString == null || userAgentString.length() == 0) return UDFUtils.EMPTY_VARCHAR_ARRAY_BLOCK;

        List<String> predefinedFieldNames = getPredefinedFileNames();

        UserAgent userAgent = userAgentAnalyzerThreadLocal.get().parse(userAgentString.toStringUtf8());

        BlockBuilder blockBuilder = VARCHAR.createBlockBuilder(null, predefinedFieldNames.size());

        predefinedFieldNames.forEach(name -> {
            String value = userAgent.getValue(name);
            if (value == null) {
                VARCHAR.writeSlice(blockBuilder, Slices.EMPTY_SLICE);
            } else {
                VARCHAR.writeString(blockBuilder, value);
            }
        });

        return blockBuilder.build();
    }
}

```

2. Place the custom function jar to appropriate plugin location at Trino server
3. Run sql using the custom user defined function

**Expected behavior**

UserAgentAnalyzer object should be created with resources loaded (`yaml files`).

**Screenshots**

Fails to load config files.
![image](https://user-images.githubusercontent.com/25147023/155670514-ffc003a7-ec0a-491f-b645-c4b46a8ff8e3.png)

**Additional context**

**Comment by nielsbasjes** [comment]
You were completely correct in your analysis and the solution you proposed.
I have fix this now.

In addition I had a look at the Trino documentation and I have created a Trino function that you should be able to use in a much easier way.

I have created some documentation for this https://yauaa.basjes.nl/udf/trino/ and I have first snapshot version of this plugin available:

https://oss.sonatype.org/content/repositories/snapshots/nl/basjes/parse/useragent/yauaa-trino/6.10-SNAPSHOT/yauaa-trino-6.10-20220226.174914-1-udf.jar

I would really appreciate it if you can test this for me.

**Comment by Chaho12** [comment]
@nielsbasjes Thx for quick reply & fix.
As you wrote on the document, I added snapshot and tested as following (masked some personal info):
![스크린샷 2022-02-28 오전 9 49 56](https://user-images.githubusercontent.com/25147023/155908396-4b85657e-646c-41cb-86c4-04d4df047d4c.png)
![스크린샷 2022-02-28 오전 10 00 33](https://user-images.githubusercontent.com/25147023/155908405-ab6be399-c427-403e-abba-64dbc45d2779.png)

Seems to work well :) Please tell me when you release 6.10 with changes applied.

**Comment by nielsbasjes** [comment]
Cool!
I have made a few more improvements (for one: Using ThreadLocal will make it use a huge amount of memory that is never cleaned, now only 1 instance).
I'm making a release for v6.10 right now.
