### ISSUE TITLE
hive udf make hive server 2000% CPU useage

### ISSUE THREAD

**Issue by jiangzhx** [nielsbasjes/yauaa#46]
hive logs:
2017-07-19T06:09:02,492 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResources(334)) - Building 2033 (dropped  231) matchers from   52 files took  3880 msec resulted in   180308 hashmap entries
2017-07-19T06:09:02,492 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResources(337)) - Analyzer stats
2017-07-19T06:09:02,493 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResources(338)) - Lookups      : 24
2017-07-19T06:09:02,493 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResources(339)) - Matchers     : 2033 (total:2033 ; dropped: 231)
2017-07-19T06:09:02,493 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResources(340)) - Hashmap size : 180308
2017-07-19T06:09:02,493 INFO  [b558b99d-de0b-477e-ba8d-1362ba049269 HiveServer2-Handler-Pool: Thread-1209506([])]: useragent.UserAgentAnalyzer (UserAgentAnalyzer.java:loadResource

and make JVM 
2017-07-19T06:09:17,286 INFO  [org.apache.hadoop.hive.common.JvmPauseMonitor$Monitor@58015e56([])]: common.JvmPauseMonitor (JvmPauseMonitor.java:run(194)) - Detected pause in JVM or host machine (eg GC): pause of approximately 1263ms

**Comment by jiangzhx** [comment]
i find a reason.
my etl engine will add jar  many times.
`add jar /usr/lib/hive/udfs/hive-jar-with-dependencies.jar;    `
`CREATE TEMPORARY FUNCTION uaparser AS 'com.reyun.hive.udf.UAParser2';`
it's make load resource many times.

so i write a Singleton mode class like this.
```

public class UserAgentAnalyzerUtils
{
    private static UserAgentAnalyzer userAgentAnalyzer;

    public static UserAgentAnalyzer getInstance()
    {
        if (userAgentAnalyzer==null){
            userAgentAnalyzer=UserAgentAnalyzer
                    .newBuilder()
                    .withField("DeviceBrand")
                    .withField("OperatingSystemName")
                    .withField("OperatingSystemVersion")
                    .build();;
        }
        return userAgentAnalyzer;
    }
}

```

then , i can use it by 
`UserAgentAnalyzerUtils.getInstance().parse("ua"); 
`

**Comment by nielsbasjes** [comment]
Thanks for reporting this.
Can you please give me as much information as possible on this issue.
So far I have not seen this effect (yet).

**Comment by nielsbasjes** [comment]
Oh wait. I think I see the problem here.
You have included the parser in your own UDF for Hive.
Last week I wrote a separate UDF.

**Comment by jiangzhx** [comment]
i think should use Singleton class to new UserAgentAnalyzer.
becase many production enviroment . will add jar and  create function many times.
it's will make hive server jvm gc.

when i use UserAgentAnalyzerUtils class. everything work fine.

**Comment by nielsbasjes** [comment]
Good to hear the problem has been fixed.
Success with your project!

**Comment by mdbyambaa** [comment]
Thank you @nielsbasjes for your great library,

i was use it with Fast Object Pool library like below, and i haven't problem.

package mdb.CMN.System.Utilities.UA;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.DependsOn;
import javax.ejb.Singleton;
import javax.ejb.Startup;

import cn.danielw.fop.ObjectFactory;
import cn.danielw.fop.ObjectPool;
import cn.danielw.fop.PoolConfig;
import mdb.CMN.Base.Constants.CMNBaseConstants.CMN.SETTING;
import mdb.CMN.System.Configure.CMNSystemConfigure;
import mdb.CMN.System.Constants.CMNSystemConstants;
import mdb.CMN.Utilities.Log.CMNLogUtilities;
import nl.basjes.parse.useragent.UserAgentAnalyzer;

/**
*

@author Byambasuren.MD
*/

@startup
@DependsOn("CMNSystemConfigure")
@singleton(name = "CMNSystemUAUtilities", mappedName = "CMNSystemUAUtilities")
public class CMNSystemUAUtilities implements CMNSystemConstants {

private static CMNSystemUAUtilities INSTANCE;

private static UserAgentAnalyzer ANALYZER;

private static ObjectFactory<UserAgentAnalyzer> ANALYZER_POOL_FACTORY;

private static ObjectPool<UserAgentAnalyzer> ANALYZER_POOL;

/** Instances **/

public static CMNSystemUAUtilities getInstance() {
	return INSTANCE != null ? INSTANCE : (INSTANCE = new CMNSystemUAUtilities());
}

/** Listener **/

@PostConstruct
public void init() {
	CMNSystemUAUtilities.INSTANCE = this;
	CMNSystemUAUtilities.ANALYZER = UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(5000).build();

	CMNSystemUAUtilities.ANALYZER_POOL_FACTORY = new ObjectFactory<UserAgentAnalyzer>() {
		public UserAgentAnalyzer create() {
			return UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(1000).build();
		}

		public void destroy(UserAgentAnalyzer o) {

		}

		public boolean validate(UserAgentAnalyzer o) {
			return true;
		}
	};

	CMNSystemUAUtilities.ANALYZER_POOL = new ObjectPool(new PoolConfig().setPartitionSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_PARTITION_SIZE).getValueASInteger()).setMaxSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_MAX_SIZE).getValueASInteger()).setMinSize(CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_MIN_SIZE).getValueASInteger()).setMaxIdleMilliseconds(60 * 1000 * CMNSystemConfigure.getInstance().getSetting(SYSTEM.SETTING.UA.UA_POOL_IDLE_TIME).getValueASInteger()), ANALYZER_POOL_FACTORY);
}

@PreDestroy
public void destroy() {
	try {
		CMNSystemUAUtilities.ANALYZER_POOL.shutdown();
	} catch (Exception ex) {
		CMNLogUtilities.error(CMNSystemConfigure.getInstance().getSetting(SETTING.LOG.SYSTEM).getValue(), "[UA.Utilities][Error on shutDown UA.Analyzer.Pool]");
	}
	CMNLogUtilities.info(CMNSystemConfigure.getInstance().getSetting(SETTING.LOG.SYSTEM).getValue(), "[UA.Utilities]");
}

/** Getter **/

public UserAgentAnalyzer getAnalyzer() {
	return ANALYZER != null ? ANALYZER : (ANALYZER = UserAgentAnalyzer.newBuilder().hideMatcherLoadStats().withCache(5000).build());
}

public UserAgentAnalyzer getAnalyzerPool() {
	return CMNSystemUAUtilities.ANALYZER_POOL.borrowObject().getObject();
}

**Comment by nielsbasjes** [comment]
Hi,
Thanks for the complement.
Please stop posting the same code over and over again.
Niels
