### ISSUE TITLE
Trino UDF incorrect parsing

### ISSUE THREAD

**Issue by Chaho12** [nielsbasjes/yauaa#476]
**The exact useragent**
useragent: v6.10 

**Expected/Incorrect fields**
agentname: 'Internet Explorer'

**Expected behavior**
Agent Name should be `Internet Explorer` and not when I run UDF downloaded from source (https://yauaa.basjes.nl/udf/trino/)
`SELECT parse_user_agent( 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; 22222ads; rv:11.0) like Gecko' );`
- string above is Internet Explorer 11 (IE 11) User Agent info
![image](https://user-images.githubusercontent.com/25147023/156955477-590052f2-c51e-48fc-9b08-689b49cd7428.png)

If I remove the `22222ads`, which I know that is abnormal string, I get correct AgentName field as shown below.
![image](https://user-images.githubusercontent.com/25147023/156955841-e96dab5f-33f1-4ac8-a5ce-95a56e8daafb.png)

**Additional information**
This is custom Hive UDF that we creating for Yauaa v5.15, which shows no problem handling abnormal strings.
![image](https://user-images.githubusercontent.com/25147023/156955874-bf82270d-7222-4d98-8a86-405358061b59.png)

**Comment by nielsbasjes** [comment]
Fixed
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/MSInternetExplorer.yaml#L1631

**Comment by Chaho12** [comment]
@nielsbasjes 
Umm, `22222ads` is just random string that i came up with to mask real string. (which is used internally in our system)
I was wondering more about why in previous version there was no problem showing as `Internet Explorer` in v5.15, but there's an issue with recent version?

**Comment by nielsbasjes** [comment]
The reason is simple: I get more and more examples over time and thus I update the rules to match all cases I actually have. So between 5.15 and now I have changed a lot of things.

I understand the `22222ads` was anonymized. What is important to me is the pattern of the real thing. If this was also a `[a-zA-Z0-9]+` with at least 1 digit then I expect it to work.
If there are also additional spaces of '/' in there then it really changes everything.

**Comment by nielsbasjes** [comment]
I have published a snapshot for you to try out on your real data: https://oss.sonatype.org/content/repositories/snapshots/nl/basjes/parse/useragent/yauaa-trino/6.11-SNAPSHOT/yauaa-trino-6.11-20220307.093549-1-udf.jar

**Comment by Chaho12** [comment]
Thx for explanation. It works well ! 
![스크린샷 2022-03-07 오후 7 08 54](https://user-images.githubusercontent.com/25147023/157012510-6e4b165a-9e6e-48f6-a0a6-8d6548986dbf.png)
This is the real case, which is alphabets + underscore, but it seems to work well ! 
![image](https://user-images.githubusercontent.com/25147023/157012439-d74622bc-55a3-4894-8a05-041f513c4266.png)

**Comment by nielsbasjes** [comment]
Thanks for checking.

**Comment by nielsbasjes** [comment]
I released 6.11 just now which includes this fix.
