### ISSUE TITLE
Logging in spring boot for every http request

### ISSUE THREAD

**Issue by david-thrymr** [nielsbasjes/yauaa#48]
please provide a configuration to disable printing banner

Yauaa 1.4 (v1.4 @ 2017-07-07T20:35:47Z)                    |
Yauaa 1.4 (v1.4 @ 2017-07-07T20:35:47Z)                    |
---------------------------------------------------------+
---------------------------------------------------------+
finding it diffcult to use this jar cause it reduces the performance of the application.

**Comment by nielsbasjes** [comment]
Starting the analyzer usually takes between 2 and 5 seconds (depending on available CPU speed).
During this step the banner is printed (takes about 1ms). Not printing the banner does not solve your performance problem.

I suspect that you are instantiating the analyser too often.
Have a look at the Hive udf I wrote where I create an instance that lives for a very long time.

**Comment by david-thrymr** [comment]
Sir I'm not understanding how to use hive udf. For every http request from client I need to capture his browser, device and os info I implemented  code  from your api to separately  capture os device info and browser info in 3 different methods instantiating 
	final UserAgent agent = uaa1.parse(request.getHeader("User-Agent"));
in all methods so please give me idea how to @Autowire this class in the service and use in all methods 
I need any solution if possible please I'm using spring boot to write services classes.

**Comment by nielsbasjes** [comment]
So far I have never done anything with spring-boot so I don't know what the 'right' way of doing things there. In normal java you would simply instantiate the analyzer using the singleton pattern and then call that one from the rest of your code. The Hive UDF is an example that does this.

Since this is neither a bug nor a sensible change in my code I'm closing this.

**Comment by anuj09garg** [comment]
Hi,
Can I autowire this class so that it doesn't load every time I call it and avoid it from taking 2-5 secs.

**Comment by anuj09garg** [comment]
@nielsbasjes Please help with the above query.

**Comment by nielsbasjes** [comment]
You should only start it once and the fire many requests at it. I do not know what "autowire" means to answer your question.
