### ISSUE TITLE
new version with caffeine 3.0.5 not compatible with jdk8

### ISSUE THREAD

**Issue by kaktos** [nielsbasjes/yauaa#485]
**Describe the bug**
with the new version 6.11 depends on caffeine 3.x, needs jdk11

**Component where the bug happens**
[√] Core analyzer
[ ] UDF : Flink/Beam/Nifi/...
[ ] Other

**To Reproduce**
just run under jdk8

**Comment by nielsbasjes** [comment]
Yes that is correct.
In the release notes I have indicated how you can handle this
https://yauaa.basjes.nl/#version-68

Just now I have added a check to ensure this actually works
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/UsedInJava8Project/src/main/java/nl/example/Demo.java#L37

Please confirm if this also works in your context.

**Comment by kaktos** [comment]
> Yes that is correct. In the release notes I have indicated how you can handle this https://yauaa.basjes.nl/#version-68
> 
> Just now I have added a check to ensure this actually works https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/UsedInJava8Project/src/main/java/nl/example/Demo.java#L37
> 
> Please confirm if this also works in your context.

thx, checks ok.

**Comment by yeshbash** [comment]
> Yes that is correct. In the release notes I have indicated how you can handle this https://yauaa.basjes.nl/#version-68
> 
> Just now I have added a check to ensure this actually works https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/UsedInJava8Project/src/main/java/nl/example/Demo.java#L37
> 
> Please confirm if this also works in your context.

I'm facing the same issue and both the links shared in this reply appear to be broken. Can you share the correct links.
I also checked [CHANGELOG](https://github.com/nielsbasjes/yauaa/blob/main/CHANGELOG.md#v68) for any leads in release 6.8 but couldn't find any. Thanks!

**Comment by nielsbasjes** [comment]
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/it/JavaPlain/Java8/src/main/java/nl/example/Demo.java#L36

**Comment by nielsbasjes** [comment]
Also this link may be of use to you
https://yauaa.basjes.nl/using/#running-on-java-8

**Comment by hertg** [comment]
I have the same issue, I am unable to even fetch the library from maven via gradle in a JDK8 project, so I can't get it to build. Some snippets from my `build.gradle`

```gradle
plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
}

...

java {
    toolchain {
        sourceCompatibility = 1.8
        withSourcesJar()
        withJavadocJar()
    }
}

repositories {
    mavenCentral()
}

dependencies {
    ...
    implementation group: 'nl.basjes.parse.useragent', name: 'yauaa', version: '7.19.2'
}
```

*Build Output*
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.ben-manes.caffeine:caffeine:3.1.6.
     Required by:
         project : > nl.basjes.parse.useragent:yauaa:7.19.2
      > No matching variant of com.github.ben-manes.caffeine:caffeine:3.1.6 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.github.ben-manes.caffeine:caffeine:3.1.6 declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability com.github.ben-manes.caffeine:caffeine:3.1.6 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.github.ben-manes.caffeine:caffeine:3.1.6 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability com.github.ben-manes.caffeine:caffeine:3.1.6 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

---

Btw. the links above are dead, maybe try using the `Copy Permalink` button in the future :)
![image](https://github.com/nielsbasjes/yauaa/assets/3533648/6dc48571-d6e4-4e44-bbc8-1c399cf98247)

**Comment by nielsbasjes** [comment]
Thanks!
I'm adding extra info to the documentation and I have started the process to setup the Github Sponsors.

**Comment by nielsbasjes** [comment]
https://yauaa.basjes.nl/using/#running-on-java-8

**Comment by nielsbasjes** [comment]
@hertg As you suggested I have setup the GitHub Sponsors system 
https://github.com/sponsors/nielsbasjes
