### ISSUE TITLE
Version "??" value is inconsistent with other "Unknown" values

### ISSUE THREAD

**Issue by bencody** [nielsbasjes/yauaa#49]
When parsing the user agent string "Apache-HttpClient/release (java 1.5)", the UserAgentAnalyzer "OperatingSystemVersion" field gets resolved to the string "??". Most other fields seem get resolved to "Unknown" if there's no reliable value.

For the sake of consistency, I recommend resolving an unknown "OperatingSystemVersion" value to "Unknown" instead of "??".

**Comment by nielsbasjes** [comment]
Hi @bencody .
The 'default' values I have chosen to use is "??" for 'version' fields and  "Unknown" for all others.
This makes the results "Look" better ... atleast that is what I think.
I understand your point also. I'll think about it for the upcomming 2.0 release (uses java 8)
Niels
