### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by fangpeng-lingoace** [nielsbasjes/yauaa#527]
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Apple Macintosh'
      DeviceBrand  : 'Apple'
      DeviceCpu  : 'Intel'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS X'
      OperatingSystemVersion  : '??'
      OperatingSystemVersionMajor  : '??'
      OperatingSystemNameVersion  : 'Mac OS X ??'
      OperatingSystemNameVersionMajor  : 'Mac OS X ??'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '99.0'
      LayoutEngineVersionMajor  : '99'
      LayoutEngineNameVersion  : 'Blink 99.0'
      LayoutEngineNameVersionMajor  : 'Blink 99'
      AgentClass  : 'Browser'
      AgentName  : 'Chrome'
      AgentVersion  : '99.0.4844.74'
      AgentVersionMajor  : '99'
      AgentNameVersion  : 'Chrome 99.0.4844.74'
      AgentNameVersionMajor  : 'Chrome 99'

```

**Comment by fangpeng-lingoace** [comment]
The os version should be 10.15.7.

**Comment by nielsbasjes** [comment]
No, that it not a bug. This is actually the right answer.
https://yauaa.basjes.nl/expect/manipulations/#there-is-no-macos-11

**Comment by nielsbasjes** [comment]
@fangpeng-lingoace 
Just so you know. The next release of Yauaa supports also analyzing the UserAgent Client Hints (if available). If you have those you CAN get the correct version:

    - test:
        name: 'Chrome 100 on MacOS 12.3.1 (Full Client Hints)'
        input:
          User-Agent                                 :  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'
          Sec-CH-UA                                  :  '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"'
          Sec-CH-UA-Platform                         :  '"macOS"'
          Sec-CH-UA-Platform-Version                 :  '"12.3.1"'
        expected:
          OperatingSystemClass                       : 'Desktop'
          OperatingSystemName                        : 'Mac OS'
          OperatingSystemVersion                     : '12.3.1'
