### ISSUE TITLE
Some device are detected as Mobile instead Phone

### ISSUE THREAD

**Issue by ncoquelet** [nielsbasjes/yauaa#54]
I here an agent which is detected as Mobile instead Phone

mozilla/5.0 (linux; android 6.0.1; sm-g920f build/mmb29k) applewebkit/537.36 (khtml, like gecko) chrome/48.0.2564.95 mobile

Device	
Class	Mobile
Name	Samsung SM-G920F
Brand	Samsung
Operating System	
Class	Mobile
Name	Android
Version	6.0.1
Name Version	Android 6.0.1
Version Build	mmb29k
Layout Engine	
Class	Browser
Name	Blink
Version	48.0
Version Major	48
Name Version	Blink 48.0
Name Version Major	Blink 48
Agent	
Class	Browser
Name	Chrome
Version	48.0.2564.95
Version Major	48
Name Version	Chrome 48.0.2564.95
Name Version Major	Chrome 48

**Comment by nielsbasjes** [comment]
First observation:
The example you provide here looks like a chopped version of what I see in my logs quite often:

    mozilla/5.0 (linux; android 6.0.1; sm-g920f build/mmb29k) applewebkit/537.36 (khtml, like gecko) chrome/48.0.2564.95 mobile
    Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2456.0 Mobile Safari/537.36

**Comment by nielsbasjes** [comment]
Fixed

**Comment by ncoquelet** [comment]
thank you
