### ISSUE TITLE
include if the OS is 16,32 or 64 bit

### ISSUE THREAD

**Issue by frko** [nielsbasjes/yauaa#55]
We've got a usecase where we want to expose the optimal download of a binary to our customers. It would be greatly appreciated if this information could be added to the DeviceProfile so we can utilize this knowledge to improve the customer experience.

**Comment by nielsbasjes** [comment]
Background info: https://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript

**Comment by nielsbasjes** [comment]
I just wrote the first draft version. 
Please try.

**Comment by nielsbasjes** [comment]
Fixed an part of version 2.1 which I just released.
