### ISSUE TITLE
Test the Snowflake UDF 7.0.0

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#560]
I have added support for (in addition to the normal User-Agents) analyzing the User-Agent in conjunction with the User-Agent Client Hints 

I have tried to follow the Snowflake [documentation](https://docs.snowflake.com/en/developer-guide/udf/java/udf-java-designing.html#passing-via-varargs) on this.

Yet as I do not have access to Snowflake (or a Snowflake provided testing framework) I'm unable to do any checks if it actually works in the system itself.

@lambrosetti I would really appreciate it if you can test if the current implementation works.

I have created a SNAPSHOT build for you to test: 

https://oss.sonatype.org/content/repositories/snapshots/nl/basjes/parse/useragent/yauaa-snowflake/7.0.0-SNAPSHOT/yauaa-snowflake-7.0.0-20220506.153943-2-udf.jar

With version 7.0.0 you are now able to do this aswell

```sql
select parse_useragent(
    'User-Agent',                   'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
    'Sec-Ch-Ua',                    '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"',
    'Sec-Ch-Ua-Arch',               '\"x86\"',
    'Sec-Ch-Ua-Bitness',            '\"64\"',
    'Sec-Ch-Ua-Full-Version',       '\"100.0.4896.127\"',
    'Sec-Ch-Ua-Full-Version-List',  '\" Not A;Brand\";v=\"99.0.0.0\", \"Chromium\";v=\"100.0.4896.127\", \"Google Chrome\";v=\"100.0.4896.127\"',
    'Sec-Ch-Ua-Mobile',             '?0',
    'Sec-Ch-Ua-Model',              '\"\"',
    'Sec-Ch-Ua-Platform',           '\"Linux\"',
    'Sec-Ch-Ua-Platform-Version',   '\"5.13.0\"',
    'Sec-Ch-Ua-Wow64',              '?0'
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;
```

When only examining the `User-Agent` this returns `Linux ??`, with the added information in the Client Hints you should get `Linux 5.13.0` instead.

The old form should also still work
```sql
select parse_useragent(
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;
```

and this should also work (first one is the UserAgent without the header name).

```sql
select parse_useragent(
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
    'Sec-Ch-Ua',                    '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"',
    'Sec-Ch-Ua-Arch',               '\"x86\"',
    'Sec-Ch-Ua-Bitness',            '\"64\"',
    'Sec-Ch-Ua-Full-Version',       '\"100.0.4896.127\"',
    'Sec-Ch-Ua-Full-Version-List',  '\" Not A;Brand\";v=\"99.0.0.0\", \"Chromium\";v=\"100.0.4896.127\", \"Google Chrome\";v=\"100.0.4896.127\"',
    'Sec-Ch-Ua-Mobile',             '?0',
    'Sec-Ch-Ua-Model',              '\"\"',
    'Sec-Ch-Ua-Platform',           '\"Linux\"',
    'Sec-Ch-Ua-Platform-Version',   '\"5.13.0\"',
    'Sec-Ch-Ua-Wow64',              '?0'
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;
```

**Comment by lambrosetti** [comment]
Hey Niels - I will look into this over the weekend and will get back to you!

**Comment by lambrosetti** [comment]
Ended up getting some extra time today!

With this new method, I had to alter the Java UDF in Snowflake to be an ARRAY instead of VARCHAR as Snowflake UDFs can't do varargs. See the new create statement:

```
create or replace function luke_dev.parse_useragent(useragent ARRAY)
returns object
language java
imports = ('@cs_stage/yauaa-snowflake-7.0.0-20220506.153943-2-udf.jar')
handler='nl.basjes.parse.useragent.snowflake.ParseUserAgent.parse';
```

Because this is now an array, I added [] to the new SELECTS to properly call the function. The old method still works for Snowflake, I'm guessing its because it knows that a single string is just a one-item array:

```

-- old method
select luke_dev.parse_useragent(
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;

-- new
select luke_dev.parse_useragent(
    ['User-Agent',                   'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
    'Sec-Ch-Ua',                    '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"',
    'Sec-Ch-Ua-Arch',               '\"x86\"',
    'Sec-Ch-Ua-Bitness',            '\"64\"',
    'Sec-Ch-Ua-Full-Version',       '\"100.0.4896.127\"',
    'Sec-Ch-Ua-Full-Version-List',  '\" Not A;Brand\";v=\"99.0.0.0\", \"Chromium\";v=\"100.0.4896.127\", \"Google Chrome\";v=\"100.0.4896.127\"',
    'Sec-Ch-Ua-Mobile',             '?0',
    'Sec-Ch-Ua-Model',              '\"\"',
    'Sec-Ch-Ua-Platform',           '\"Linux\"',
    'Sec-Ch-Ua-Platform-Version',   '\"5.13.0\"',
    'Sec-Ch-Ua-Wow64',              '?0']
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;

-- new
select luke_dev.parse_useragent(
    ['Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
    'Sec-Ch-Ua',                    '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"',
    'Sec-Ch-Ua-Arch',               '\"x86\"',
    'Sec-Ch-Ua-Bitness',            '\"64\"',
    'Sec-Ch-Ua-Full-Version',       '\"100.0.4896.127\"',
    'Sec-Ch-Ua-Full-Version-List',  '\" Not A;Brand\";v=\"99.0.0.0\", \"Chromium\";v=\"100.0.4896.127\", \"Google Chrome\";v=\"100.0.4896.127\"',
    'Sec-Ch-Ua-Mobile',             '?0',
    'Sec-Ch-Ua-Model',              '\"\"',
    'Sec-Ch-Ua-Platform',           '\"Linux\"',
    'Sec-Ch-Ua-Platform-Version',   '\"5.13.0\"',
    'Sec-Ch-Ua-Wow64',              '?0']
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;
```

Please let me know if there are further questions here! This weekend I'll take some time to rerun some of my performance testing.

**Comment by nielsbasjes** [comment]
Thank you for helping out so quick!
So as I understand it actually works and I only need to update the documentation?

Reading back the documentation on the UDFs with varargs https://docs.snowflake.com/en/developer-guide/udf/java/udf-java-designing.html#passing-via-varargs I now also see the `ARRAY` in the definition.
Given that they call it "varargs" in the documentation and the 'single value' still works the same; I would have expected it to also work without the `[` `]` for the list of arguments. I would appreciate a double check on this.

**Comment by nielsbasjes** [comment]
Also: A screenshot of what this example looks like in the system and what the output looks like would be nice to put in the documentation.

**Comment by lambrosetti** [comment]
Oh sorry, I completely missed the varargs documentation, but it effectively confirmed what I was seeing when initially testing. In that documentation, it's calling array_construct() to build the example dataset, so instead of being multiple arguments of strings, it's a single array of strings being passed. Calling array_construct() or using `[` `]` is effectively the same thing in this case.

Here is the error if you don't have the input as an array (or single string value):
```
SQL compilation error: error line 1 at position 7 too many arguments for function [PARSE_USERAGENT('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36', 'Sec-Ch-Ua', '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"', 'Sec-Ch-Ua-Arch', '"x86"', 'Sec-Ch-Ua-Bitness', '"64"', 'Sec-Ch-Ua-Full-Version', '"100.0.4896.127"', 'Sec-Ch-Ua-Full-Version-List', '" Not A;Brand";v="99.0.0.0", "Chromium";v="100.0.4896.127", "Google Chrome";v="100.0.4896.127"', 'Sec-Ch-Ua-Mobile', '?0', 'Sec-Ch-Ua-Model', '""', 'Sec-Ch-Ua-Platform', '"Linux"', 'Sec-Ch-Ua-Platform-Version', '"5.13.0"', 'Sec-Ch-Ua-Wow64', '?0')] expected 1, got 22
```

Attached are the screenshots that should help. I included an example using `[` `]` and array_construct(). Here is the SQL using array_construct():

```
-- new
select luke_dev.parse_useragent(
    array_construct('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
    'Sec-Ch-Ua',                    '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"',
    'Sec-Ch-Ua-Arch',               '\"x86\"',
    'Sec-Ch-Ua-Bitness',            '\"64\"',
    'Sec-Ch-Ua-Full-Version',       '\"100.0.4896.127\"',
    'Sec-Ch-Ua-Full-Version-List',  '\" Not A;Brand\";v=\"99.0.0.0\", \"Chromium\";v=\"100.0.4896.127\", \"Google Chrome\";v=\"100.0.4896.127\"',
    'Sec-Ch-Ua-Mobile',             '?0',
    'Sec-Ch-Ua-Model',              '\"\"',
    'Sec-Ch-Ua-Platform',           '\"Linux\"',
    'Sec-Ch-Ua-Platform-Version',   '\"5.13.0\"',
    'Sec-Ch-Ua-Wow64',              '?0')
) as ua_obj, ua_obj:OperatingSystemNameVersion::string as operating_system_name_version;
```

Thanks again for the work here - let me know if there's anything else to test!

<img width="1529" alt="Screen Shot 2022-05-11 at 5 17 47 PM" src="https://user-images.githubusercontent.com/92615308/167949706-126a529e-b435-44a2-ae1d-5f420f94b1f8.png">
<img width="1449" alt="Screen Shot 2022-05-11 at 5 17 15 PM" src="https://user-images.githubusercontent.com/92615308/167949707-331cb377-e8ca-497d-8e33-716429619b4c.png">
<img width="1391" alt="Screen Shot 2022-05-11 at 5 16 36 PM" src="https://user-images.githubusercontent.com/92615308/167949708-97f97275-2d2f-4c86-bcf5-4ff0abbcf211.png">

**Comment by nielsbasjes** [comment]
I have included all of this in the documentation.
Thanks!
