### ISSUE TITLE
Darwin

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#570]
I think that it would be more user friendly to make the conversion from Darwin to the different name and version of the Apple OSes.
There is a handy conversion chart here: https://en.wikipedia.org/wiki/Darwin_(operating_system) 

```

- test:
    input:
      User-Agent  : 'GiFi/415 CFNetwork/1331.0.7 Darwin/21.4.0'
    expected:
      DeviceClass  : 'Mobile'
      DeviceName  : 'Apple iOS Device'
      DeviceBrand  : 'Apple'
      OperatingSystemClass  : 'Mobile'
      OperatingSystemName  : 'iOS'
      OperatingSystemVersion  : '15.4.0'
      OperatingSystemVersionMajor  : '15'
      OperatingSystemNameVersion  : 'iOS 15.4.0'
      OperatingSystemNameVersionMajor  : 'iOS 15'
      LayoutEngineClass  : 'Mobile App'
      LayoutEngineName  : 'GiFi'
      LayoutEngineVersion  : '415'
      LayoutEngineVersionMajor  : '415'
      LayoutEngineNameVersion  : 'GiFi 415'
      LayoutEngineNameVersionMajor  : 'GiFi 415'
      AgentClass  : 'Mobile App'
      AgentName  : 'GiFi'
      AgentVersion  : '415'
      AgentVersionMajor  : '415'
      AgentNameVersion  : 'GiFi 415'
      AgentNameVersionMajor  : 'GiFi 415'

```

**Comment by nielsbasjes** [comment]
Yes, such a mapping is technically possible.

My main problem is the speed at which these things change.
It would require sometimes even weekly releases just to keep up... assuming this wikipedia page has been updated.
This is faster than I want to support.

I'm thinking about providing an example config that would do this and then leave it to the user of this system if they really want to take up this update process themselves.

**Comment by nielsbasjes** [comment]
Fixed as best as possible.
Your example works now.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Apps.yaml#L3548
