### ISSUE TITLE
Firefox Focus 1.3

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#58]
Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/1.3 Chrome/60.0.3112.116 Mobile Safari/537.36

**Comment by smm397** [comment]
I AM NOT subscribed to Github. My phone and PC have been hacked,  and your
site is being used via my info for illegal purposes. UNSUBSCRIBE me.  The
police are involved in this investigation,  which includes international
law enforcement as well. This is your only warning.  I will have Github's
server logs and you, the person,  added to my list. This is serious,  and
this is not a joke.
