### ISSUE TITLE
NPE for certain values of userAgent

### ISSUE THREAD

**Issue by bartoszwalacik** [nielsbasjes/yauaa#59]
The lib throws NPE (from antlr) for some userAgent values:

For example for this userAgent:
"      ltx71 - (http://ltx71.com/)"

Obviously, this userAgent is wrong (but it is a real value logged on our site on production).

I would expect "Hacker" (or "Malformed UA") result in this case.

**Comment by nielsbasjes** [comment]
Thank you !
I am able to reproduce this.

**Comment by nielsbasjes** [comment]
Fixed.
See https://github.com/nielsbasjes/yauaa/commit/5113c0d4890ce67dce4ac8bc2d60854924171a1c

**Comment by bartoszwalacik** [comment]
Thanks for the super fast bugfix :)
We are waiting for the release

**Comment by nielsbasjes** [comment]
Released. On its way to maven central now.
