### ISSUE TITLE
Possibility to define max length of user agent string to parse

### ISSUE THREAD

**Issue by pawel-piecyk** [nielsbasjes/yauaa#60]
It would be nice to have a possibility to define what is maximum length of parsed user agent. 
Now it is possible to provide very long user agent so parsing can take very long time. I've tested this on sample app (pasted sample user agent 500 times) and parsing took more than 1s - it seems that it's possible to DDOS a service with long user agents.

**Comment by nielsbasjes** [comment]
Sounds like a plan.
I did a quick check on 2 years of production logs and found that all useragents longer than 1000 chars are hack attempts. 
So you also think that would be a good cut of point?

**Comment by pawel-piecyk** [comment]
I think it would be okay to have this option in builder :) Please take look at my PR.

**Comment by nielsbasjes** [comment]
I'll have a look tonight. I myself was thinking about a simpler solution: 
   if >1000 chars then hacker trying bufferoverflow.

**Comment by pawel-piecyk** [comment]
Maybe analysing first X characters and then ignoring the remaining part is enough to identify user agent?

**Comment by nielsbasjes** [comment]
No, I did some more checks and beyond 2K I'm 100% sure it is a hacker.
This means that everything else you see is nonsense and there is no need to actually analyse that.
Have a look at what I just committed.

**Comment by pawel-piecyk** [comment]
Okay, but we use a bit lower value. Can I make this hardcoded value (2048 from your commit) configurable by builder like in my PR?

**Comment by nielsbasjes** [comment]
I merged your code and used my value as a default.

**Comment by pawel-piecyk** [comment]
Thanks!
