### ISSUE TITLE
OS Name Version Unknown ?? and Agent version not display minor

### ISSUE THREAD

**Issue by nampvdrunsystem** [nielsbasjes/yauaa#601]
**The exact useragent**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Expected/Incorrect fields**
OperatingSystemNameVersion: 'Windows 10.0'
AgentVersion: '102.0.0.0'

**Expected behavior**
I am using version 6.0 and cant get the expected Agent Version and OS Name

**Comment by nielsbasjes** [comment]
The documentation explains this and also that you need the client hints to fix this.
Basically Yauaa knows which versions are fake and doesn't give you the fake values.

https://yauaa.basjes.nl/expect/manipulations/#reducingfreezing-the-useragent

https://yauaa.basjes.nl/expect/manipulations/#there-is-no-windows-11-in-chromiumchromeedge

https://yauaa.basjes.nl/using/clienthints/

Also: the 6.0 version is a year old, please use the latest release of yauaa.

**Comment by nielsbasjes** [comment]
I have tried to explain this a bit further here:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs
