### ISSUE TITLE
Google SecurityScanner

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#611]
On Google Cloud Platform this product is called Cloud Web Security Scanner

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (X11; Linux x86_64; GoogleSecurityScanner Google-HTTP-Java-Client) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36 (scan 4592796119236608, run 5605990237962240) To_stop_this_scan_visit_https://console.cloud.google.com/security/web-scanner'
    expected:
      DeviceClass  : 'Robot'
      DeviceName  : ''
      DeviceBrand  : 'Google'
      OperatingSystemClass  : 'Cloud'
      OperatingSystemName  : 'Cloud'
      OperatingSystemVersion  : '??'
      OperatingSystemVersionMajor  : '??'
      OperatingSystemNameVersion  : 'Cloud ??'
      OperatingSystemNameVersionMajor  : 'Cloud ??'
      LayoutEngineClass  : 'Robot'
      LayoutEngineName  : 'Google-HTTP-Java-Client'
      LayoutEngineVersion  : '??'
      LayoutEngineVersionMajor  : '??'
      LayoutEngineNameVersion  : 'Google-HTTP-Java-Client ??'
      LayoutEngineNameVersionMajor  : 'Google-HTTP-Java-Client ??'
      AgentClass  : 'Robot'
      AgentName  : 'Cloud Web Security Scanner'
      AgentVersion  : '??'
      AgentVersionMajor  : '??'
      AgentNameVersion  : 'Cloud Web Security Scanner ??'
      AgentNameVersionMajor  : 'Cloud Web Security Scanner ??'
      AgentInformationUrl  : 'https://console.cloud.google.com/security/web-scanner'

```

**Comment by nielsbasjes** [comment]
Since this is a security scanning tool it is classified on almost all fields as `Hacker` and       `HackerToolkit` is set to `Google Security Scanner`.

Fixed

**Comment by FrancoisDevemy5** [comment]
> Since this is a security scanning tool it is classified on almost all fields as `Hacker` 

This is surprising. Isn't it just another robot?

**Comment by nielsbasjes** [comment]
My reasoning is that it is a system that someone uses to find security problems.
Just like nmap, nessus and openvas.

With tools like this it is clear it is not a normal visitor that is interested in the content of the website. 
What is uncertain is the reason behind this: is it to fix problems or to abuse them? 
So I classify all of them as hacking oriented tools.

Does this make sense to you?

**Comment by FrancoisDevemy5** [comment]
> Does this make sense to you?

Ok.
Maybe there should be a doc somewhere to explain these nuances?

**Comment by nielsbasjes** [comment]
Done: https://yauaa.basjes.nl/expect/fieldvalues/#values-explained
