### ISSUE TITLE
CFNetwork on macOS

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#614]
The x86_64 indicates that it is macOS not iOS.
```

- test:
    input:
      User-Agent  : 'Safari/15612.1.29.41.4 CFNetwork/1128.1 Darwin/19.6.0 (x86_64)'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Apple Macintosh'
      DeviceBrand  : 'Apple'
      DeviceCpu  : 'Intel x86_64'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS'
      OperatingSystemVersion  : '10.15.6 beta 2'
      OperatingSystemVersionMajor  : '10.15'
      OperatingSystemNameVersion  : 'Mac OS 10.15.6 beta 2'
      OperatingSystemNameVersionMajor  : 'Mac OS 10.15'
      LayoutEngineClass  : 'Desktop App'
      LayoutEngineName  : 'Safari'
      LayoutEngineVersion  : '15612.1.29.41.4'
      LayoutEngineVersionMajor  : '15612'
      LayoutEngineNameVersion  : 'Safari 15612.1.29.41.4'
      LayoutEngineNameVersionMajor  : 'Safari 15612'
      AgentClass  : 'Desktop App'
      AgentName  : 'Safari'
      AgentVersion  : '15612.1.29.41.4'
      AgentVersionMajor  : '15612'
      AgentNameVersion  : 'Safari 15612.1.29.41.4'
      AgentNameVersionMajor  : 'Safari 15612'

```

**Comment by nielsbasjes** [comment]
I agree that a specific Darwin version can either be a macOS or an iOS.

- https://en.wikipedia.org/wiki/Darwin_(operating_system)#Darwin_16_%E2%80%93_19;_OS_X_rebranded_into_macOS

Yet regarding this useragent pattern I have so far only been able to find statements like this:

> If you create an iOS app and retrieve data from a webserver, 
> the app will create a default user agent as 
> "AppName/version CFNetwork/version Darwin/version".

So for this pattern I now have that it is always an iOS version.

How do you know this to be wrong in this case?

Have you found a specification?

**Comment by FrancoisDevemy5** [comment]
I will look for a spec but with a little googling I haven't found something definitive.
But again, with `(x86_64)` I would say that even without spec it feels like it should be macOS and if we find something to contradict we could change it later.

**Comment by nielsbasjes** [comment]
Note that I consider the actual code (source or decompiled) that does it also a valid enough specification.

**Comment by nielsbasjes** [comment]
https://stackoverflow.com/a/46746999/114196

**Comment by nielsbasjes** [comment]
Ok, I'm convinced. I have fixed it.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Apps.yaml#L3729
