### ISSUE TITLE
Possibility to provide custom cache implementation

### ISSUE THREAD

**Issue by pawel-piecyk** [nielsbasjes/yauaa#62]
In current implementation there's only option to turn cache on/off and provide its size.  It would be great to have a possibility to provide another cache implementation.

We use yauaa in runtime, custom cache implementation would allow us to monitor hit rate, size etc.

**Comment by nielsbasjes** [comment]
Would this work in progress solve this for you ?
https://github.com/nielsbasjes/yauaa/tree/StructuralImprovements/analyzer/src/main/java/nl/basjes/parse/useragent

The UserAgentAnalyzerDirect does not have any caching so you can roll your own if you want to.

**Comment by pawel-piecyk** [comment]
Thank you, it looks promising :) I'm waiting for release then.

**Comment by nielsbasjes** [comment]
Hi, 
I merged this into master. 
Can you please check if this allows for what you want?
Note that the builder system has been completely rewritten to allow inheritance without duplicating methods over and over again.
Thanks.

**Comment by pawel-piecyk** [comment]
Hi,
Thanks for merging this. I like the separation to "core" user agent analyzer and cached one :) 

Btw. does this parse method in `UserAgentAnalyzerDirect` has to be still `synchronized` after separating cache layer to `UserAgentAnalyzer`?

**Comment by nielsbasjes** [comment]
Yes, that one needs to remain synchronized because there is only 1 set of matchers.

**Comment by nielsbasjes** [comment]
I just released version 3.0 with this in it.
It is currently on its way to maven central. Should be there in an hour or two.

**Comment by iNikem** [comment]
Hello, @nielsbasjes. First of all, thank you for work :) 

Is there somewhere any documentation or example how to provide custom cache?

**Comment by nielsbasjes** [comment]
I haven't documented this.
The UserAgentAnalyzerDirect is the implementation of the actual analyzer.
The UserAgentAnalyzer class is a subclass that only adds the caching.

The simplest way to get a custom caching implementation is to copy the UserAgentAnalyzer class to your own application and replace what you need.

Please let me know if this works for you.

**Comment by iNikem** [comment]
A, I see. Yep, that is good enough, thank you :)
