### ISSUE TITLE
Include input UserAgent in response when making batch reqs

### ISSUE THREAD

**Issue by pwm1991** [nielsbasjes/yauaa#632]
**Is your feature request related to a problem? Please describe.**

I did a batch run of ~2m useragents. Without the input useragent in each response, I had to map them back to the input in order to generate a 'complete' object of the input and output.

**Describe the solution you'd like**

When batch parsing UAs, include the input UA on each response. This is so that the response is 'complete' from the perspective of having the input value and output value together. When dealing with large number of UA, this means one doesn't have to do a mapping exercise back to the original values, which many(all?) users would have to do when doing large numbers of UAs.

**Describe alternatives you've considered**

I mapped them using py, which was fine.

**Additional context**

Used the webservlet via cli. 
YAUAA is great

**Comment by nielsbasjes** [comment]
Fixed.
I have pushed an updated (temporary) docker image so you can try it

    nielsbasjes/yauaa:7.2.1-SNAPSHOT
