### ISSUE TITLE
Upgrade to Antlr 4.7.1 when it is released.

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#65]
The upgrade should remove the need for this workaround:
https://github.com/nielsbasjes/yauaa/blob/master/analyzer/src/main/java/nl/basjes/parse/useragent/parse/UserAgentTreeFlattener.java#L267

for this problem

https://github.com/antlr/antlr4/issues/1949

**Comment by mmorel-35** [comment]
If you haven't noticed yet , 4.7.1 is available [here](https://github.com/antlr/antlr4/releases/tag/4.7.1)

**Comment by nielsbasjes** [comment]
Thanks for the heads up.
