### ISSUE TITLE
Frozen Mac OS version on Safari

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#656]
Hello,
On Safari 15 in macOS 12, I get this user agent, with the frozen version at 10.15.7.
I think it should be more in line with Firefox and Chrome. 
I saw that this policy is in place since Safari Technology preview 46 in 2017 but I don't know which version of Safari it corresponds to. Maybe between 11 and 12.
https://twitter.com/rmondello/status/943545865204989953

> Report frozen Mac OS X versions as ??:
Always [10_15_7](https://bugs.chromium.org/p/chromium/issues/detail?id=1175225) since Chrome 90.
Always [10.15](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#macintosh) since Firefox 87.

Furthermore, I vastly prefer what you did on Windows showing `Windows >=10 ` instead of just `Windows ??`.
Would it be possible to have something similar with masOS, like `macOS >=10.15`?

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Apple Macintosh'
      DeviceBrand  : 'Apple'
      DeviceCpu  : 'Intel'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS'
      OperatingSystemVersion  : '10.15.7'
      OperatingSystemVersionMajor  : '10.15'
      OperatingSystemNameVersion  : 'Mac OS 10.15.7'
      OperatingSystemNameVersionMajor  : 'Mac OS 10.15'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'AppleWebKit'
      LayoutEngineVersion  : '605.1.15'
      LayoutEngineVersionMajor  : '605'
      LayoutEngineNameVersion  : 'AppleWebKit 605.1.15'
      LayoutEngineNameVersionMajor  : 'AppleWebKit 605'
      AgentClass  : 'Browser'
      AgentName  : 'Safari'
      AgentVersion  : '15.5'
      AgentVersionMajor  : '15'
      AgentNameVersion  : 'Safari 15.5'
      AgentNameVersionMajor  : 'Safari 15'

```

**Comment by nielsbasjes** [comment]
https://bugs.webkit.org/show_bug.cgi?id=216593

**Comment by nielsbasjes** [comment]
Fixed.
