### ISSUE TITLE
Frozen Mac Version for Chrome / Firefox / Brave

### ISSUE THREAD

**Issue by dwdunham** [nielsbasjes/yauaa#696]
With the fix for https://github.com/nielsbasjes/yauaa/issues/656 it would be nice to handle frozen OS versions for all browsers the same. I've added example failing user agent strings from Chrome, Firefox and Brave

**The exact useragent**
useragents:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0" [Firefox]
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36" [Brave]
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" [Chrome]

**Expected/Incorrect fields**
OperatingSystemVersion: Expected: '>=10.15' or '>=10.15.7', Received: '??'

**Expected behavior**
Expect when the user agent string has "Mac OS X 10.15" to receive '>=10.15' if there are no client-hints that give a better version. [Firefox]
Expect when the user agent string has "Mac OS X 10_15_7" to receive '>=10.15.7' if there are no client-hints that give a better version. [Chrome, Brave]

**Additional information**
https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome/

**Comment by nielsbasjes** [comment]
I agree, this should be made consistent.

**Comment by nielsbasjes** [comment]
How about I make them all report `Mac OS >=10.15.7` (also the Firefox ones).
This way any reporting an filtering on the "Special Mac OS versions" becomes easier.

**Comment by nielsbasjes** [comment]
Fixed.
