### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by superbhimanshu** [nielsbasjes/yauaa#70]
I found a problem with this useragent.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36{${sleep(20)}}

Library throws a NullPointerException and webapp (https://analyze-useragent.appspot.com/)  displays the following:

![image](https://user-images.githubusercontent.com/7120105/33692289-2cd01806-dab2-11e7-94c7-fde0a199628a.png)

**Comment by nielsbasjes** [comment]
Thanks!
I fixed this immediately and updated the webapp.

**Comment by nielsbasjes** [comment]
I released version 3.3 that includes the fix for this. Should be in maven central in an hour or so.
