### ISSUE TITLE
UserAgentAnalyzer 实例化问题

### ISSUE THREAD

**Issue by gaofang07** [nielsbasjes/yauaa#702]
Can the new version of UserAgentAnalyzer be instantiated once for permanent resolution？

In the old version, this is a problem

**Comment by nielsbasjes** [comment]
I do not understand your problem. What "old version" do you mean?
I regularly instantiate the analyzer and leave it running for a long time. 
Only restarting because I updated the version.

**Comment by nielsbasjes** [comment]
So the answer is yes: You can (and should) instantiate it for many resolutions.
