### ISSUE TITLE
Add Agent minor version field

### ISSUE THREAD

**Issue by merlin-zaraza** [nielsbasjes/yauaa#73]
Please add `AgentNameVersionMinor` field to get minor version of user agent.
For example if I have Chrome version `56.0.2924.87`, the minor version is `0`

**Comment by nielsbasjes** [comment]
That would be `AgentVersionMajor` (without the 'Name').
I'll have a look how hard this is.
Curious: What is the usecase you need this for?

**Comment by merlin-zaraza** [comment]
Just for analytics. If it's hard to add - just skip it

**Comment by nielsbasjes** [comment]
I did some tests and found that it complicates things needlessly and I think there is only a limited use for having this in the base analysis. 
Simply doing a substring/stringsplit type of action is easy to do in almost any analytics environment in case anyone needs this.
So I chose not to implement this.
