### ISSUE TITLE
Opera 91

### ISSUE THREAD

**Issue by dianond** [nielsbasjes/yauaa#738]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

nl.basjes.parse.useragent:yauaa:7.5.0

**The exact useragent**
useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 OPR/91.0.4516.16'

**Expected/Incorrect fields**
"AgentName" -> {AgentField$ImmutableAgentField@16224} "{ value:'Opera', confidence:'2091', default:'Unknown', isDefault:false }"
"AgentVersion" -> {AgentField$ImmutableAgentField@16226} "{ value:'105', confidence:'3000', default:'??', isDefault:false }"
"AgentVersionMajor" -> {AgentField$ImmutableAgentField@16228} "{ value:'105', confidence:'3000', default:'??', isDefault:false }"
"AgentNameVersion" -> {AgentField$ImmutableAgentField@16232} "{ value:'Opera 105', confidence:'3000', default:'Unknown ??', isDefault:false }"
"AgentNameVersionMajor" -> {AgentField$ImmutableAgentField@16234} "{ value:'Opera 105', confidence:'3000', default:'Unknown ??', isDefault:false }"
...

**Expected behavior**
AgentVersion : 91
AgentVersionMajor : 91
AgentNameVersion : Opera 91
AgentNameVersionMajor : Opera 91

**Additional information**
"Sec-CH-UA-Arch" -> ""x86""
"Sec-CH-UA-Bitness" -> ""64""
"Sec-CH-UA-Full-Version" -> ""105.0.5195.102""
"Sec-CH-UA-Full-Version-List" -> ""Opera";v="105.0.5195.102", "Not)A;Brand";v="8.0.0.0", "Chromium";v="105.0.5195.102""
"Sec-CH-UA-Model" -> """"
"Sec-CH-UA-Platform-Version" -> ""10.0.0""
"Sec-CH-UA-WoW64" -> "?0"
"Sec-Ch-Ua" -> ""Not-A.Brand";v="99", "Opera";v="91", "Chromium";v="105""
"Sec-Ch-Ua-Mobile" -> "?0"
"Sec-Ch-Ua-Platform" -> ""Windows""

**Comment by nielsbasjes** [comment]
Thanks.
Indeed the result is incorrect.

How I understand the client hints is that they contain the better values than what is presented in the user agent.

Apparently when the user agent says

OPR/91.0.4516.16

And the client hints say

"Sec-CH-UA-Full-Version" -> ""105.0.5195.102""
"Sec-CH-UA-Full-Version-List" -> ""Opera";v="105.0.5195.102", "Not)A;Brand";v="8.0.0.0", "Chromium";v="105.0.5195.102""

This is not true.
I'll have to check if I can fix this in a reliable form.

Right now I consider this mostly to be a bug in Opera.

**Comment by dianond** [comment]
Thank you for your reply.

I think so too.

"Sec-CH-UA-Full-Version-List" 
In this item, Opera directly copied the information of Chrome, and then replaced its own name.

sec-ch-ua-full-version-list -> "Google Chrome";v="105.0.5195.127", "Not)A;Brand";v="8.0.0.0", "Chromium";v="105.0.5195.127"


"Sec-Ch-Ua"
In this item, the information is correct.

**Comment by nielsbasjes** [comment]
I fixed it.
Turns out that I already had a fix in place for the broken client hints.
What I did not yet have was an Opera useragent with a reduced Chrome version (i.e. the Chrome/105.0.0.0 part) which triggers an additional set of rules ... that broke the Opera version.

https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Opera.yaml#L1017

**Comment by nielsbasjes** [comment]
@dianond Just so you know: I have released a new version with this fix in it.

**Comment by dianond** [comment]
Thank you very much
