### ISSUE TITLE
Wrong CPU reported

### ISSUE THREAD

**Issue by zhangjunqiang** [nielsbasjes/yauaa#74]
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]
My Device CPU is Intel(R) Core(TM) i5-6500 CPU while the check result is AMD
```

- test:
    input:
      user_agent_string: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Desktop'
      DeviceBrand  : 'Unknown'
      DeviceCpu  : 'AMD x86_64'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Windows NT'
      OperatingSystemVersion  : 'Windows 7'
      OperatingSystemNameVersion  : 'Windows 7'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '65.0'
      LayoutEngineVersionMajor  : '65'
      LayoutEngineNameVersion  : 'Blink 65.0'
      LayoutEngineNameVersionMajor  : 'Blink 65'
      AgentClass  : 'Browser'
      AgentName  : 'Chrome'
      AgentVersion  : '65.0.3325.146'
      AgentVersionMajor  : '65'
      AgentNameVersion  : 'Chrome 65.0.3325.146'
      AgentNameVersionMajor  : 'Chrome 65'



```

**Comment by nielsbasjes** [comment]
Thanks for pointing this out.

I base this conclusion on the only specification I have regarding the "Win64; x64" that I have been able to find so far which is indeed for a different browser.
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537503(v=vs.85)#internet-explorer-user-agent-tokens

Here it says under feature tokens:

```
Win64; IA64     | System has a 64-bit processor (Intel).
Win64; x64      | System has a 64-bit processor (AMD).
```
Now for Chrome (which you have) I do not have any specification on this field so essentially I'm guessing that for Internet Explorer and Chrome both use the same specification.

At this point I'm tempted to make it more fuzzy and simply say in both of these cases something like "Intel x86_64" or  "Intel/AMD x86_64".

What do you think?

**Comment by nielsbasjes** [comment]
I decided to drop the "AMD" thing completely and simply got for the idea that saying "Intel x86_64" really means "Compatible with the Intel x86_64 cpus"
