### ISSUE TITLE
Wrong version detection on several UserAgent Strings

### ISSUE THREAD

**Issue by klopfdreh** [nielsbasjes/yauaa#75]
**Example 1 (IE 11)**
UserAgent: "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.1) like Gecko"
Actual Version: "11.0"
Right Version "11.1"

**Example 2 (FireFox 38)**
UserAgent: "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.3) Gecko/20100401 Mozilla/5.0 (X11; U; Linux i686; it-IT; rv:1.9.0.2) Gecko/2008092313 Ubuntu/9.25 (jaunty) Firefox/3.8"
Actual Version: "2008092313"
Right Version: "3.8"

**Example 3 (IE10)**
UserAgent: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)"
Actual Version: "9.0"
Right Version: "10.0"

**Example 4 (IE10)**
UserAgent: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/4.0; InfoPath.2; SV1; .NET CLR 2.0.50727; WOW64)"
Actual Vesion: "8.0"
Right Version: "10.0"

**Example 5 (IE10)**
UserAgent: "Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)"
Actual Version: "9.0"
Right Version: "10.0"

**Comment by nielsbasjes** [comment]
Thanks for reporting these examples.
First feedback:

Example 1: Fixed.

Example 2: This is a broken useragent string, or more specific; This is two totally different user agent strings concatenated. My system very often chooses the "first" part that matches. Also in several cases the relative position of fields matters. As such this example causes problems. If I just feed it the second half (i.e. starting at the second "Mozilla/") it does return Firefox 3.8 as expected. I have seen this before and in all of those cases I have seen it it was a measurement problem.

Examples 3,4,5: These are strange.
The Trident version indicates the IE version AND the MSIE indicates the IE version. 
Microsoft then also has a documented thing called compatibility mode which makes both of these indicate something different. 
See https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537503(v=vs.85)

Now according to what I understand is that IE 9 and up have a mode where they are compatible with IE 7 or 8. In that case the "Trident" will indicate the "Real" version and the MSIE will indicate the "Compatible with" version. In these 3 examples This has been flipped. These indicate that they are IE 8/9 running in a mode where they are compatible with IE 10.
These examples are not logical and also do not follow what MS has documented.

My question to you: Have these been modified? Perhaps hackers on your site?

**Comment by klopfdreh** [comment]
Hi @nielsbasjes,

Examples 3,4,5: I just took them out of Wickets Source Code (Unit Tests) - I guess they were added because of issues requested to be fixed by users. I think they are no hacks.

If they are faulty I would drop the Unit Tests and change them to real. If there might be an easy fix on your side it would be nice to have.

**Comment by nielsbasjes** [comment]
Understood. I see a way to fix this. Working on it.

**Comment by nielsbasjes** [comment]
I just released a new version of the software (version 4.2) that contains fixes for Examples 1,3,4,5. Example 2 is for me a "Won't fix" because this useragent is broken.
This new version should arrive at maven central within a few hours.
http://search.maven.org/#search%7Cga%7C1%7Cyauaa

**Comment by klopfdreh** [comment]
Thanks a lot! :-)
