### ISSUE TITLE
Windows 10 Chrome 106 OS version not resolved Bug report

### ISSUE THREAD

**Issue by aquacode** [nielsbasjes/yauaa#767]
I found a problem with this useragent.
[Please update the output below to match what you expect it should be]

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
      Sec-Ch-Ua  : '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"'
      Sec-Ch-Ua-Mobile  : '?0'
      Sec-Ch-Ua-Platform  : '"Windows"'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Desktop'
      DeviceBrand  : 'Unknown'
      DeviceCpu  : 'Intel x86_64'
      DeviceCpuBits  : '64'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Windows NT'
      OperatingSystemVersion  : '10'
      OperatingSystemVersionMajor  : '10'
      OperatingSystemNameVersion  : 'Windows NT ??'
      OperatingSystemNameVersionMajor  : 'Windows NT ??'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Blink'
      LayoutEngineVersion  : '106'
      LayoutEngineVersionMajor  : '106'
      LayoutEngineNameVersion  : 'Blink 106'
      LayoutEngineNameVersionMajor  : 'Blink 106'
      AgentClass  : 'Browser'
      AgentName  : 'Chrome'
      AgentVersion  : '106'
      AgentVersionMajor  : '106'
      AgentNameVersion  : 'Chrome 106'
      AgentNameVersionMajor  : 'Chrome 106'
      UAClientHintBrands_0_Brand  : 'Chromium'
      UAClientHintBrands_0_Version  : '106'
      UAClientHintBrands_1_Brand  : 'Google Chrome'
      UAClientHintBrands_1_Version  : '106'
      UAClientHintMobile  : 'false'
      UAClientHintPlatform  : 'Windows'

```

**Comment by nielsbasjes** [comment]
Based on the provided input it is not valid to conclude "Windows 10".
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**Comment by aquacode** [comment]
I've read that and request the client hints but ?? is still expected then?

**Comment by nielsbasjes** [comment]
Correct. The provided client hints in your case do not contain the information needed to conclude a specific windows version.

**Comment by nielsbasjes** [comment]
For reference compare this testcase I personally collected on a Windows 7 machine ([link](https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/ClientHints-Tests.yaml#L440)) which is almost identical to your testcase.
Only with the full client headers it becomes possible to determine the actual version of Windows used:  ([link](https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/ClientHints-Tests.yaml#L478)).
In this last example the version is derived from the 
```
Sec-Ch-Ua-Platform                         : '"Windows"'
Sec-Ch-Ua-Platform-Version                 : '"0.1.0"'
```

See also: https://yauaa.basjes.nl/using/clienthints/#analyzing-the-user-agent-client-hints

**Comment by aquacode** [comment]
Ok, that's fine, so we tested on a different machine, different user-agent for which the version resolved using the https://try.yauaa.basjes.nl/ tester app. However, using the lastest release of 7.6.0 it doesn't resolve within our app. Is it possible the tester app has more fixes than 7.6.0 because it is running the latest 7.6.1 snapshot and that perhaps we need to wait to get the additional fixes for a 7.7.0 release?

**Comment by nielsbasjes** [comment]
Yes you can test many different versions easily because many of them are still available in docker.
So you can just do something like this on your machine and test it out:

    docker run --rm -p 8080:8080 nielsbasjes/yauaa:7.6.0

Check this for what is currently available: https://hub.docker.com/r/nielsbasjes/yauaa/tags

**Comment by aquacode** [comment]
Perfect! That's helpful, thank you.
