### ISSUE TITLE
Pixel Watch using the Samsung Internet browser

### ISSUE THREAD

**Issue by wkeithvan** [nielsbasjes/yauaa#783]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'Mozilla/5.0 (Linux; Android 11; SAMSUNG Google Pixel Watch) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/1.2. Chrome/90'

**Expected/Incorrect fields**
Device Name: 'Google Pixel Watch'
Device Brand: 'Google'

**Expected behavior**
New device (Google Pixel Watch) using Samsung Internet for Wear OS (https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_GB&gl=US)

**Comment by nielsbasjes** [comment]
This looks a lot like this: https://yauaa.basjes.nl/expect/limitations/#some-are-simply-incorrect

**Comment by nielsbasjes** [comment]
I found specs which clearly hardcode the Samsung string.
https://developer.samsung.com/internet/user-agent-string-format.html

I'm going to try to build matching rules for this spec.

**Comment by nielsbasjes** [comment]
Fixed.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Samsung.yaml#L1094

**Comment by nielsbasjes** [comment]
I have just released version 7.8.0 which contains this fix.
