### ISSUE TITLE
hive udf use hive on spark  error

### ISSUE THREAD

**Issue by caotao94** [nielsbasjes/yauaa#791]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'your useragent'

**Expected/Incorrect fields**
fielda: 'expected value'
fieldb: 'expected value'
...

**Expected behavior**
i use yauaa-hive-7.8.0-udf.jar  in hive on spark
user temporary FUNCTION
22/11/02 13:49:16 ERROR status.SparkJobMonitor: Job failed with java.lang.NoClassDefFoundError: Could not initialize class nl.basjes.parse.useragent.UserAgentAnalyzer
	java.util.concurrent.ExecutionException: Exception thrown by job
		at org.apache.spark.JavaFutureActionWrapper.getImpl(FutureAction.scala:337)
		at org.apache.spark.JavaFutureActionWrapper.get(FutureAction.scala:342)
		at org.apache.hive.spark.client.RemoteDriver$JobWrapper.call(RemoteDriver.java:382)
		at org.apache.hive.spark.client.RemoteDriver$JobWrapper.call(RemoteDriver.java:343)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, yqg-bigdata-test-172-20-64-102, executor 1): java.lang.RuntimeException: Error processing row: java.lang.NoClassDefFoundError: Could not initialize class nl.basjes.parse.useragent.UserAgentAnalyzer

**Additional information**
If you know of specifications provided by the builder of the agent or system at hand then please provide these specifications.

**Comment by nielsbasjes** [comment]
I need more information to help you.
What caused the class not being initialized?

**Comment by nielsbasjes** [comment]
Can you please create a piece of code that reproduces the problem?

**Comment by caotao94** [comment]
i use hive engine is hive.execution.engine=spark
and rename the  yauaa-hive-7.8.0-udf.jar to userAgent-parse-udf.jar
and java udf is temporary FUNCTION

this my test example
and error info：
hive -e "set hive.execution.engine=mr;

add jar /data/apps/yqg_datatask_cheetah/warehouse/java_udf/userAgent-parse-udf.jar;

CREATE temporary FUNCTION ParseUserAgent
AS 'nl.basjes.parse.useragent.hive.ParseUserAgent';

insert overwrite table test.dwd_product_di_web_ua_info
select user_agent,
       ParseUserAgent(user_agent).OperatingSystemName as os,
       ParseUserAgent(user_agent).OperatingSystemVersion as os_version,
       ParseUserAgent(user_agent).AgentName as browser,
       ParseUserAgent(user_agent).AgentVersion as browser_version
  from (select 'Mozilla/5.0 (Linux; Android 9; HarmonyOS; STF-AL00; HMSCore 6.7.0.321; GMSCore 19.6.29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.4.302 Mobile Safari/537.36' as user_agent) tmp"

**Comment by caotao94** [comment]
[1667370329416.log](https://github.com/nielsbasjes/yauaa/files/9916869/1667370329416.log)

**Comment by nielsbasjes** [comment]
From my perspective there is a problem with your setup, not with the UDF.
At this point my best guess is that you specify the path to the jar file differently.
Your code: `add jar /data/apps/yqg_datatask_cheetah/warehouse/java_udf/userAgent-parse-udf.jar;`
My code:   `ADD JAR hdfs:///udf/yauaa-hive-7.8.0-udf.jar;`

The most notable difference: the `hdfs://` part.

**Comment by caotao94** [comment]
Thank you very much！I try again

**Comment by caotao94** [comment]
I need  'Mozilla/5.0 (Linux; Android 9; HarmonyOS; STF-AL00; HMSCore 6.7.0.321; GMSCore 19.6.29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.4.302 Mobile Safari/537.36' output
Android 9 Chrome 92.0.4515
but  output 
HarmonyOS	??	Huawei Browser	12.1.4.302
Could i use which classes?

**Comment by nielsbasjes** [comment]
The output you expect ('Android 9 Chrome 92.0.4515') is incorrect.
The output of the analyzer is correct.

**Comment by caotao94** [comment]
OK ,I got it, thanks.
