### ISSUE TITLE
Headless Edge

### ISSUE THREAD

**Issue by ikstewa** [nielsbasjes/yauaa#815]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.1418.42 Safari/537.36 Edg/107.0.1418.42'

useragent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.110 Safari/537.36 Edg/107.0.1418.56'

**Expected/Incorrect fields**
AgentName: 'Edge'
OperatingSystemVersion: '>=10'
...

**Expected behavior**
Expect the Agent to be classified as Edge, but it's classified as 'HeadlessChrome'

**Additional information**
https://user-agents.net/browsers/headless-edge

**Comment by nielsbasjes** [comment]
I see what happens here; the detection of Edge is aware it is more relevant than 'Chrome', have to add something similar for HeadlessChrome.

Do you know when this is used? Does this make it a Robot in the Cloud for example?

**Comment by nielsbasjes** [comment]
Fixed.
Now the AgentClass is "Robot" for these HeadlessChrome situations and the AgentName is either "Chrome" or "Edge" to make it consistent.

**Comment by ikstewa** [comment]
> I see what happens here; the detection of Edge is aware it is more relevant than 'Chrome', have to add something similar for HeadlessChrome.
> 
> Do you know when this is used? Does this make it a Robot in the Cloud for example?

I'm not sure where else it is used. We're using it internally for running headless test automation with Edge.

**Comment by nielsbasjes** [comment]
Understood. 
With version 7.9.0 (released today) you get "Edge" and AgentClass is "Robot".
