### ISSUE TITLE
Invalid operating system version for edge

### ISSUE THREAD

**Issue by ikstewa** [nielsbasjes/yauaa#816]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35'

**Expected/Incorrect fields**
OperatingSystemVersion: '>=10'
...

**Expected behavior**
Expected the platform version to be '>=10' regardless of Edge version. Newer edge version returns '??' instead.

**Additional information**
Previous edge version report appropriately:
useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62'

**Comment by nielsbasjes** [comment]
Yes you are correct. 
I had to fire up Edge on a Windows 7 and Windows 11 to verify what they are sending.
Windows 7 -> NT 6.1
Windows 10 -> NT 10.0
Windows 11 -> NT 10.0

**Comment by nielsbasjes** [comment]
Fixed
