### ISSUE TITLE
Chrome / Edge 109 on Windows 11 detected as Not_A Brand version 99

### ISSUE THREAD

**Issue by Fabien38300** [nielsbasjes/yauaa#886]
Please read this to ensure this is really a bug:
https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs

**The exact useragent**
useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.61'

**User-Agent client hints**
sec-ch-ua: "Not_A Brand";v="99", "Microsoft Edge";v="109", "Chromium";v="109"
sec-ch-ua-arch: "x86"
sec-ch-ua-bitness: "64"
sec-ch-ua-full-version: "109.0.1518.61"
sec-ch-ua-full-version-list: "Not_A Brand";v="99.0.0.0", "Microsoft Edge";v="109.0.1518.61", "Chromium";v="109.0.5414.87"
sec-ch-ua-mobile: ?0
sec-ch-ua-model: ""
sec-ch-ua-platform: "Windows"
sec-ch-ua-platform-version: "14.0.0"
sec-ch-ua-wow64: ?0

**Expected/Incorrect fields**
AgentName: Expected : 'Microsoft Edge' / Incorrect : 'Not_A Brand'
AgentVersion: Expected : '109' / Incorrect : '99'

**Expected behavior**
Microsoft Edge / Chrome correctly detected using User-Agent client hints

**Additional information**

**Comment by nielsbasjes** [comment]
Thanks!

**Comment by nielsbasjes** [comment]
I have found the cause and fixed it.
Since 'everyone' is using one of the affected browsers (I have found this with Chromium, Chrome and Edge) I'm putting out a release quickly.

Thanks for reporting this.

**Comment by nielsbasjes** [comment]
I have released 7.11.0 which includes this fix.
Thanks for reporting this important problem.

**Comment by Fabien38300** [comment]
Thanks!
