### ISSUE TITLE
UCBrowser classified as Tablet

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#89]
Using yauaa 4.5

For some reason UCBrowser user agents are classified as tablets. Is there any reason? By looking at UA itself it does not seem to contain device information

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 UCBrowser/10.4.1.565
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; ARM; Touch; WPDesktop) UCBrowser/4.2.1.541
Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Safari/537.36 UCBrowser/11.5.0.1015
Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.108 Safari/537.36 UCBrowser/12.5.5.1111
Mozilla/5.0 (Windows; U; Windows NT 5.2; zh-CN) AppleWebKit/537.51.1 (KHTML, like Gecko) Chrome/40.0.2214.89 Safari/537.36 UCBrowser/11.9.2.1062  AliApp(TUnionSDK/0.1.20.2)
Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/534.31 (KHTML, like Gecko) Chrome/17.0.558.0 Safari/534.31 UCBrowser/11.0.8.858
Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.108 Safari/537.36 UCBrowser/11.9.3.973
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 UCBrowser/10.10.8.820
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 UCBrowser/11.4.2.995
Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/534.31 (KHTML, like Gecko) Chrome/17.0.558.0 Safari/534.31 UCBrowser/11.0.4.846
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 UCBrowser/11.4.5.1005

**Comment by DaimonPl** [comment]
Just checked that 5.0 has same outcome

**Comment by nielsbasjes** [comment]
Thanks for reporting this problem and providing this nice list of examples.
Turns out for the UCBrowser I had a default value "Tablet" with a score that was a bit too high.
The above examples now all classify as Desktop instead.

I have updated the test site so you can try it
https://analyze-useragent.appspot.com/

Question: Do you perhaps know what this AliApp is in this one ?

  Mozilla/5.0 (Windows; U; Windows NT 5.2; zh-CN) AppleWebKit/537.51.1 (KHTML, like Gecko)
  Chrome/40.0.2214.89 Safari/537.36 UCBrowser/11.9.2.1062 **AliApp**(TUnionSDK/0.1.20.2)`

**Comment by DaimonPl** [comment]
No idea. I just checked yauaa against some older library on 6 months of real traffic. I checked where it reported different device class, checked manually and if yauaa looks to be wrong, reported those as issues.

**Comment by DaimonPl** [comment]
It looks like those UAs are now classified as desktop (Yauaa 5.1-SNAPSHOT)

**Comment by nielsbasjes** [comment]
Yes, I think that Windows NT 5.x and 6.x are desktop type systems.
Ok, so as I understand all these issues are indicating the differences between an other library.
So I expect in some cases Yauaa is wrong, and in some cases the other library is wrong.
Is that correct?

**Comment by DaimonPl** [comment]
Yep but I'm only reporting manually checked UAs which look to be yauaa issues.

I'm not reporting situations where there was a difference but yauaa was right :)

**Comment by nielsbasjes** [comment]
Ok, clear.
