### ISSUE TITLE
Tablets classified as phones

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#90]
Using yauaa 5.0

Mozilla/5.0 (Linux; Android 4.4.2; MID713 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.105 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.0.3; en-US; Sony Tablet S Build/TISU0143) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.4.0.982 U3/0.8.0 Mobile Safari/534.30

**Comment by nielsbasjes** [comment]
According to https://developer.chrome.com/multidevice/user-agent if it has "Mobile Safari" it is a phone. if it has just "Safari" it is a tablet.
Apparently these two do not follow this definition.

**Comment by nielsbasjes** [comment]
Fixed.
