### ISSUE TITLE
Bot/library classified as unknown

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#93]
Chromeless 1.3.0

**Comment by nielsbasjes** [comment]
I found that this tool is actually a plugin for Chrome that allows local and remote cloude based execution.
So effectively I have no idea what kind of device and/or operating system are used.

So at this point in time this seems the correct classification to me:

      DeviceClass                          : 'Unknown'
      DeviceName                           : 'Unknown'
      DeviceBrand                          : 'Unknown'

      OperatingSystemClass                 : 'Unknown'
      OperatingSystemName                  : 'Unknown'
      OperatingSystemVersion               : '??'

      LayoutEngineClass                    : 'Unknown'
      LayoutEngineName                     : 'Unknown'
      LayoutEngineVersion                  : '??'
      LayoutEngineVersionMajor             : '??'

      AgentClass                           : 'Special'
      AgentName                            : 'Chromeless'
      AgentVersion                         : '1.3.0'
      AgentVersionMajor                    : '1'
      AgentNameVersion                     : 'Chromeless 1.3.0'
      AgentNameVersionMajor                : 'Chromeless 1'
