### ISSUE TITLE
Mac Catalyst app

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#930]
Hello,

I have tested a Mac Catalyst app (i.e. an iPad app adapted to run on a Mac) and it produces wrong results:

```

- test:
    input:
      User-Agent  : 'Sandbox/1.0 (me.og4.local-full; build:1; macOS(Catalyst) 13.1.0) Alamofire/5.6.4'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Unknown'
      DeviceBrand  : 'Apple'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Mac OS'
      OperatingSystemVersion  : '13.1.0'
      OperatingSystemVersionMajor  : '13'
      OperatingSystemNameVersion  : 'Mac OS 13.1.0'
      OperatingSystemNameVersionMajor  : 'Mac OS 13'
      LayoutEngineClass  : 'Desktop App'
      LayoutEngineName  : 'Alamofire'
      LayoutEngineVersion  : '5.6.4'
      LayoutEngineVersionMajor  : '5'
      LayoutEngineNameVersion  : 'Alamofire 5.6.4'
      LayoutEngineNameVersionMajor  : 'Alamofire 5'
      AgentClass  : 'Desktop App'
      AgentName  : 'Sandbox'
      AgentVersion  : '1.0'
      AgentVersionMajor  : '1'
      AgentNameVersion  : 'Sandbox 1.0'
      AgentNameVersionMajor  : 'Sandbox 1'

```

**Comment by nielsbasjes** [comment]
Thanks!
I found that Alamofire is only a networking library.
So I don't think it is right to call it a LayoutEngine.

Do you have more examples of this (Catalyst/Alomofire) ?

**Comment by FrancoisDevemy5** [comment]
> I found that Alamofire is only a networking library.

Yes indeed.

> So I don't think it is right to call it a LayoutEngine.

Since it is a native app there is no layout engine at all really (well certainly not a web layout engine). So I leave this up to you whether you want to put something or nothing at all.

> Do you have more examples of this (Catalyst/Alomofire) ?

I have only my own app on my own laptop, so not yet.

**Comment by nielsbasjes** [comment]
Ok, Turns out I already had some examples and I've updated the rules to make sure your case is now also correct.
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Apps.yaml#L5285

I have to make a choice about the Layout engine for this. 
I think now it should be `Unknown`.
Still have to change that.

**Comment by nielsbasjes** [comment]
Fixed
