### ISSUE TITLE
Normal-looking UAs classified as Unknown

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#94]
Shouldn't those be desktop?

Mozilla/5.0 Galeon/1.2.0 (X11; Linux i686; U;) Gecko/20020326
Mozilla/5.0 Gecko/20100101 Firefox/16.0
Mozilla/5.0 (Windows; U; NT 5.1; en-MT) AppleWebKit/603.1.4 (KHTML, like Gecko) Version/3.0.4 Safari/603.1.4
Dillo/0.8.5-i18n-misc
Mozilla/5.0 (Windows; U; NT 6.1; en-SG) AppleWebKit/602.4.3 (KHTML, like Gecko) Version/4.0.1 Safari/602.4.3
Mozilla/5.0 (Windows; U; WinNT4.0; pl; rv:1.8.1.20) Gecko/20081217 Firefox/2.0.0.20
ELEMENT10 1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24
Mozilla/5.0 (Windows; U; NT 6.1; en-ZA) AppleWebKit/605.5.7 (KHTML, like Gecko) Version/5.0.3 Safari/605.5.7
Mozilla/5.0 (Windows; U; NT 5.1; en-NZ) AppleWebKit/536.21.19 (KHTML, like Gecko) Version/5.0.1 Safari/536.21.19
Mozilla/5.0 (Windows; U; NT 5.1; en-ZA) AppleWebKit/605.3.4 (KHTML, like Gecko) Version/5.0.1 Safari/605.3.4
Mozilla/5.0 (X11; U; DragonFly i386; de; rv:1.9.1) Gecko/20090720 Firefox/3.5.1
Mozilla/5.0 (Windows; U; NT 5.1; en-US) AppleWebKit/535.15.14 (KHTML, like Gecko) Version/3.0.4 Safari/535.15.14
Chrome/62.0.3202.94
Mozilla/4.0 (compatible; IBrowse 2.3; AmigaOS4.0)
Mozilla/5.0 (Windows; U; ) AppleWebKit/533.21.1 (KHTML, like Gecko) Zetakey/3.3.1
Mozilla/5.0 (Windows; U; NT 6.0; en-IN) AppleWebKit/536.19.23 (KHTML, like Gecko) Version/3.0.4 Safari/536.19.23

**Comment by nielsbasjes** [comment]
I assume the word "Unknown" at the start is not part of the UA?

**Comment by DaimonPl** [comment]
Yep, sorry for that. That's device class returned by yauaa. I forgot to remove it here

**Comment by nielsbasjes** [comment]
I fixed most of these.
Please tell me what you think of the current analysis output.
https://analyze-useragent.appspot.com/

**Comment by DaimonPl** [comment]
Looks ok. I might perform another run of tests when new version is available
