### ISSUE TITLE
Improve GraalVM support

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#943]
See also #710 for some more info.

**Comment by papegaaij** [comment]
I'm currently on vacation, but I'll give it a try next week.

**Comment by papegaaij** [comment]
@nielsbasjes The branch works fine on WildFly.

**Comment by nielsbasjes** [comment]
Thanks for helping out!

**Comment by nielsbasjes** [comment]
Last question: 
Do you perhaps have a link to a very very simple demo/example/tutorial which shows me how to do this myself?
I'm looking for the simplest possible thing that uses VFS which I can then turn into an integration test (using docker).
My goals is automatically ensure VFS support works during a release of a new version.

**Comment by nielsbasjes** [comment]
Thanks. I'm going to try this.
