### ISSUE TITLE
e-readers classified as desktops

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#95]
Mozilla/5.0 (Linux; Android; pl_PL) AppleWebKit/534.34 PocketBook/631 (screen 1072x1448; FW U631.5.17.1409) Mobile
Mozilla/5.0 (Linux like Android; pl_PL) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.1235) Mobile
Mozilla/5.0 (Linux; Android; ru_RU) AppleWebKit/534.34 PocketBook/631 (screen 1072x1448; FW U631.5.17.972) Mobile
Mozilla/5.0 (Linux like Android; pl_PL) AppleWebKit/534.34 PocketBook/626 (screen 1024x758; FW W626.5.14.1286) Mobile
Mozilla/5.0 (Linux like Android; pl_PL) AppleWebKit/534.34 PocketBook/631 (screen 1072x1448; FW U631.5.17.953) Mobile
Mozilla/5.0 (Linux like Android; pl_PL) AppleWebKit/534.34 PocketBook/624 (screen 600x800; FW W624.4.3.216) Mobile
Mozilla/5.0 (Linux; Android; pl_PL) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.1475) Mobile
Mozilla/5.0 (Linux like Android; pl_PL) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.1096) Mobile
Mozilla/5.0 (Linux; Android; pl_PL) AppleWebKit/534.34 PocketBook/740 (screen 1404x1872; FW U740.5.17.1255) Mobile
Mozilla/5.0 (Linux like Android; en_US) AppleWebKit/534.34 PocketBook/626 (screen 758x1024; FW W626.5.14.1096) Mobile

**Comment by nielsbasjes** [comment]
Fixed
