### ISSUE TITLE
Smartphones classified as desktops

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#96]
Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; PSP8500DUO) like Gecko
Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; Nokia 625H) like Gecko
Mozilla/5.0 (Linux; U; Android Zoe ROM 7.7 - CM7.2 - SDSL v4; pl-pl; LG-GT540 Build/GWK74; -=Zoe ROM=-) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
Mozilla/5.0 (X11; U; Linux armv7l; en-US; rv:1.9.2.3pre) Gecko/20100723 Firefox/3.5 Maemo Browser 1.7.4.8 RX-51 N900
Mozilla/5.0 (Linux; Android ; VM_Vertis 4010 You Build/VM AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; PSP8400DUO) like Gecko

**Comment by nielsbasjes** [comment]
Please tell me what you think of the current analysis output.
https://analyze-useragent.appspot.com/

**Comment by DaimonPl** [comment]
Looks ok. I might perform another run of tests when new version is available
