### ISSUE TITLE
Missing/undocumented values in FieldValues page

### ISSUE THREAD

**Issue by pcct** [nielsbasjes/yauaa#966]
I have done some experimentation and detected some undocumented values for AgentClass (`DesktopApp`) and LayoutEngineClass (`Cloud` and `DesktopApp`) that are missing from [FieldValues page](https://github.com/nielsbasjes/yauaa/blob/main/documentation/content/expect/FieldValues.md)

**Comment by pcct** [comment]
I would create the pull request myself but I'm not sure what the definitions should be or if there are other ones missing

**Comment by nielsbasjes** [comment]
I'll fix this. Thanks for reporting.

**Comment by nielsbasjes** [comment]
Fixed
