### ISSUE TITLE
Some pretty-sure-mobile classified as Unknown

### ISSUE THREAD

**Issue by DaimonPl** [nielsbasjes/yauaa#97]
NokiaE52-1/SymbianOS/9.1 Series60/3.0 3gpp-gba
Mozilla/5.0 \(Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D\) AppleWebKit/535.19 \(KHTML, like Gecko\) Chrome/18.0.1025.166 Mobile Safari/535.19;__CT_JOB_ID__:75033994-b6fc-48a1-9e1b-15bf115d9292;
Mozilla/5.0 (iPhone1 06; CPU iPhone OS 11_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 MQQBrowser/8.0.2 Mobile/15B87 Safari/8536.25 MttCustomUA/2 QBWebViewType/1 WKType/1
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1089_1038) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_PL; pl; scale=1.50; gamut=normal; 540x960)
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1072_1045) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; ru_PL; ru; scale=2.00; gamut=normal; 720x1280)
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1045_1011) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_PL; pl; scale=3.00; gamut=normal; 1080x1920)
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1118_13880) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_DE; pl; scale=4.00; gamut=normal; 1440x2560)
Mozilla/5.0 \(iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us\) AppleWebKit/537.51.1 \(KHTML, like Gecko\) Version/7.0 Mobile/11A465 Safari/9537.53;__CT_JOB_ID__:61e58770-4309-4c54-beac-bf9c14a794e8;
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1099_1016) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; uk_RU; uk; scale=1.50; gamut=normal; 480x800)
Mozilla/5.0 (iPhone1 01; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 MQQBrowser/8.3.0 Mobile/15B87 Safari/604.1 MttCustomUA/2 QBWebViewType/1 WKType/1
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1085_15171) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_PL; pl; scale=3.00; gamut=normal; 1440x2560)
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1045_1046) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_PL; pl; scale=3.00; gamut=normal; 1080x1920)
Mozilla/5.0 \(Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D\) AppleWebKit/535.19 \(KHTML, like Gecko\) Chrome/18.0.1025.166 Mobile Safari/535.19;__CT_JOB_ID__:0171e451-c0e6-4d34-93d1-9d828a6daca7;
Mozilla/5.0 (osmeta like iPhone; U; osmeta 10.3.2132; RM-1045_1086) AppleWebKit/602.1.1 (KHTML, like Gecko) Mobile/2132 Instagram 10.32.0 (Windows Phone; osmeta/Windows Phone 10_3_2132; pl_PL; pl; scale=2.50; gamut=normal; 1080x1920)

**Comment by nielsbasjes** [comment]
I fixed the Nokia case.
Most other refer to 'osmeta' which I currently do not yet understand.

**Comment by nielsbasjes** [comment]
I have fixed all of these cases.
Please check.
 https://analyze-useragent.appspot.com/

**Comment by nielsbasjes** [comment]
I'm closing this as "Fixed". 
Please reopen if I made a mistake somewhere.
