### ISSUE TITLE
AliApp ?

### ISSUE THREAD

**Issue by nielsbasjes** [nielsbasjes/yauaa#99]
Mozilla/5.0 (Windows; U; Windows NT 5.2; zh-CN) AppleWebKit/537.51.1 (KHTML, like Gecko)
Chrome/40.0.2214.89 Safari/537.36 UCBrowser/11.9.2.1062 AliApp(TUnionSDK/0.1.20.2)

**Comment by darkal** [comment]
It looks like an app developed by alibaba.

**Comment by nielsbasjes** [comment]
Fixed
